### ISSUE TITLE
Can't close the sliding?Android does not need to sliding function.

### ISSUE THREAD

**Issue by pheromone** [jemise111/react-native-swipe-list-view#100]
excuse me.
1.不能都关闭滑动?Android不需要滑动功能
   Can't close the sliding?Android does not need to sliding function
2.只使用SwipeRow,不使用SwipeListView,可以实现只能滑动一个吗?
only use SwipeRow,not use SwipeListView,Slide can be only one?

![default](https://cloud.githubusercontent.com/assets/14305431/23006147/1e998302-f43b-11e6-8d73-b2620d042455.gif)

**Comment by jemise111** [comment]
Hey @pheromone there shouldn't be any difference between Android and iOS. If there is, it's a bug. Can you please paste the code you're using with the `<SwipeRow />`?

**Comment by jemise111** [comment]
Going to close this as it has been inactive for a while
