### ISSUE TITLE
how to use scrollTo in SwipeListView

### ISSUE THREAD

**Issue by wuyi51** [jemise111/react-native-swipe-list-view#102]
how to use scrollTo in SwipeListView

**Comment by jemise111** [comment]
Hey @wuyi51. There's a prop on the SwipeListView called `listViewRef` where you can get a ref to the underlying `<ListView />` and call whatever methods on it you like. To use `scrollTo` do something like this:

```
class ComponentClass extends React.Component {

	scrollToSomewhere() {
		this._listViewRef.scrollTo({y: 300});
	}

	render() {
		return (
			<SwipeListView
				listViewRef={ref => this._listViewRef = ref}
			/>
		);
	}
}

```

**Comment by jemise111** [comment]
I'm going to close this. If you have any further problems please reopen, thanks!
