### ISSUE TITLE
Missing swipeToClosePercent prop

### ISSUE THREAD

**Issue by pshurygin** [jemise111/react-native-swipe-list-view#108]
There is a swipeToOpenPercent prop, which allows you to control how far you need to swipe to open the row, but there is no similar functionality for closing the row. I believe it should either be a separate prop or the existing prop should affect both opening and closing behavior.

**Comment by peterdev6** [comment]
Any updates on this issue?

**Comment by jemise111** [comment]
There is an open PR ( #148 ). Should be merged in and released very soon

**Comment by jemise111** [comment]
This has been fixed by #148 and is in the latest release (v0.4.6)
