### ISSUE TITLE
error when i run the example

### ISSUE THREAD

**Issue by ramy612** [jemise111/react-native-swipe-list-view#11]
after i npm install the component and i wrote the codes just like the example, but when i run
 the app, it shows 

Element type is invalid: expected a string(for built-in components) or a class/function (for composite components) but got: object. Check the render method of 'TestSwipeListView'

I really don't know why? would you help me? THX

**Comment by Thorbenandresen** [comment]
Have you modularized you components and maybe forgot to `module.exports` it? It would help if you could post your code.

**Comment by jemise111** [comment]
Hey @ramy612, like @Thorbenandresen said could you please post your TestSwipeListView code. There's likely an issue in that file. Happy to take a look. Thanks!

**Comment by ramy612** [comment]
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict'

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  View,
  ListView
} from 'react-native';

var SwipeListView = require('react-native-swipe-list-view');

var dataSource = [
  {data: 'a'},
  {data: 'b'},
  {data: 'c'},
];

class pandaswipelistview extends Component {
  render() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});

    return (
      <SwipeListView
        dataSource={ds.cloneWithRows(dataSource)}
        renderRow={ data => (
          <View>
            <Text>test</Text>
          </View>
        )}
        renderHiddenRow={ (data) => (
          <View>
            <Text>Left</Text>
            <Text>Right</Text>
          </View>
        )}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('pandaswipelistview', () => pandaswipelistview);
`

@jemise111 @Thorbenandresen

**Comment by jemise111** [comment]
Hey @ramy612 - found the issue.

Change
```var SwipeListView = require('react-native-swipe-list-view');```

to
```var { SwipeListView } = require('react-native-swipe-list-view');```

This package exports two components so you just have to specify which one in your require statement.

Closing the issue. Please let me know if you have any more problems and I'll re open. Thanks!

**Comment by ramy612** [comment]
yeah, thx for your kindly help! problem solved! @jemise111
