### ISSUE TITLE
Need to set leftOpenValue and rightOpenValue different for each item

### ISSUE THREAD

**Issue by ithieund** [jemise111/react-native-swipe-list-view#111]
@jemise111 ,
These prop should be override in each item as sometimes the button in each item are not the same.
leftOpenValue={0}
rightOpenValue={-90}

Can you please make this feature available in next release?
Thanks.

**Comment by jemise111** [comment]
Hey @ithieund, thanks for the question. This feature is already available! Have a look at the documentation here:

https://github.com/jemise111/react-native-swipe-list-view#per-row-behavior

And if you're still having any problems feel free to reopen

**Comment by ithieund** [comment]
@jemise111 ,
Awesome!
Thank you very much for your help.
