### ISSUE TITLE
how do we possible to add footer and header

### ISSUE THREAD

**Issue by jjhesk** [jemise111/react-native-swipe-list-view#113]
It will be desired to adding footer and header with no swipe interactions. How can it be done?

**Comment by jemise111** [comment]
@jjhesk have you tried the using the ListView props `renderHeader` and `renderFooter`? Whatever components are passed to those props should not have any swipe interactions on them.

https://facebook.github.io/react-native/docs/listview.html#renderfooter

**Comment by jjhesk** [comment]
yes it worked. @jemise111

**Comment by dvisco** [comment]
It's worthwhile to mention that when using the `Flatlist` implementation you'll need to use the `ListFooterComponent` and `ListHeaderComponent` props instead.

https://facebook.github.io/react-native/docs/flatlist.html#listfootercomponent
