### ISSUE TITLE
Click on swipe listview renderHiddenRow is visible

### ISSUE THREAD

**Issue by MhtSuthar** [jemise111/react-native-swipe-list-view#116]
All are implement is very good but i have implement click on your swipe list view than hidden row visible, how to resolve this issue, i use this code for row
renderRow(rowData, sectionID, rowID) {
        return (
            <TouchableOpacity onPress={() => this.clickMinimize(rowData, sectionID, rowID)} >
            <View style={styles.rowFront}>
                <Text>I am {rowData.row} in a SwipeListView</Text>
                <Text>I am {""+rowData.isSelect} </Text>
            </View>
            </TouchableOpacity>
        );
    }

and this fir hiddenrow
 renderHiddenRow(rowData, sectionID, rowID, rowMap) {
        return (
            <View style={styles.rowBack}>
                <Text>Left</Text>
                <TouchableOpacity onPress={() => this._onPressRow(rowID, rowData, sectionID, rowMap)}>
                    <Image
                        source={require('../images/ic_delete.png')} style={{ width: 30, height: 30, marginLeft: 0, marginRight: 0 }} />
                </TouchableOpacity >
            </View>
        );
    }

**Comment by alexcoady** [comment]
@MhtSuthar The nature of this plugin is that the hidden row sits behind the visible row, if you're using `TouchableOpacity` in your normal `renderRow` function, you *will* see the hidden row behind while transparency is applied.

**Comment by jemise111** [comment]
@alexcoady Is absolutely right. I would recommend using a `TouchableHighlight` instead of `TouchableOpacity`. Going to close this
