### ISSUE TITLE
How to change the disableLeftSwipe state

### ISSUE THREAD

**Issue by sagexy** [jemise111/react-native-swipe-list-view#118]
In normal mode 
disableLeftSwipe:{true}

In edit mode
disableLeftSwipe:{false}

how to change the state with other button click

I tried the code
![image](https://cloud.githubusercontent.com/assets/4734448/25217451/93ced206-25d9-11e7-8994-f7e3f49c6061.png)

and  button onPress function

    onPressEditButton() {
        this.setState({
            isEditing:true
        });

        console.log('disableLeftSwipe:', this.listView.props.disableLeftSwipe);
    }

but it still can't swipe

**Comment by jemise111** [comment]
@sagexy are you setting `disableLeftSwipe={!this.state.isEditing}` ?

**Comment by sagexy** [comment]
@jemise111  yes 

    render(){
        const isEditing = this.state.isEditing;
        ......
        <SwipeListView
                        dataSource={this.state.dataSource}
                        renderRow={this.renderList.bind(this)}
                        style={styles.listView}
                        rightOpenValue={-70}
                        disableRightSwipe={true}
                        disableLeftSwipe={!isEditing}
                        renderHiddenRow={ () => (
                            <View style={styles.rowBack}>
                                <TouchableOpacity style={styles.backRightBtn}>
                                    <Text style={styles.deleteTitleStyle}>delete</Text>
                                </TouchableOpacity>
                            </View>
                        )}
                        ref = {e=>this.listView=e}
                    />
    }

**Comment by jemise111** [comment]
@sagexy Just confirmed again that this is working for me locally. Going to close this as I really don't think there's an issue here. If it's still a problem for you please reopen and paste the full code (including the constructor and the logic around the button click) and I'll be happy to take another look, thanks!

(sorry for the delay in responding)
