### ISSUE TITLE
When add list with tab navigator the performance of TabNavigator slow

### ISSUE THREAD

**Issue by farrukhbashir** [jemise111/react-native-swipe-list-view#121]
I use a Tab Navigator in one tab I Display a Swipe-List-View .When I Click on This Tap the SwiplistView come after a little bit pause and it look like a glitch....Is there any solution to remove the pause on tabNavigator when tab click ...I think so tabNavigator Every time rerender may be that why error come is any method to stop rerender in tabnavigator

**Comment by peterdev6** [comment]
same issue...

**Comment by jemise111** [comment]
Going to close as this has been inactive for a while and is not related to this package. This sounds like a problem with the TabNavigator re-rendering and would likely happen to any `ListView`
