### ISSUE TITLE
How to explicitly close a row after it has already been swiped

### ISSUE THREAD

**Issue by zrsb** [jemise111/react-native-swipe-list-view#122]

**Comment by zrsb** [comment]
i am sorry
`<SwipeList
    renderHiddenRow={ (data, secdId, rowId, rowMap) => {
        <TouchableOpacity onPress={ _ => rowMap[`${secId}${rowId}`].closeRow() }>
            <Text>I close the row</Text>
        </TouchableOpacity>
    }}
/>`

**Comment by jemise111** [comment]
Hey @zrsb seems like you got it. Going to close this. Please re open if you're having any problems, thanks
