### ISSUE TITLE
when i add a textInput into the listview ,sometimes the keyboard flashes and can't input anything.

### ISSUE THREAD

**Issue by XIAOYAYAYAYA** [jemise111/react-native-swipe-list-view#127]
when i add a textInput into the listview ,sometimes the keyboard flashes and can't input anything.
for example ,when i click the textInput which into the listview at the bottom of the screen,the keyboard just  suddently appearance and suddently closed ,but textInputs that at the top of the screen will not happen ,    i don't know why  ?  is there someone knows about it?

**Comment by XIAOYAYAYAYA** [comment]
![image](https://cloud.githubusercontent.com/assets/26213730/26335329/a0103ce8-3f9d-11e7-8e29-6ac30e2d7b13.png)

**Comment by XIAOYAYAYAYA** [comment]
and i find that  when the listview scroll to the bottom,it will close current keybroad,so i want to know where can i change the code to forbid listview close current keybroad when scroll to the bottom?

**Comment by AndreyPatseiko** [comment]
have the same problem (

**Comment by XIAOYAYAYAYA** [comment]
I solve this problem by using ScrollView instead of listview ,  you can have a try ScrollView binding Array.map()

**Comment by jemise111** [comment]
Going to close this as it's been inactive for a while and it looks like @XIAOYAYAYAYA found a solution. Thanks
