### ISSUE TITLE
Prevent to close actual opened row

### ISSUE THREAD

**Issue by vendramini** [jemise111/react-native-swipe-list-view#129]
I would like to open/close rows independently. Actually, every time I open one and try to open another one, it closes the first one.

I noticed that the function `safeCloseOpenRow` is called. So I go into it and we can see that the current opened row will be closed: `this._rows[this.openCellId].closeRow();`

Is there a way to do what i want without changing original code? And more: is there some problem to do this behavior that i want?

Regards.

**Comment by seclace** [comment]
@vendramini Hi! You can do this with using `ListView` with renderRow set to `SwipeRow`.

    <ListView
        dataSource={this.ds.cloneWithRows(this.props.data)}
        renderRow={this.renderRow}
    />

    renderRow = () => (
        <SwipeRow>
            <View style={styles.hiddenRow} />
            <View style={styles.row} />
        </SwipeRow>
    );

This makes each SwipeRow independent from others.

**Comment by vendramini** [comment]
@seclace Not too late! I have been working on other modules of this app, and I'm coming back for this issue now. I tested here and you are right! Thank you!

But this approach create another problem for me. I was using `SwipeListView` with `SwipeRow`, and on `renderRow` method I have access to `(data, secId, rowId, rowMap)` so I can close the row pressing a button with: 
```javascript 
rowMap[`${secId}${rowId}`].manuallySwipeRow(Dimensions.get('window').width); 
```
Now I don't have this information.

Do you know how to close a row now? I will try and back here when succeeded.

**Comment by seclace** [comment]
Oh, I don't know what version you are using now, but my version is `0.4.1` and there you can simply call the `closeRow()` method to close the row :)
Such as:
```javascript
rowMap[`${secId}${rowId}`].closeRow();
```

**Comment by vendramini** [comment]
Yes, I was using this code, but inside a `SwipeList` that pass those parameters to the `renderRow` function.

Now, I'm using a `<FlatList>` with `renderItem=<SwipeRow>` as you said, to make they independent. (I changed `ListView` with `FlatList`.

**Comment by seclace** [comment]
Sorry, I forgot that it needs for independent `swipeRow`. For call `closeRow` for independent `swipeRow` you need to refer to it's `ref`, for example:
```javascript
render() {
    return <SwipeRow ref={ref => this.ref = ref} />
}

closeRow() {
    this.ref.closeRow();
}
```
And then you can use it anywhere in component or it's children.

**Comment by jemise111** [comment]
Sorry for the late response here.

Looks like @seclace found a solution for you, thanks!

Also @vendramini if you do end up using the `SwipeListView` again you can use the `closeOnRowBeginSwipe` to disable that behavior.

Going to close this issue, please re open if you're still having problems, thanks!
