### ISSUE TITLE
View.propTypes has been deprecated

### ISSUE THREAD

**Issue by williams-voon** [jemise111/react-native-swipe-list-view#130]
Hi,

View.propTypes has been deprecated in RN 0.44.

Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

The file:
react-native-swipe-list-view/components/SwipeRow.js	

The code:
/**
	 * Styles for the parent wrapper View of the SwipeRow
	 */
	style: View.propTypes.style,

Please fix it, thank you very much!

Regards,
Williams Soon

**Comment by elieteyssedou** [comment]
Seems to be important in my opinion ! I don't like very much having an error in the console.

Can someone please fix it ?

**Comment by jemise111** [comment]
This is fixed and will be release in the next version

**Comment by jemise111** [comment]
Fixed in v0.4.2
