### ISSUE TITLE
I can drag the item to left without limit

### ISSUE THREAD

**Issue by cielu** [jemise111/react-native-swipe-list-view#133]
as the title descript , I can drag the list item to left without limit . That will result app stopped once a while . suggest: user can drag a item in a fixed width , but out of this width user can do nothing

**Comment by rcorrie** [comment]
`stopLeftSwipe` and `stopRightSwipe` let you set hard limits for the swipe.

**Comment by jemise111** [comment]
@rcorrie is right here. You should be able to limit swiping with those props. Going to close this, please reopen if you're still having problems, thanks!

(sorry for the delay in responding!)
