### ISSUE TITLE
Open row on press

### ISSUE THREAD

**Issue by kyangy** [jemise111/react-native-swipe-list-view#137]
Hi, is there a way to manually open a row by an onPress?

**Comment by jemise111** [comment]
Hey @kyangy, this behavior is currently technically supported but there is some hackery you could do in meantime:

```
class Example {

  openRow = (rowRef) => {
    // Use an internal method to manually swipe the row open to whatever value you pass
    rowRef.manuallySwipeRow(50);
  }

  render() {
    <SwipeListView
       renderRow={ (data, secId, rowId, rowMap) => (
	  <TouchableHighlight
             onPress={ _ => this.openRow(rowMap[`${secId}${rowId}`])}
          />
       }
    />
  }

}
```

Hope that helps!

(sorry for the delay in responding!)

**Comment by jemise111** [comment]
Closing as this seems to be sufficient for most people

**Comment by fdelavra** [comment]
Hello and thanks for your answer. Can you explain a little bit how and where to create this function?
