### ISSUE TITLE
Cannot read property 'closeRow' of undefined

### ISSUE THREAD

**Issue by ramy612** [jemise111/react-native-swipe-list-view#14]
`import { SwipeRow, SwipeListView } from 'react-native-swipe-list-view';

< SwipeListView
  dataSource={this.state.dataSource}
  renderRow={this._renderRow}
  renderHiddenRow={ (data, sectionID, rowID, rowMap) => (
    < View style={styles.rowBack}>
      < TouchableOpacity style={[styles.backRightBtn, styles.backRightBtnRight]} onPress={ _ => rowMap[rowID].closeRow()}>
        < Text>delete< /Text>
      < /TouchableOpacity>
      < TouchableOpacity style={[styles.backRightBtn, styles.backRightBtnLeft]} onPress={ _ => rowMap[rowID].closeRow()}>
        < Text>cancel< /Text>
      < /TouchableOpacity>
    < /View>
   )}
   leftOpenValue={0}
   rightOpenValue={-150}
   renderSeparator={(sectionID, rowID) => <View key={`${sectionID}-${rowID}`} style={styles.separator} />}
   disableRightSwipe={true}
 />`

I wrote codes like above, but when I run the app, the screen tells me "Cannot read property 'closeRow' of undefined", at fiirst i thought it might be the low version of react native caused this problem, but after i updated my react native to 0.24.1, the problem still occurred. Is there any wrong usage in my codes? I really don't know what is going on here……

**Comment by jemise111** [comment]
@ramy612 Please see this section of the README: https://github.com/jemise111/react-native-swipe-list-view#manually-closing-rows. The latest update released a breaking change so you have to do things slightly differently.

Also see here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/example.js#L25

That shows a working example of closing a row. You can ignore the part about deleting.

Please let me know if you still have problems or I can close this, thanks!

**Comment by ramy612** [comment]
@jemise111 I changed my code to the form that you give me like below:

`import { SwipeListView, SwipeRow } from 'react-native-swipe-list-view';

            < SwipeListView
                dataSource={this.state.dataSource}
                renderRow={this._renderRow}
                renderHiddenRow={ (data, sectionID, rowID, rowMap) => (
                    < View style={styles.rowBack}>
                        < TouchableOpacity style={[styles.backRightBtn, styles.backRightBtnRight]} onPress={ _ => this._closeRow(sectionID, rowID, rowMap)}>
                            < Text>delete< /Text>
                        </TouchableOpacity>
                    < /View>
                )}
                leftOpenValue={0}
                rightOpenValue={-150}
                renderSeparator={(sectionID, rowID) => <View key={`${sectionID}-${rowID}`} style={styles.separator} />}
                disableRightSwipe={true}
            />

_closeRow: function(sectionID, rowID, rowMap) {
        rowMap['${sectionID}${rowID}'].closeRow();
    },
`

but i still got the "Cannot read property 'closeRow' of undefined" message. Problem still not solved. I tried many times still cannot figure out why……

**Comment by ramy612** [comment]
@jemise111 problem solved. my fault, i use ' not `, my god,hahah, thank you very very much

**Comment by jemise111** [comment]
Ahh damn I missed that too. Glad it's working! Closing
