### ISSUE TITLE
repo maintained

### ISSUE THREAD

**Issue by nonotest** [jemise111/react-native-swipe-list-view#141]
Hello,

is this still maintained / active?
there are some useful PRs that could be merged :)

thanks!

**Comment by jemise111** [comment]
Hey @nonotest,

Yes this repo is still being maintained / is active. I've been traveling / working a lot recently and have fallen behind in addressing issues and PRs.

I'll do my best to get those PRs merged in and a new release out in the next couple days. And take a look at issues as well.

If anyone's interested in being a maintainer shoot me an email (jesse [dot] sessler [at] gmail)

Thanks! :)

**Comment by nonotest** [comment]
thank you! I am happy to help where I can, let me know if you need help reviewing things etc.

**Comment by jemise111** [comment]
Going to close this issue now. I have a lot more time on my hands and will be much more active.

Apologies for the long absence. I've addressed / merged all open PRs and have gone through over half the open issues. Will be addressing the other half and trying to solve as many as possible going forward.
