### ISSUE TITLE
Element type is invalid:

### ISSUE THREAD

**Issue by dzonel** [jemise111/react-native-swipe-list-view#142]
![img_0205](https://user-images.githubusercontent.com/12531667/28865670-4ed0f316-77a3-11e7-8140-ac3bfe8861ae.PNG)

**Comment by jemise111** [comment]
Hey @dzonel make sure you are important just the component you need and not the entire library. i.e. do this:
```
import { SwipeListView } from 'react-native-swipe-list-view';
```

and do NOT do this

```
import SwipeListView from 'react-native-swipe-list-view';
```

Going to close this issue but please re-open and show some example code if you're still having problems, thanks!

(sorry for the delay in responding)

**Comment by dzonel** [comment]
Thank you so much

**Comment by AlbertMontolio** [comment]
The official documentation does said that
https://github.com/oliviertassinari/react-swipeable-views
