### ISSUE TITLE
How to let all cells scroll?

### ISSUE THREAD

**Issue by lenglengiOS** [jemise111/react-native-swipe-list-view#146]
I want to make all cells move to right, that i can show checkbox.

![image](https://user-images.githubusercontent.com/21171262/29737667-7c27bbf2-8a44-11e7-8924-fcb98edef109.png)

**Comment by seclace** [comment]
may be it is not the best way, but a solved it by wrapping it in another component and put there more one listview component, so I have 1 parent wrapper, which has 2 children - listviews.

**Comment by jemise111** [comment]
Hey @lenglengiOS that behavior isn't really supported and isn't quite what this component is designed for (the use case is really swiping open rows on a row by row basis) but I think you could make this work by either:

1. Doing what @seclace suggested and sliding the entire ListView to the right
2. Wrapping your rows in an `<Animated />` component and controlling that animation yourself

Going to close this as it's not really an issue, but happy to help further in any way I can, thanks!

(sorry for the delay in responding!)
