### ISSUE TITLE
onRowClose() is called even the row is already closed.

### ISSUE THREAD

**Issue by sandeep-t2s** [jemise111/react-native-swipe-list-view#150]
I am using the FlatListview like

```
<FlatListview>
          renderItem= <swipeRow 
                                 onRowClose = {()=>{console.log("row closed")}}
                          
                              >
          .. .. 
```

**Comment by jemise111** [comment]
Hey @sandeep-t2s just double checked and the `onRowClose` callback runs immediately after the animation begins to close the row. It is possible that the animation is so quick by the time the callback runs the row is already closed, but in my testing I don't see that happening.

At what point in the animation would you expect that callback to run? Maybe I can add another callback at a different point in the code.

Thanks!

**Comment by jemise111** [comment]
Closing as this has been inactive for a while
