### ISSUE TITLE
PropTypes issue with React Native 0.48

### ISSUE THREAD

**Issue by mmaschenko** [jemise111/react-native-swipe-list-view#152]
After i upgraded react native to last version, swipe-list started to crash application because after react changes Proptypes is now can not be imported from react directly. You need install another package as described here https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html. I was able to fix it by changing package files directly, but it is bad idea for a lot of reasons

**Comment by jemise111** [comment]
@mmaschenko This is fixed in the `v0.4.2` release. Sorry for the delay!
