### ISSUE TITLE
Question: how to render the hidden row based on the swipe position?

### ISSUE THREAD

**Issue by grigy** [jemise111/react-native-swipe-list-view#153]
I want to achieve Google Inbox's swipe experience, where the hidden row animates based on the swipe open position. Is this possible with the react-native-swipe-list-view?
<img src="https://media.giphy.com/media/vdQxv9751YX9m/source.gif" alt="Google Inbox" width="300"/>

**Comment by grigy** [comment]
Hi everyone!

I'm trying to add a feature to let the hidden row component know the swipe position. Then I can use that to animate the icon, like the Google Inbox.

So what would be the best way to pass the _translateX value from the SwipeRow to its child component hiddren row?

**Comment by jemise111** [comment]
Hey @grigy this currently isn't supported but could be achieved by passing the value of how much a row has been swiped as it is being opened / closed. Maybe you could pass the value to a callback here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L134

Not sure what kind of impact this would have on performance though...

Give it a shot and I'd be happy to look at a PR, thanks!

**Comment by jemise111** [comment]
@grigy took a while but this is finally supported! See here:

https://github.com/jemise111/react-native-swipe-list-view#ui-based-on-swipe-values-the-gmail-effect

**Comment by grigy** [comment]
Thank you @jemise111. This is great!
