### ISSUE TITLE
How to turn off the sideslip when you click?Ask God for help

### ISSUE THREAD

**Issue by ChenghaoHu** [jemise111/react-native-swipe-list-view#154]

**Comment by cukiy** [comment]
swipeListView component has a function  name is safeCloseOpenRow,  using the ref to call this function

**Comment by jemise111** [comment]
Hey @ChenghaoHu, I'm not sure what your issue is referring to. Could you elaborate a bit and maybe provide some example code? Thanks!

**Comment by ChenghaoHu** [comment]
Such as, The react-native-swipeout component has autoClose functioned. However, I don't know the react-native-swipe-list-view component's autoClose method. I'm just trying to get the autoClose function. To implement this method, you can judge the display effect of each column in the click event. Thank you very much  for your letter and help!  







------------------ 原始邮件 ------------------
发件人: "Jesse Sessler";<notifications@github.com>;
发送时间: 2017年10月23日(星期一) 凌晨2:40
收件人: "jemise111/react-native-swipe-list-view"<react-native-swipe-list-view@noreply.github.com>;
抄送: "HuChengHao"<1742759591@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jemise111/react-native-swipe-list-view] How to turn off thesideslip when you click?Ask God for help (#154)




Hey @ChenghaoHu, I'm not sure what your issue is referring to. Could you elaborate a bit and maybe provide some example code? Thanks!

**Comment by jemise111** [comment]
Hey @ChenghaoHu it sounds like you're trying to close a row on a click event. Here is some sample code that closes the row when you click on one of the hidden buttons:

```
<SwipeListView
    renderHiddenRow={ (data, secId, rowId, rowMap) => (
        <View style={styles.rowBack}>
            <Text>Left</Text>
            <View style={[styles.backRightBtn, styles.backRightBtnLeft]}>
                <Text style={styles.backTextWhite}>Right</Text>
            </View>
            <TouchableOpacity
                style={[styles.backRightBtn, styles.backRightBtnRight]}
                onPress={ _ => rowMap[`${secId}${rowId}`].closeRow() }
            >
                <Text style={styles.backTextWhite}>Delete</Text>
            </TouchableOpacity>
        </View>
    )}
    leftOpenValue={75}
    rightOpenValue={-150}
/>
```

Hope that works for you!

**Comment by ChenghaoHu** [comment]
Thank You very mach!
