### ISSUE TITLE
Direction of opened row lost in onRowOpen

### ISSUE THREAD

**Issue by ronnen** [jemise111/react-native-swipe-list-view#156]
Using the combination of SwipeListView and SwipeRow in its renderRow function, I try to get the direction the row was swiped open.
While SwipeRow::onRowOpen is triggered with 'toValue' as a single param, it is then swallowed by SwipeListView which triggers its onRowOpen callback with param signature (secId, rowId, this._rows) and losing the toValue.
Below is the gist of the component structure and I marked the problematic callbacks.

Could someone assist in getting the toValue either at the SwipeRow or the SwipeListView level? 

Thanks in advance!

```
  render() {
    return (
      <SwipeListView
        ref={'_listView'}
        dataSource={this.state.dataSource}
        renderRow={(row, sectionId, rowId, rowMap) => {
          return (
            <SwipeRow
              onRowOpen={(toValue) => {
                // this method gets overridden in SwipeListView and never get called
                console.log("never gets here")
              }}
            >
              <HiddenRow
                rowId={rowId}
                sectionId={sectionId}
                rowMap={rowMap}
                rowData={row}
              />
              <View>
                <Text>Foreground Row</Text>
              </View>
            </SwipeRow>
          )}
        }
        onRowOpen={(toValue) => {
          console.log("gets here but getting sectionId instead of toValue - from the (sectionId, rowId, rowMap) signature");
        }}
      />
    );
  }

```

**Comment by jemise111** [comment]
Closing as this was taken care of in #228
