### ISSUE TITLE
When I sliding bottom to top ,I have some trouble

### ISSUE THREAD

**Issue by MaiYiHang** [jemise111/react-native-swipe-list-view#166]
hey,first Thank you to your good compoent.I'm a chinese ,and my English is not good,so please forgive me.
I have some trouble,when I sliding bottom to top for get more,it crash.

**Comment by jemise111** [comment]
Hey @MaiYiHang, thanks for the compliment! Could you provide some more info? If you could provide some sample code the reproduces the issue I'd be happy to give it a shot on my end and try and fix it. Thanks!

**Comment by jemise111** [comment]
Closing as this has been inactive for a while
