### ISSUE TITLE
closeRow() 'Out of Memory'

### ISSUE THREAD

**Issue by sabbiu** [jemise111/react-native-swipe-list-view#170]
On debugger mode, everything is working perfectly. 
But, on non-debugger mode, when the following command is encountered, app freezes for a while and 'out of memory error is displayed.
```rowMap[`${secId}${rowId}`].closeRow();```

**Packages**
```
    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-navigation": "^1.1.300",
    "react-native-swipe-list-view": "^0.4.7",
```
**Error**
![Out of Memory Error](https://user-images.githubusercontent.com/19733021/33935897-9dc91ac6-e025-11e7-8af6-698b174b6596.png)

**Comment by sabbiu** [comment]
Turns out there was way more `console.log()` in my project.. :rofl:

**Comment by jemise111** [comment]
Hah glad it's all sorted!

**Comment by OrangeFlavoredColdCoffee** [comment]
i have same problem,what is the solution？
