### ISSUE TITLE
Slow performance and init size not working

### ISSUE THREAD

**Issue by poc7667** [jemise111/react-native-swipe-list-view#171]
As you can see I tried to init 5 items at first.
However, from the debugger console I could also see all the items are rendered which slows down my app performance!

Any idea?

# ListView

    <SwipeListView
        initialListSize={5}
        dataSource={this.ds.cloneWithRows(this.props.words)}
        renderRow={this.renderWord.bind(this)}
        renderHiddenRow={(data, secId, rowId, rowMap) => this.renderDeleteAction(data, secId, rowId, rowMap)}
        disableRightSwipe={false}
        disableLeftSwipe={false}
        leftOpenValue={RIGHT_OPEN_WIDTH}
        rightOpenValue={-RIGHT_OPEN_WIDTH}
    />

# Cell/Item

    render(){
        let startTime = Date.now();
        let detailView = this.computeDetailView()
        console.log(this.props.word);
        console.log(Date.now() - startTime);
        return(
            this.props.showDetail && detailView
        )
    }

# console.log

![inline](https://i.imgur.com/R8jbV5U.png=300x "Title")

**Comment by jemise111** [comment]
Hey @poc7667 I'm not sure I entirely understand your question but let me give it a shot. The `initialListSize` prop is simply passed on to the underlying `ListView` on this line: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L150.

So between a `SwipeListView` and a `ListView` there is absolutely no difference in how `initialListSize` works.

When you say `initialListSize={5}` the component will initially render 5 rows but will then continue to render as it normally does. This does not limit it to ONLY rendering 5 rows.

For example if your data calls for 100 rows and you say `initialListSize={5}`, it will render 5 rows and then immediately render as many as it deems necessary. I was doing some testing and my component rendered ~30 rows. Then as I scrolled the rest of the rows were rendered.

However, if you say `initialListSize={100}`, it will render ALL 100 rows immediately.

Does that make sense? Does that answer your question? Thanks!

**Comment by jemise111** [comment]
Closing as this has been inactive for a while
