### ISSUE TITLE
this._listView.setNativeProps is not the function.

### ISSUE THREAD

**Issue by sandeepjrs** [jemise111/react-native-swipe-list-view#175]
![simulator screen shot - iphone 6 - 2017-12-28 at 15 12 42](https://user-images.githubusercontent.com/14137376/34413511-f89fc2a2-ec09-11e7-8870-4cd9597fb536.png)

**Comment by sandeepjrs** [comment]
created the pull request #176

**Comment by jemise111** [comment]
Hey @sandeepjrs thanks for the PR, will get that merged in and released shortly.

Can I ask what platform / RN version you are using and if you're using FlatList or not?

I haven't run into this issue so I'm curious.

**Comment by sandeep-t2s** [comment]
Thank you @jemise111 for the quick action. I am using the react-native 45 and yea I am using the FlatList.

**Comment by jemise111** [comment]
@sandeep-t2s Hm strange that I never seemed to run into this issue. Last question - iOS or Android?

**Comment by sandeepjrs** [comment]
ha ha :D I don't have any problem in responding to your questions. This library is helping me a lot.

I tried only in iOS.

**Comment by jemise111** [comment]
Closing via #176
