### ISSUE TITLE
Is it possible to use SectionList to achieve swipe row?

### ISSUE THREAD

**Issue by wangdicoder** [jemise111/react-native-swipe-list-view#180]
Hi,

Thanks for providing so much useful component. 

I have a question. How can I use SwipeRow to achieve swipe function in the SectionList? ListView has been deprecated, and also I want to use the section function, so I think SectionList will be better. I tried to render the item as SwipeRow, but I could not figure out automatically closing row when another row is opening, and forbid vertical scroll when a row is swiping.

Cheers,

**Comment by jemise111** [comment]
Hey @wangdicoder it is possible but you'll have to implement a lot of the same functionality that's included in the SwipeListView by default. I hope to getting around to supporting SectionList at some point but I just don't have the time right now. If I were you I would take a look at the source code for `SwipeListView`, in particular the logic in these methods:

`rowSwipeGestureBegan`
`onRowOpen`
`onRowPress`
`onScroll`

I don't think that should be too difficult to reimplement that behavior in your own case

**Comment by wangdicoder** [comment]
@jemise111 Thanks a lot. I try to have a look.
