### ISSUE TITLE
TouchableWithoutFeedback won't work

### ISSUE THREAD

**Issue by Elijen** [jemise111/react-native-swipe-list-view#183]
If TouchableWithoutFeedback is used instead of TouchableOpacity onPress callback is never called.

**Comment by ch3nj** [comment]
Wrap whatever you're putting in there with a View.

**Comment by jemise111** [comment]
Hey @Elijen could you post some code that you're using in your `renderRow` / `renderItem` function? Or a reproducible example I can try on my end? Thanks!

**Comment by Elijen** [comment]
@jemise111, @ch3nj  So apparently the issue is `TouchableWithoutFeedback` itself. See: https://github.com/facebook/react-native/issues/10180#issuecomment-298375648

Thanks for your replies though :)

**Comment by I-O-O-I** [comment]
THIS WORKED https://github.com/facebook/react-native/issues/10180#issuecomment-298375648
