### ISSUE TITLE
Disable scroll while swiping

### ISSUE THREAD

**Issue by Elijen** [jemise111/react-native-swipe-list-view#184]
If you check out a native app that uses a similar swipe list (e.g. iOS Phone.app) it behaves slightly differently when you start swiping (left or right). A native app disables the scrolling so even when you suddenly move your finger down the list stays in the same place.

This makes it MUCH easier to swipe on items since a human thumb naturally moves along an elliptical path rather then straight line.

Current version of SwipeListView doesn't disable the scroll and even closes the SwipeRow on the scroll event.

**Comment by jemise111** [comment]
Hey @Elijen the `SwipeListView` actually does disable scrolling on the parent `ListView` or `FlatList` as soon as it has been detected that a swipe has begun. See here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L120

I also tried to demonstrate this in the gif below. If you're not experiencing that behavior that's a bug. Please let me know which platform you're using and if you had some code that could repro the bug that would be really helpful.

> and even closes the SwipeRow on the scroll event

This is intentional behavior. If you'd like to disable it you can set the `closeOnScroll` prop to `false`.



![](http://g.recordit.co/OV147xsIGP.gif)

**Comment by Elijen** [comment]
@jemise111 Thanks for the reply. 

Seems you are right and it works as expected when FlatList is used in a simple View. It breaks however when used as a child of another ScrollView.

I figured out I'd probably need to disable scrolling myself using `swipeGestureBegan`, but it seems there is no `swipeGestureEnded` to enable the scrolling again.

**Comment by Elijen** [comment]
Perhaps it would be nice if `onScrollEnabled` prop was added. It would be called by `setScrollEnabled` so user can enable/disable scrolling of any nested `ScrollView`.

**Comment by jemise111** [comment]
@Elijen Done! 

Get version v1.0.6 and see here: https://github.com/jemise111/react-native-swipe-list-view#onscrollenabled

Going to close this, please open if you have any other issues.

**Comment by yudongqiu** [comment]
Thanks for the insightful discussions!

Follow up question: For the nested scrolling use case, I tried the `onScrollEnabled` method to disable the scrolling of the parent Flatlist when triggered. However the it causes glichy behavior when swiping. It was also mentioned here: https://stackoverflow.com/questions/73927596/how-can-i-prevent-vertical-scrolling-of-parent-flatlist-when-scrolling-horizonta

Would you mind share if there are better ways to handle this use case?

**Comment by yudongqiu** [comment]
> Thanks for the insightful discussions!
> 
> Follow up question: For the nested scrolling use case, I tried the `onScrollEnabled` method to disable the scrolling of the parent Flatlist when triggered. However the it causes glichy behavior when swiping. It was also mentioned here: https://stackoverflow.com/questions/73927596/how-can-i-prevent-vertical-scrolling-of-parent-flatlist-when-scrolling-horizonta
> 
> Would you mind share if there are better ways to handle this use case?

Found the solution myself, the trick is to not use a state but rather ["Direct Manipulation"](https://reactnative.dev/docs/direct-manipulation) similar to your example [here](https://github.com/jemise111/react-native-swipe-list-view/blob/3c3fa95b0509af71dcf253834e367916ad688d13/components/SwipeListView.js#L48)

**Comment by pitops** [comment]
Just for reference. I had also the issue of the parent further up the tree being a scroll view. The way I solved it was to forward the ref from that parent component and then add the following two props to SwipeListView

```
swipeGestureBegan={() => {
     scrollViewRef.current?.setNativeProps({scrollEnabled: false});
 }}
swipeGestureEnded={() => {
    scrollViewRef.current?.setNativeProps({scrollEnabled: true});
}}
```
