### ISSUE TITLE
Cannot read property 'setNativeProps' of undefined

### ISSUE THREAD

**Issue by sideme** [jemise111/react-native-swipe-list-view#186]
![image](https://user-images.githubusercontent.com/10138628/35611087-cec4fff6-069e-11e8-9a75-fd1c73b93301.png)

**Comment by sideme** [comment]
When I slide this error occurs
When I silde another one,the previous one will not be restored

**Comment by sideme** [comment]
this is how I am using
`<SwipeListView
                useFlatList
                data={this.state.listViewData}
                renderItem={ (data, rowMap) => (
                    <View>
                        <TouchableHighlight>

                        </TouchableHighlight>
                    </View>
                )}
                renderHiddenItem={ (data, rowMap) => (
                    <View>
                        <TouchableOpacity>
                            
                        </TouchableOpacity>
                    </View>
                )}
            />`
Thank you for your help!

**Comment by jemise111** [comment]
Hey @sideme could you tell me:

1. What version of RN are you using?
2. What version of react-native-swipe-list-view are you using?
3. Is this on iOS and Android?

Thanks! This seems to be an issue for multiple people and I can't reproduce so that would be super helpful.

Also make sure you have the latest version of RNSLV. It may partially solve your issue

**Comment by sideme** [comment]
Thank you for your reply
1. My version of RN is 52
2. My version of react-native-swipe-list-view  is 1.0.5
3.I'm using IOS

**Comment by sideme** [comment]
Thank you for your reply

1. My version of RN is 52
2. My version of react-native-swipe-list-view is 1.0.5
3. I'm using IOS

**Comment by jemise111** [comment]
Hey @sideme I've had people reporting various formats of this same issue across different versions.

I've rewritten this small piece of code to be as safe as possible. Please give the latest version a shot (v1.0.6) and let me know if it fixes your problem, thanks!

**Comment by sideme** [comment]
Thank you!
it seems to lead to another question，like this
![image](https://user-images.githubusercontent.com/10138628/35960277-099ebcac-0ce4-11e8-8e05-acc08ffeade8.png)
The previous one is not hidden

**Comment by jemise111** [comment]
@sideme Hm I'm really not sure why that would be happening. Do you have any of the props set that would cause a change to this behavior? such as `closeOnRowBeginSwipe`

**Comment by sideme** [comment]
I'm used the basic features, like this
![image](https://user-images.githubusercontent.com/10138628/36006787-dfce3e8e-0d79-11e8-858f-7313be2aff06.png)
I think using FlatList is the cause of the problem
When I use ListView,The problem will not happen

**Comment by jemise111** [comment]
@sideme sorry man I'm really not sure what's going on. Could you investigate a little further for me?

If you go into your `node_modules/react-native-swipe-list-view/components/SwipeListView.js` and add a `debugger` on line 58 right inside the `onRowOpen` method and maybe you could see what's going on?

Is `safeCloseOpenRow` being called at all? If so is it able to grab a reference to a row?

Any other details would be greatly appreciated, thanks!

**Comment by sideme** [comment]
Thank you!
I read your code and I used other way to achieve 
Now I have solved it
Thank you very much! you are pretty good!

**Comment by jemise111** [comment]
@sideme great! Glad to hear it
