### ISSUE TITLE
TypeError: Undefined is not an object

### ISSUE THREAD

**Issue by andrzey** [jemise111/react-native-swipe-list-view#188]
`TypeError: undefined is not an object (evaluating 'dataSource.rowIdentities')` is the error I get even with the simplest example. Do you have any clue as to why I experience this error?

![screen shot 2018-02-07 at 16 21 13](https://user-images.githubusercontent.com/2391667/35924323-04f28218-0c23-11e8-9592-fc7921b25ea6.png)

**Comment by jemise111** [comment]
Hey @andrzey looks like there's a typo there. You have `useFlaList` instead of `useFlatList`. Therefore it's trying to use a `ListView` and looking for a `datasource` prop that doesn't exist.

Does that do the trick?

**Comment by andrzey** [comment]
Djesus that was embarrasing. Thank you so much!

**Comment by jemise111** [comment]
Hah no problem man. Second pair of eyes always does the trick :)
