### ISSUE TITLE
Add renderFlatList prop

### ISSUE THREAD

**Issue by Paul-Todd** [jemise111/react-native-swipe-list-view#190]
Right now we have a renderListView function which consumes the renderRow function.
If we want to use a flatlist then this consumes the renderItem method. We need to expose the renderItem method in addition to the renderRow function.

I propose adding a renderFlatList property that exposes the renderItem method if the useFlatList property is true.

Comments? If okay I will do a PR on this.

**Comment by jemise111** [comment]
Hey @Paul-Todd sounds good to me, happy to look at a PR

**Comment by jemise111** [comment]
Closing as `FlatList` is now supported
