### ISSUE TITLE
Can not animate hidden item correctly

### ISSUE THREAD

**Issue by olejka91** [jemise111/react-native-swipe-list-view#194]
I have an animated item in my app, it is a red trash can which scales # from 0 to 1 

![123](https://user-images.githubusercontent.com/18009429/37927006-808a302c-3141-11e8-9163-8d8825eb4c9b.png)

When I open any item at first it works as it should be but when I open any next item, previously opened item closed and the animation of scaling down to 0 works on the item I open and then immediately scale up to 1 which is incorrect I think. How to avoid this behavior? How to make each animation to be responsible only for the image in the item, not for all hidden images on the screen?  

### INITIAL  VALUE

>
state = {
  animatedTrashCan: new Animated.Value(0),
};
>

### METHODS
>
  onRowDidOpen = () => {
    Animated.spring(this.state.animatedTrashCan, {
      toValue: 1,
    }).start();
  };

  swipeGestureBegan = () => {
    Animated.spring(this.state.animatedTrashCan, {
      toValue: 0,
    }).start();
  };
>

### WHAT I RENDER

> 
render() {
    const { items, removeHandler } = this.props;
    const animatedImageStyle = {
      transform: [{ scale: this.state.animatedTrashCan }],
    };
    return (
      <SwipeListView
        useFlatList
        closeOnRowPress
        closeOnScroll
        closeOnRowBeginSwipe
        disableRightSwipe
        data={items}
        keyExtractor={this.keyExtractor}
        ItemSeparatorComponent={this.renderSeparator}
        onRowDidOpen={this.onRowDidOpen}
        swipeGestureBegan={this.swipeGestureBegan}
        renderItem={this.renderItem}
        renderHiddenItem={(data, rowMap) => (
          <TouchableOpacity
            style={styles.trashCanContainer}
            onPress={() => removeHandler(data, rowMap)}
          >
            <Animated.Image source={trashCan} style={[styles.trashCan, animatedImageStyle]} />
          </TouchableOpacity>
        )}
        leftOpenValue={70}
        rightOpenValue={-70}
      />
    );
  }
> 

Thanks in advance

**Comment by jemise111** [comment]
Hey @olejka91, so it looks like you're are tying the animation of each trash can to only one animated value. You'll have to use a different animated value for each trash can. To do this you can tie the animated value to the key or the data for the row that the trash can lives in. I've modified your code above and I'm assuming that each piece of data in `data` has a `key` property.

```
constructor() {
  this.animatedValues = {};
  this.props.items.forEach(item => {
    this.animatedValues[item.key] = new Animated.Value(0);
  });
}

onRowDidOpen = (key) => {
  Animated.spring(this.animatedValues[key], {
    toValue: 1,
  }).start();
};

swipeGestureBegan = (key) => {
  Animated.spring(this.animatedValues[key], {
    toValue: 0,
  }).start();
};

render() {
  const { items, removeHandler } = this.props;

  return (
    <SwipeListView
      useFlatList
      closeOnRowPress
      closeOnScroll
      closeOnRowBeginSwipe
      disableRightSwipe
      data={items}
      keyExtractor={this.keyExtractor}
      ItemSeparatorComponent={this.renderSeparator}
      onRowDidOpen={this.onRowDidOpen}
      swipeGestureBegan={this.swipeGestureBegan}
      renderItem={this.renderItem}
      renderHiddenItem={(data, rowMap) => (
        <TouchableOpacity
          style={styles.trashCanContainer}
          onPress={() => removeHandler(data, rowMap)}
        >
          <Animated.Image
            source={trashCan}
            style={[
              styles.trashCan,
              {
                transform: [{ scale: this.animatedValues[data.item.key] }],
              }
            ]}
          />
        </TouchableOpacity>
      )}
      leftOpenValue={70}
      rightOpenValue={-70}
    />
  );
}
```

Take a look and feel free to ask any questions but I think this should be pretty close to achieving what you're going for. Let me know otherwise, thanks!
