### ISSUE TITLE
How to avoid binding when using touchables

### ISSUE THREAD

**Issue by michalpetrov** [jemise111/react-native-swipe-list-view#196]
If I want to use a touchble row (according to the documentation) it must be the topmost component. So I have to use it like this:
```
class ItemsList extends Component {
    renderItem = (data) => {
        return  (
            <TouchableHighlight onPress={this.onItemPress.bind(this, data.item)} >
                ...
            </TouchableHightlight>
        )
    }

    onItemPress = (item) => {
        ... // do something with item
    }
}
```
So I have to call bind for each item to get the pressed item value as a parameter of onItemPress function. But binding like this should be not used because of perfomance issues (especially for large lists).

Normally to avoid such a binding I would use a wrapper child component like this:
```
class ItemComponent extends Component {
    render () {
        <TouchableHighlight onPress={this.onPress} >
            ...//
        </TouchableHightlight>
    }

    onPress = () => {
        this.props.onItemPress(this.props.item)
    }
}

class ItemsList extends Component {
    renderItem = (data) => {
        return  <ItemComponent item={data.item} onItemPress={this.onItemPress}  />
    }

    onItemPress = (item) => {
        ... // do something with item
    }
} 

```
But this way the topmost component isn't a touchable and the swipelist doesnt work.
Any idea how to do this right?

**Comment by jemise111** [comment]
Hey @michalpetrov I don't think you need an entirely new component here. How about this:

```
class MyComponent extends React.Component {

  onItemPress = (item) => () => {
    // Here I have access to item
  }

  render() {
    return (
      <SwipeListView
        useFlatList
        data={this.state.listViewData}
        renderItem={ (data, rowMap) => (
          <TouchableHighlight
            onPress={this.onItemPress(data.item)}
            style={styles.rowFront}
            underlayColor={'#AAA'}  
          >
            <View>
              <Text>I am {data.item.text} in a SwipeListView</Text>
            </View>
          </TouchableHighlight>
        )}
        ...
      />
    );
  }
}
```

**Comment by michalpetrov** [comment]
`onPress={this.onItemPress(data.item)}` 
Like this you are invoking the function during the render. You need to pass a function to `onPress` and not to invoke it.

**Comment by jemise111** [comment]
```
onItemPress = (item) => () => {
```

There's actually another `=>` here so `onItemPress` returns a function which can then be passed to `onPress`. I tested the code above and it works fine. I'm not sure if it's the best practice way to do things but it's how I usually handle this type of scenario when I don't want to explicitly `bind` and haven't seen performance issues as far as I know.

Hope it works for you!

**Comment by michalpetrov** [comment]
Ok, I didn't note the second `=>` ... so, yes, like this it will work. But from performance site it's basically the same as using `bind` because it returns new function at each render, that means the props will change and that would cause another render.

**Comment by jemise111** [comment]
@michalpetrov fair enough. I'm having some trouble seeing how you would achieve what you want using a normal ListView (or FlatList). Could you expand your example above to include that bit? And I'll see if I can make a few changes to get it to work for the SwipeList as well. Thanks!

**Comment by jemise111** [comment]
@michalpetrov just saw this article and thought it might be helpful: https://medium.freecodecamp.org/the-best-way-to-bind-event-handlers-in-react-282db2cf1530

**Comment by jemise111** [comment]
Closing as inactive, please reopen if you still have issues
