### ISSUE TITLE
undefined closeRow() from SwipeListView 

### ISSUE THREAD

**Issue by pisangGoreng** [jemise111/react-native-swipe-list-view#201]
Hi.. im try to implement closeRow() when user click button from renderHiddenItem property.
when im try to access closeRow() from rowMap, its look like undefined. 
im try with onPress={ _ => rowMap[rowData.item.key].closeRow()} 

Any idea to solve this? Thanks

```
      <SwipeListView
        useFlatList
        data={notificationList}
        disableLeftSwipe
        style={{flexGrow: 1, backgroundColor: 'white'}}
        leftOpenValue={55}
        renderItem={(data, rowMap) => this._renderNotificationItem(data.item)}        
        renderHiddenItem={(rowData, rowMap) => (
          <TouchableOpacity onPress={() => {this.readThisNotif(rowData)}} style={styles.swipeButton}>
            <MaterialIcons name={`markunread`} size={28} color={'#fff'} />
          </TouchableOpacity>
        )}
      />
```

**Comment by jemise111** [comment]
@pisangGoreng are you calling `closeRow` from within `readThisNotif`? Because I don't see where you are passing the `rowMap` to `readThisNotif`? 

Also what is `undefined`? The `rowMap` or something in `rowData`? 

It would be super helpful if you could post the code for `readThisNotif` and the redbox error you're seeing as well.

Thanks!

**Comment by jemise111** [comment]
@pisangGoreng Sorry man I'm not sure what's going on.. I've plugged in the code you're using in `renderHiddenItem` into my example and it's working just fine.

Can I see what `notificationList` looks like? That might help figure out the issue.

Thanks!

**Comment by pgonzalez-santiago** [comment]
Same happening to me. rowMap[rowData.item.key] is undefined

**Comment by jemise111** [comment]
@pgonzalez-santiago @pisangGoreng I think my response to another issue may help you here. Have a look at this and see if it solves your problems. If not please let me know:

https://github.com/jemise111/react-native-swipe-list-view/issues/220#issuecomment-398678246

**Comment by jemise111** [comment]
Closing as inactive, please reopen if you still have issues

**Comment by kapilwhaval** [comment]
rowMap[rowData.item.key] gives undefined because there is no any property called "key" in your item object.
You can use rowMap[rowData.item.id] instead as my item object consist of unique "id" in it.
Worked for me.
