### ISSUE TITLE
rowData is undefined on a first event call in hidden items

### ISSUE THREAD

**Issue by ivanushka1703** [jemise111/react-native-swipe-list-view#203]
Here is my setup:

```
{ list && list[0]
    <SwipeListView
      useFlatList
      keyExtractor={(item) => item._id}
      data={list}
      renderItem={({item}) => (
      <View style={style.listItem}>
        {editable && editable._id == item._id
          ? <TextInput
              style={style.editInput}
              value={editable.name}
              onChangeText={value => this.handleChangeText(value, 'editable')}
              onSubmitEditing={this.handleEditItem}
              onBlur={this.handleEditItem}
              autoFocus/>
          : <Text style={style.listItemText}>{item.name}</Text>}
      </View>
    )}
      renderHiddenItem={(data, row) => {
        console.log(row, data);
        return (
      <View style={style.rowBack}>
        <EditButton row={row[data.index]} _id={data.item._id}/>
        <DeleteButton row={row[data.index]} _id={data.item._id}/>
      </View>
    );}}
      rightOpenValue={-200}
      disableRightSwipe
      closeOnRowPress
      closeOnScroll/> }
```

And the EditButton is:

```
const EditButton = ({_id, row}) => {
      console.log('edit', _id, row);
      return (
        <TouchableOpacity onPress={() => this.handleSetEditable(_id, row)}>
          <View
            style={{
            ...style.rowButton,
            width: 200,
            paddingLeft: 120,
            backgroundColor: '#6ba2fc'
          }}>
            <Text style={style.buttonText}>{I18n.t('edit')}</Text>
          </View>
        </TouchableOpacity>
      );
    };
```

When I add a first item to the list, then swipe to open hidden buttons and click EditButton I have `undefined` for `row` in `console.log('edit', _id, row)` of EditButton component.

If I print `row` in `renderHiddenItem` it seems like an empty object, but when I expand it there is a first  row (look at the first console.log):
**collapsed**
![image](https://user-images.githubusercontent.com/23135685/38988862-68c3693c-43dd-11e8-87d7-636dc09af1a6.png)

**expanded**
![image](https://user-images.githubusercontent.com/23135685/38988946-b6fb7248-43dd-11e8-8ed2-4320cb2fc956.png)

On the second click on the same edit button all works as expected.

Am I doing something wrong?

**Comment by jemise111** [comment]
Hey @ivanushka1703 I think there's a timing issue going on here but I'm not entirely sure.

At the exact moment the row is rendered I would expect the `rows` map to be undefined. The reason for this is I build the `rows` object as each is row is being rendered. So at the exact moment of rendering it will most likely be `undefined`. However any moment after that (including when you click on any hidden buttons) there should be a `rows` object and you should be able to get a reference to your row. So for example if you change this line:

```
console.log('edit', _id, row);
```
to
```
setTimeout(() => {
  console.log('edit', _id, row);
}, 100);
```

My guess is it would be defined.

Does that make sense?

Is this an issue for you? Do you need to get a reference to the row when you are rendering it, or are you okay only having a reference to the row when the button is clicked?

Thanks!

**Comment by jemise111** [comment]
Closing as inactive, please re open if you're still having issues, thanks!
