### ISSUE TITLE
getScrollResponder() isn't available.

### ISSUE THREAD

**Issue by hkung77** [jemise111/react-native-swipe-list-view#206]
I'm using nested swipelistviews (flatlist), the app crashes when i try to swipe on the inner swipe row.

Error:
Cannot read property 'setNativeProps' of undefined
Unhandled JS Exception: Cannot read property 'setNativeProps' of undefined

I looked into the swipelist, it seems like getScrollResponder() is not available function, however the flatlist ref is still available..

**Comment by fukemy** [comment]
how did u fixed this?
