### ISSUE TITLE
Undefined is not an object (Version 1.3.0)

### ISSUE THREAD

**Issue by nzrin** [jemise111/react-native-swipe-list-view#209]
I've got this error while try to trigger closeRow function : 

undefined is not an object (evaluating 'rowMap[rowKey].closeRow')

I'm using FlatList option. This is my closeRow function code: 
```
closeRow(rowMap, rowKey) {
  rowMap[rowKey].closeRow();
}
```

This is my trigger touch code : 
```
<TouchableOpacity onPress={ _ => this.closeRow(rowMap, rowData.item.id) }>
```

This is SwipeListView (FlatList). When I swipe spesific row, another row I've swiped not closing automatically. 

![aaaa](https://user-images.githubusercontent.com/36392666/40304097-f1b0fd32-5d27-11e8-806b-552698e13f6c.png)

Please help.

**Comment by jemise111** [comment]
Hey @nzrin can I see the structure of your data and how you're using the <SwipeListView>. I'm curious to know if each object in your data has a `key` property or if you're passing a `keyExtractor` prop, thanks!

**Comment by nzrin** [comment]
Yes sure, this is my structure of data :  

```
{
    "data": [
        {
            "id": 3,
            "name": "Daging Burger",
            "quantity": 80
        },
        {
            "id": 5,
            "name": "Sos",
            "quantity": 21
        },
        {
            "id": 6,
            "name": "Lada Hitam",
            "quantity": 14
        },
        {
            "id": 7,
            "name": "Mayonis",
            "quantity": 46
        },
        {
            "id": 27,
            "name": "Cheesy",
            "quantity": 6
        },
        {
            "id": 81,
            "name": "Kokpu",
            "quantity": 10
        }
    ]
}
```

**Comment by jemise111** [comment]
Can you try adding a `key` to your data, so it looks like 

```
"data": [
        {
            "key": 3,
            "id": 3,
            "name": "Daging Burger",
            "quantity": 80
        },
...
```

or using a key extractor prop:

```
<SwipeLisView
   keyExtractor={(item, index) => item.id}
   ...
/>
```

and seeing if that fixes it?

**Comment by nzrin** [comment]
Thank you! It works fine when I use keyExtractor.

**Comment by jemise111** [comment]
👍 glad to hear it
