### ISSUE TITLE
React-native-swipe-list-view can support pull-up to load more data and pull-down to refresh the page

### ISSUE THREAD

**Issue by suwu150** [jemise111/react-native-swipe-list-view#212]
Can react-native-swipe-list-view support pull-ups to load more data and drop-down refresh pages, or how should I implement it, taking 10 data at a time

**Comment by jemise111** [comment]
Hey @suwu150 the `<SwipeListView>` component is just a `<FlatList>` (or a `<ListView>`) under the hood so you can follow any of the guides on how to implement pull to refresh for those components and it will work here, thanks!

Here's a guide e.g. https://dev-blog.apollodata.com/loading-data-into-react-natives-flatlist-9646fa9a199b
