### ISSUE TITLE
TouchableOpacity component can see the hidden button

### ISSUE THREAD

**Issue by suwu150** [jemise111/react-native-swipe-list-view#213]
![image-touchopcy](https://github.com/suwu150/static-resource/blob/master/images/react-native-swip-touchopcy.gif?raw=true)
When I use the TouchableOpacity component, I can see the back button when I click on the row. Can I remove the back button or hide it when I click, and make it unnecessary to display or modify the style? thank you！
my renderRow code 
```
  _renderRow = ({ item }) => {
    return (
      <TouchableOpacity
        onPress={() => this._onRowPress({ item })}
      >
        <View
          style={{ padding: 15, marginVertical: 5, backgroundColor: 'white', }}
        >
          <Text>{ 'row data'}</Text>
        </View>
      </TouchableOpacity>
    );
  };
```
style css code 
```
  backRightBtn: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 75
  },
  backRightBtnLeft: {
    backgroundColor: 'blue',
    right: 80
  },
  backRightBtnRight: {
    backgroundColor: 'red',
    right: 0
  },
```

**Comment by jemise111** [comment]
Hey @suwu150 this is a long standing issue without a real solution because it's just two `<View />`s stacked on top of each other.

Either use `activeOpacity={1}` or use a `TouchableHighlight` instead of a `TouchableOpacity`.

If you really wanted to use a `TouchableOpacity` your could try to set the style to change using the `onRowOpened` prop but my guess is you would see some flickering and IMO it's just not worth the trouble. I'd use a `TouchableHighlight` instead. Hope that helps!

**Comment by suwu150** [comment]
Thank you very much for your explanation, I finally decided to use TouchableHighlight, the effect is also OK, as shown below
![hign](https://github.com/suwu150/static-resource/blob/master/images/react-native-swip-touchhign.gif?raw=true)
```
  _renderRow = ({ item }) => {
    return (
      <TouchableHighlight
        onPress={() => this._onRowPress({ item })}
        activeOpacity={0.5}
        // style={{ borderColor: 'red', borderBottomWidth: 2 }}
        underlayColor={styleDict.colorSet.mainColor}
        style={{ padding: 15, marginVertical: 5, backgroundColor: 'white', }}
      >
        <View>
          <Text>{ 'row data'}</Text>
        </View>
      </TouchableHighlight>
    );
  };
```

**Comment by jeanmaried** [comment]
TouchableHighlight with  `activeOpacity={1}` would make you lose the TouchableOpacity animation so I wrapped a View around my component in renderItem and gave it the same background as my screen's  background like so:

    renderItem = () => (
        <View style={{  backgroundColor: ScreenBackgroundColor}}>
            <TouchableOpacity>
                <Item />
            </TouchableOpacity>
        </View>
    )

This prevents both buttons from appearing when you click on the TouchableOpacity and then when you slide they come out from under the sides it as expected.

**Comment by gtaylor44** [comment]
Have also faced the same issue.

TouchableOpacity by default uses opacity of 0.2

Based on this... Another possible workaround:

onCellPressed = () => {
    this.setState({cellPressed: true});

    setTimeout(() => {
      NavigationService.navigate(...);
      this.setState({cellPressed: false});
    }, 100);
}

<TouchableWithoutFeedback onPress={this.onCellPressed}>
<View style={{opacity: this.state.cellPressed ? 0.2 : 1.0}}>
...
</View>
</TouchableWithoutFeedback>

Keep in mind that you also need to hide/show buttons based on state of cellPressed.
