### ISSUE TITLE
previewFirstRow vs previewRowKey

### ISSUE THREAD

**Issue by nzrin** [jemise111/react-native-swipe-list-view#214]
Is there a way to use previewFirstRow instead previewRowKey?

Reason: 
Value inside my keep keep on changing. For example, it doesn't always hold the value of '0', might be random number. How to preview first row without using previewRowKey?

I got an error when I tried to use this code : 
```
previewRowKey={this.state.fetchedData[0].id}
```
Error : 
```
TypError: undefined is not and object 
(evaluating 'this.state.fetchedData[0].id')
```

Thank you.

**Comment by jemise111** [comment]
Hey @nzrin I don't think this is an issue with SwipeListView. It looks like `this.state.fetchedData` is undefined at some point. What if you just did something like:

```
let previewRowKey;
if (this.state.fetchedData && this.state.fetchedData[0]) {
  previewRowKey = this.state.fetchedData[0].id;
}
```

something like that...

**Comment by nzrin** [comment]
Thank you!
