### ISSUE TITLE
Setting the background color does not work

### ISSUE THREAD

**Issue by suwu150** [jemise111/react-native-swipe-list-view#215]
Setting the background color does not work，I set the background color, and when I first entered the list page, I could see it flicker, and it became like this in the picture below.
```
style={{ backgroundColor: 'red' }}
```
![beijingse](https://github.com/suwu150/static-resource/blob/master/images/react-native-swip-backgrouncolor.png?raw=true),

**Comment by jemise111** [comment]
Hi @suwu150 I'm pretty sure there are no issues with setting style on the SwipeListView. Here is the example using FlatList from `example.js` with the `style` prop added...

![image](https://user-images.githubusercontent.com/4265163/40460134-949ef6a8-5f48-11e8-9a47-1400abde203f.png)

**Comment by suwu150** [comment]
hi，But I do have this kind of problem here. I will give you specific code and I hope we can find out the specific reasons for the problem. Thank you.
```
      <SwipeListView
        style={{ backgroundColor: 'red' }}
        useFlatList
        {...this.props}
        data={dataList}
        extraData={this.state}
        renderItem={(rowData, rowMap) => this._renderRow({ rowData, rowMap })}
        renderHiddenItem={this._renderHiddenItem}
        // onRowOpen={(rowKey, rowMap) => {
        // 打开后在一定的时间内关闭
        //   setTimeout(() => {
        //     rowMap[rowKey].closeRow();
        //   }, 5000);
        // }}
        keyExtractor={(item, index) => index.toString()}
      />
```
And, my environment library version is as follows
```
"react": "^16.0.0",
"react-native": "^0.51.0",
"react-native-swipe-list-view": "^1.3.0",
```

**Comment by jemise111** [comment]
`{...this.props}`

Is it possible the parent is passing in a `style` prop that is overriding your style?

**Comment by jemise111** [comment]
Can I also see what `_renderRow` and `_renderHiddenItem` look like?

**Comment by suwu150** [comment]
![backgroundcolorok](https://github.com/suwu150/static-resource/blob/master/images/react-native-swip-backgroundColor-ok.gif?raw=true)

I found the reason because of the style in example.js.Because the background color in the rowBack style is not transparent, as follows
```
	rowBack: {
		alignItems: 'center',
		backgroundColor: '#DDD',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingLeft: 15,
	},
```
The background color I modified to the following,it can display normally.
```
  rowBack: {
    alignItems: 'center',
    // backgroundColor: '#DDD',
    backgroundColor: 'transparent',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 15,
  },
```
I have changed this way and can use it. I do not know if it will affect the project.
And here's my hidden button set
```
  _renderHiddenItem = ({ rowData, rowMap }) => {
    return (
      <View style={styles.rowBack}>
        <Text>Left</Text>
        <View style={{ flex: 1, height: 112 }}>
          <TouchableOpacity
            style={[styles.backRightBtn, styles.backRightBtnLeft]}
            onPress={() => this._distribute({ rowMap, key: rowData.item.key, rowData })}
          >
            <Text style={styles.backTextWhite}>分配</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.backRightBtn, styles.backRightBtnRight]}
            onPress={() => this._delete({ rowMap, key: rowData.item.key, rowData })}
          >
            <Text style={styles.backTextWhite}>删除</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  };
```

**Comment by jemise111** [comment]
Changing the example won't affect the project at all. So I'm a little confused - is your issue resolved?

**Comment by suwu150** [comment]
It has been solved, because the style of roback is directly used in example.js. The background color of _renderHiddenItem blocks the background color of the bottom layer. When I change the color of the layer carrying the bottom button to transparent , list can see the bottom of the style

**Comment by suwu150** [comment]
Can I see the style of rowBack in your `<View style={styles.rowBack}>`? Since we are the same, how can I not show before?

**Comment by suwu150** [comment]
I suggest the rowBack this style, the default background color is transparent

**Comment by jemise111** [comment]
Closing as inactive and solved
