### ISSUE TITLE
Only one opened tab, close previous when next tab open

### ISSUE THREAD

**Issue by vetrslav** [jemise111/react-native-swipe-list-view#218]
Hi!

What i need is to close previous opened tab whet next tab open.
I need only one active tab, is it possible?
I've tried **closeOnRowBeginSwipe** , but it seems doesn't work at all, i don't see any changes.

**Comment by vetrslav** [comment]
![image](https://user-images.githubusercontent.com/20933356/40604398-9377316a-6267-11e8-86ac-d6c011c9b4cf.png)

**Comment by jemise111** [comment]
Hey @vetrslav this should be happening by default. Make sure each object in `this.props.data` has a `key` property. Or make sure you're passing a `keyExtractor` function, otherwise that behavior won't work.

If you like I can take a look at what `this.props.data` looks like

**Comment by vetrslav** [comment]
Yep. The problem was solved by adding keyExtractor 

Thanx
