### ISSUE TITLE
I want to Click this row and right button show auto with no swip,how can I get it

### ISSUE THREAD

**Issue by jdl7758258** [jemise111/react-native-swipe-list-view#220]

**Comment by orarr** [comment]
I am trying to implement this feature with `renderItem` using v1.3.0
```       
       <SwipeListView
          swipeToOpenPercent={5}
          keyExtractor={(t, i) => `t${i}` }
          rightOpenValue={-120}
          useFlatList
          data={listData}
          renderItem={ (data, rowMap) => (
            <TouchableOpacity onPress={_=> rowMap[`t${data.index}`].openRow()} >
              <View style={{flex: 1, height: 40, backgroundColor: '#fdd'}}>
                <Text>I am in a SwipeListView</Text>
              </View>
            </TouchableOpacity>
         )}
      ...more
      />
```
But it seems `rowMap` object is not populated with refs on render. I can access refs only from `onRowOpen`

`rowMap['t1'] is undefined`

**Comment by jemise111** [comment]
Hey @jdl7758258, @orarr, the problem is like you said refs aren't populated until after the component renders. Also there is no method called `openRow` on a SwipeRow so I think it'll work if you change the above code to the following:

```
onRowPress(rowMap, rowKey) {
  if (rowMap[rowKey]) {
    rowMap[rowKey].manuallySwipeRow(-75);
  }
}

render() {
  return (
    <SwipeListView
      ...
      renderItem={ (data, rowMap) => (
        <TouchableOpacity
          onPress={ _ => this.onRowPress(rowMap, data.item.key) }
        >
          <View style={{flex: 1, height: 40, backgroundColor: '#fdd'}}>
            <Text>I am in a SwipeListView</Text>
          </View>
        </TouchableOpacity>
      )}
      ...
    />
  );
}
```

And you can change `data.item.key` to however your keys are calculated.

Give that a shot and let me know if you're still having problems, thanks!

**Comment by jemise111** [comment]
Closing as inactive, please reopen if you still have issues

**Comment by kuangyliang** [comment]
When I use the TextInput component, when I click Close, it will trigger the focus. What should I do?
