### ISSUE TITLE
OnRowOpen direction swipe opened

### ISSUE THREAD

**Issue by novose** [jemise111/react-native-swipe-list-view#225]
Hello,

I read that it's possible to get the direction from where the swipe is opened but i can't get how to use it. I tried with "translateX" and "toValue" which are both undefined for me, I just can't get it how to use it in the right way. I would like to use it to know in which side the swipe is opened! 

Thanks

**Comment by jemise111** [comment]
@novose good call, this was definitely a bug. This should be fixed in v1.3.1.

I've added `toValue` as the 3rd param in the `onRowOpen` and `onRowDidOpen` props. Let me know if you have any other problems, thanks!
