### ISSUE TITLE
Disable horizontal bouncing?

### ISSUE THREAD

**Issue by mmckinley8** [jemise111/react-native-swipe-list-view#227]
Is there a way to disable swiping past the left/right open value to disallow any white space from appearing? Currently I am able to continue swiping the entire row while my open value is only 75.

**Comment by jemise111** [comment]
Hey @mmckinley8, `stopLeftSwipe` and `stopRightSwipe` props should do the trick for you

**Comment by jemise111** [comment]
Closing as inactive, please reopen if you still have issues
