### ISSUE TITLE
Add swipeToClosePercent prop

### ISSUE THREAD

**Issue by Elijen** [jemise111/react-native-swipe-list-view#229]
Would be nice to add `swipeToClosePercent` prop that would work the same as `swipeToOpenPercent` just for closing. By default it should perhaps use the value from `swipeToOpenPercent` (a minor BC break).

**Comment by jemise111** [comment]
Hey @Elijen apologies for the late response. `swipeToClosePercent` is actually already a prop! Somehow it was removed from the Readme but I just added it back here: https://github.com/jemise111/react-native-swipe-list-view#swipetoclosepercent
