### ISSUE TITLE
How to openRow dynamically ?

### ISSUE THREAD

**Issue by PriyankaAshu** [jemise111/react-native-swipe-list-view#231]
How to achieve that, I want show (or openRow)-> row's right side existed trash icon. This must be happens by outside function not manually.

**Comment by jemise111** [comment]
Hey @PriyankaAshu you just need to grab a reference to the row and then call `manuallySwipeRow` on that ref. Here's an example of opening a row when I button is pressed on the row:

```
onRowPress(rowMap, rowKey) {
  if (rowMap[rowKey]) {
    rowMap[rowKey].manuallySwipeRow(-75);
  }
}

render() {
  return (
    <SwipeListView
      ...
      renderItem={ (data, rowMap) => (
        <TouchableOpacity
          onPress={ _ => this.onRowPress(rowMap, data.item.key) }
        >
          <View style={{flex: 1, height: 40, backgroundColor: '#fdd'}}>
            <Text>I am in a SwipeListView</Text>
          </View>
        </TouchableOpacity>
      )}
      ...
    />
  );
}
```

I'm going to close this but please reopen if you have any issues, thanks!

**Comment by sturmenta** [comment]
This was happening to me: https://drive.google.com/open?id=1yTkYn0SCeS5RDi1DEUBrDFLMAv4CaNaD

but I got to fix it using: 

```javascript
_onDeleteItem = ( itemId, data, rowMap ) => {
	if ( rowMap[ data.index ] ) rowMap[ data.index ].manuallySwipeRow( 0 );
	this.props.onDelete( itemId );
}

<SwipeListView
	renderHiddenItem={( data, rowMap ) => (
		<TouchableOpacity
			onPress={() => this._onDeleteItem( data.item.id, data, rowMap )}
		>
			{children}
		</TouchableOpacity>
	)}
	{...props}
/>
```

**Comment by ashok-sl** [comment]
@jemise111 
How Can I swipe the row left/right dynamically without touching/clicking on the row?
The button is outside the rows. I want all rows to swipe left/right by clicking the button.

**Comment by jemise111** [comment]
Hi @ashok-sl please see the discussion here: https://github.com/jemise111/react-native-swipe-list-view/issues/486
