### ISSUE TITLE
hiddenRow flashing on screen change

### ISSUE THREAD

**Issue by bohdan145** [jemise111/react-native-swipe-list-view#232]
I can see the red hidden region in seconds every time i switch to that scene,then it disapper
I'm using react-native-router-flux for navigation.
I've tried setting **recalculateHiddenLayout** but it doesn't help 
I know this issue is the same as  #182 
But i don't use react-navigation

**Comment by aoarashi1988** [comment]
have a try of 
`previewOpenValue={.01}`

**Comment by vishalenrique** [comment]
`previewOpenValue={.01}` doesn't work, anything else?

**Comment by canhtran10** [comment]
Hi guys, Have you anything solution for this? I having same problem. hjccc

**Comment by taixw2** [comment]
+1

**Comment by MichaelKovich** [comment]
It's a bit of a hacky workaround but you can set a value on state, update it onRowOpen and onRowClose, and use that value to change the opacity of the view that contains the red region.

**Comment by nferrara100** [comment]
I had this problem, but realized it was because I had my front row in a TouchableOpacity. By default, that reduces the opacity on touch so I could see the background briefly. Putting it inside a view with the background color set to white fixed the issue:

```javascript
<SwipeRow leftOpenValue={75} rightOpenValue={-75}>
    <View style={styles.swipedRow}>
        <Text style={styles.swipeText}>Left</Text>
        <Text style={styles.swipeText}>Right</Text>
    </View>
    <View style={{backgroundColor: "white"}}>
        <TouchableOpacity>Front row</TouchableOpacity>
    </View>
</SwipeRow>;
```

**Comment by jemise111** [comment]
Closing as it sounds like @nferrara100 has identified the issue and a fix, thanks!

**Comment by alexvazquez** [comment]
> I had this problem, but realized it was because I had my front row in a TouchableOpacity. By default, that reduces the opacity on touch so I could see the background briefly. Putting it inside a view with the background color set to white fixed the issue:
> 
> ```js
> <SwipeRow leftOpenValue={75} rightOpenValue={-75}>
>     <View style={styles.swipedRow}>
>         <Text style={styles.swipeText}>Left</Text>
>         <Text style={styles.swipeText}>Right</Text>
>     </View>
>     <View style={{backgroundColor: "white"}}>
>         <TouchableOpacity>Front row</TouchableOpacity>
>     </View>
> </SwipeRow>;
> ```

Thanks a lot that fix my same issue!
