### ISSUE TITLE
Hidden Row sometimes not there

### ISSUE THREAD

**Issue by KeithM23** [jemise111/react-native-swipe-list-view#233]
I have a strange issue where the hidden row does not appear sometimes, it tends to happen more so on an actual device (it happens most on an iPhone X) rather than the simulator but I haven't been able to find a way to consistently reproduce the issue.

I've toggled the inspector a few times when it happens and can see the row is not there, i.e. it's not that it's invisible it's just not there.

There are a few things I'm doing that aren't standard that may be causing this:

- I'm using SwipeRow inside [sortable list](https://github.com/gitim/react-native-sortable-list) not swipe list view

- I'm setting the data from a network call, however, I only render the list when the network call has returned. i.e. I have if(loading){ return null; ) check before return <SortableList...

- I have the SwipeRow inside an Animated.View so I can scale it on long press (for drag n drop)

- I have a timer to set renderPreview to false (I change the data/order which would trigger the preview if I wasn't doing this, although there may be a better way).

I've tried removing each of these one by one but as the glitch is so random I can never confirm whether it's gone or not.

Unfortunately I can't share the actual code for this as it is a private repo but do any of the above look like they would cause strange issues with the hidden row?

**Comment by jemise111** [comment]
Hi @KeithM23 sorry for the delayed response. So people have reported a few issues using SwipeRows inside of other listview packages (like sortable list) however no one has found consistent problems or repos so I'm at a bit of a loss as well.

My first suggestion would be to try and set `recalculateHiddenLayout={true}` on your swipe rows. This is a performance enhancement but can have unintended consequences and you may be running into one of them. 

You could try isolating the problem (removing the Animated.View wrapper, removing the sortable list entirely, etc).

Off the top of my head I can't think of why your list of implementation details would be causing any issues but if you could come up with an isolated, reproducible, example (outside of your private repo) I'd love to see some code.

Thanks and sorry I don't have a better answer for you right now!

**Comment by KeithM23** [comment]
Hi @jemise111 , thanks for the response.

I actually forgot to update this saying I think I may have solved it. 

I had my list that renders the swipeRow in a screen that's shown as a modal (comes up from bottom) and I believe that if the network call that returned my items returned before this animation finished, then the swipe row would have issues with rendering the hidden rows. This would explain the randomness of the bug.

So the simple fix was to kick off the network call after the modal animation had finished. Since doing this we haven't spotted an issue in almost 2 months now.

**Comment by jemise111** [comment]
@KeithM23 excellent! Glad to hear
