### ISSUE TITLE
I can run Demo 

### ISSUE THREAD

**Issue by icastillejogomez** [jemise111/react-native-swipe-list-view#236]
When I execute `react-native run-ios` I get that error:

![image](https://user-images.githubusercontent.com/16567802/45496760-7b73a300-b776-11e8-91dd-fe23ca7bc4e3.png)

Somebody know what happens?

**Comment by jemise111** [comment]
@icastillejogomez I've updated the example project to RN 57.5 and just tested this, it's working now. Sorry about that! Thanks
