### ISSUE TITLE
closeOnRowPress don't be called when using TouchableHighlight

### ISSUE THREAD

**Issue by lucasfjportela** [jemise111/react-native-swipe-list-view#237]
Hi!

I'm having a problem with SwipeRow component. Inside the visible view I'm calling a TouchableHighlight component and when it's pressed so navigate to another screen and when I navigate back the row **didn't close**. How to call closeRow method from SwipeRow when the TouchableHighlight is pressed?

**Comment by lucasfjportela** [comment]
I did resolve my problem just creating a ref of SwipeRow component and calling it from TouchableHighlight, like this:

`ref={(SwipeRow) => { this.refSwipeRow = SwipeRow }}`  on SwipeRow tag, and adding:

`this.refSwipeRow.closeRow()` on TouchableHighlight onPress method.

Thanks!

**Comment by MikeMajara** [comment]
Hi @lucasfjportela , I am having the same problem, tried the same as you. But no luck. Could you share a bit more code? I your TouchableOpacity the very first levels? Is there one or several TouchableOpacities?

**Comment by JManuelMT** [comment]
It seems this is not working anymore, closeRow() doesn't exist in the ref

**Comment by MikeMajara** [comment]
> It seems this is not working anymore, closeRow() doesn't exist in the ref

The solution back then was to store the references on time of creation (for example on an array). I could search for some code to illustrate how I managed to make it work, but in the end I left this library and went on to [React Native Gesture Handler](https://kmagiera.github.io/react-native-gesture-handler/) which has a [Swipeable](https://kmagiera.github.io/react-native-gesture-handler/docs/component-swipeable.html) component. So my advice is check out that and [reanimated](https://github.com/kmagiera/react-native-reanimated).
