### ISSUE TITLE
When using FlatList with a SwipeRow, previewRowKey prop does not function

### ISSUE THREAD

**Issue by mjfiandaca** [jemise111/react-native-swipe-list-view#238]
Formerly, I was using a swipelistview with useFlatlist, but using the prop renderHiddenItem to define the hidden row.  However, I needed to modify this to a SwipeRow, so that I could disable specific rows within the flatlist from being 'swipeable' .  In reworking the code, I noticed that the previewRowKey now does not function - it should be noted that I do have circumstances where the 0th item in the flatlist may not be swipeable.  But if it is swipeable, I want to show the preview.

Does swiperow accommodate the preview, or is that only in use with the renderhiddenitem functionality? Thank you.

            <SwipeListView
              useFlatList={true}
              data={this.props.messages}
              keyExtractor={(item: any, index: number) => item.id}
              renderItem={(data: any, rowMap: any) => {
                const { item } = data;
                return (
                  <SwipeRow
                    leftOpenValue={75}
                    rightOpenValue={-75}
                    disableRightSwipe={true}
                    disableLeftSwipe={!item.isRead ? true : false}
                  >
                    <TouchableOpacity
                      style={[
                        styles.swipeableHiddenRightBtn,
                        styles.swipeableHiddenMarkUnreadBtn
                      ]}
                      onPress={() => {
                        this.markUnread(item);
                        rowMap[data.item.id].closeRow();
                      }}
                    >
                      <CustomIcon
                        name='mail-unread'
                        style={{ color: 'white', fontSize: 32 }}
                      />
                      <Text style={styles.swipeableHiddenBtnText}>Unread</Text>
                    </TouchableOpacity>
                    <TouchableHighlight
                      underlayColor='white'
                      activeOpacity={0.2}
                      style={styles.swipeableFrontRow}
                      onPress={() => {
                        this.props.SelectMessage(item, true);
                        this.props.SelectPatient(AppPatients[item.account]);
                        navigation.navigate(
                          NavigationRoutes.MessageDetailController,
                          { back: NavigationRoutes.MessageSummaryController }
                        );
                      }}
                    >
                      <Card
                        priority={item.isPriority}
                        sender={item.sender}
                        subject={item.subject}
                        patient={AppPatients[item.account].lastNameFirstName}
                        message={item.content ? item.content : ''}
                        time={item.time}
                        status={item.status}
                        isRead={item.isRead}
                      />
                    </TouchableHighlight>
                  </SwipeRow>
                );
              }}
              previewRowKey={
                this.props.messages[0] ? this.props.messages[0].id : ''
              }
            />
          )}
        </View>

**Comment by jemise111** [comment]
Hey @mjfiandaca if you're going to use your own custom `<SwipeRow />` the `previewRowKey` will no longer work because you can just use the preview props directly on the SwipeRow itself. See the docs for them here: https://github.com/jemise111/react-native-swipe-list-view#preview

So I think your code will look something like:

```
<SwipeListView
  useFlatList={true}
  data={this.props.messages}
  keyExtractor={(item: any, index: number) => item.id}
  renderItem={(data: any, rowMap: any) => {
  const { item } = data;
  return (
    <SwipeRow
      leftOpenValue={75}
      rightOpenValue={-75}
      disableRightSwipe={true}
      disableLeftSwipe={!item.isRead ? true : false}
      preview={this.props.messages[0] && item.id === this.props.messages[0].id}
    >
```

Something like that... does that make sense?

**Comment by mjfiandaca** [comment]
That totally works.  I guess I should have read the entire readme - however, perhaps the readme can be updated in the section regarding Per row behavior:
If you need rows to behave independently you can return a <SwipeRow> in the renderItem function. Make sure you import the <SwipeRow> in addition to the <SwipeListView>. See the example below and the docs under API for how to implement a custom <SwipeRow>. There is also a full example in example.js.

Below it, props are listed for the per row behavior - whereas I was reading this as all props which can be passed to a swiperow.  Sometimes developers don't read the entire readme...my bad, and thank you.

**Comment by jemise111** [comment]
@mjfiandaca Glad it worked! PR's always welcome on that Readme change :)
