### ISSUE TITLE
Hard open right row..

### ISSUE THREAD

**Issue by ldhios** [jemise111/react-native-swipe-list-view#241]
- react-native-swipe-list-view Version: 1.3.1

- react-native version: 0.44.3

 Sometimes it's very hard to open right row。Can you help me？

![image](https://user-images.githubusercontent.com/9722423/47083059-2679ef80-d242-11e8-9ed1-999b3bf5fd0d.png)

![image](https://user-images.githubusercontent.com/9722423/47083076-32fe4800-d242-11e8-86b3-7c988800c59e.png)

**Comment by jemise111** [comment]
Closing as inactive
