### ISSUE TITLE
Is there a callback to know when the swipe open value has been reached?

### ISSUE THREAD

**Issue by scottmcpherson** [jemise111/react-native-swipe-list-view#245]
Is there a way to figure out if the swipe distance is past the open value?

I need to be able to listen to the x swipe distance in real time as the user is swiping.

**Comment by scottmcpherson** [comment]
I'm looking through the code and not seeing anything like that. Maybe we could add an `onSwipeValueChange` function? 

It could return something like:
```
{
    value: x,
    isOpen: <bool>
}
```

**Comment by jemise111** [comment]
@scottmcpherson Love the idea, thanks for the suggestion!

`onSwipeValueChange` has been added as of v1.5.0, it behaves exactly as you described. See an example here:

https://github.com/jemise111/react-native-swipe-list-view#ui-based-on-swipe-values-the-gmail-effect

Closing this, please reopen if you have issues using it, thanks!

**Comment by jemise111** [comment]
Fixed in #252
