### ISSUE TITLE
it can not add refreshController?thanks

### ISSUE THREAD

**Issue by YufengHu123** [jemise111/react-native-swipe-list-view#246]
it can not add refreshController, thanks,can u add it

**Comment by jemise111** [comment]
Hey @YufengHu123 The SwipeListView is just a ListView (or FlatList, or SectionList) under the hood so you can use it the same way. Adding a refresh control is just as it is in the docs:

https://facebook.github.io/react-native/docs/refreshcontrol#usage-example

Thanks!
