### ISSUE TITLE
"Cannot read property 'props' of undefined".

### ISSUE THREAD

**Issue by lcrabbit** [jemise111/react-native-swipe-list-view#247]
I was trying to use the lib, but I can't even access the screen when I add it to it.

That's my import: `import { SwipeRow } from 'react-native-swipe-list-view';`

`                <SwipeRow
                    leftOpenValue={75}
                    rightOpenValue={-75}
                >
                    <Text>Test.</Text>
                </SwipeRow>`

And this is what I was trying to do. I've tried a lot of properties but nothing has change (besides the error's line number, lol).
![image](https://user-images.githubusercontent.com/28108272/48350625-f837d600-e66e-11e8-8a99-2c8624e26373.png)

What can I do? I've also tried inside a blank screen inside the same project, and I get the same error.

**Comment by jemise111** [comment]
Hey @lcrabbit looks like you're not quite using the SwipeRow correctly. In addition to the first child passed (`<Text>Test</Text>`) you need to pass a send child as the hidden component. See the example here for how to use a standalone SwipeRow

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L64

Please reopen if that doesn't work for you, thanks
