### ISSUE TITLE
SwipeRow doesn't update anymore in 1.4.0

### ISSUE THREAD

**Issue by yoyohko** [jemise111/react-native-swipe-list-view#250]
This bug was introduced in https://github.com/jemise111/react-native-swipe-list-view/pull/235

shouldItemUpdate prop should be optional, but it actually is mandatory.

shouldComponentUpdate method of SwipeRow class should return true when shouldItemUpdate prop is null.

**Comment by jemise111** [comment]
@yoyohko Thanks for the catch! Fixed here: #251 and released in v1.4.1

**Comment by yoyohko** [comment]
Well, it sure is fixed because now shouldComponentUpdate always returns true :slightly_smiling_face:

You wrote this.props.shouldComponentUpdate instead of this.props.shouldItemUpdate

Thanks
