### ISSUE TITLE
Turn Preview Off

### ISSUE THREAD

**Issue by lightninglu10** [jemise111/react-native-swipe-list-view#255]
Is there anyway to turn the preview off for a SwipeListView? It gets annoying if it happens everytime for a user. It doesn't look like previewOpenValue={0} works

**Comment by lightninglu10** [comment]
Spent way too long on this. Setting `previewRowKey={false}` works...

**Comment by espadon54** [comment]
I am trying to turn off the preview as well but this is not working with the module 3.0.0
