### ISSUE TITLE
Hidden row icons disappear after being left visible and changing orientation of device

### ISSUE THREAD

**Issue by devonhuangcodes** [jemise111/react-native-swipe-list-view#257]
In the example provided, when you swipe open the list item and rotate the orientation of a device. The icons of the hidden row disappear. They reappear when you rotate it back to the previous orientation. I'm also getting the same behaviour in my project where I have react-native-swipe-list-view implemented.

**Orientation (Portrait)**
![original](https://user-images.githubusercontent.com/39835747/49492065-c0aeea80-f824-11e8-942b-ede447605125.jpg)

**Orientation (Landscape)**
![change_orientation](https://user-images.githubusercontent.com/39835747/49492071-c4db0800-f824-11e8-8a96-d9991dc2abf9.jpg)

**Comment by devonhuangcodes** [comment]
Recalculate the layout on the orientation change:
https://github.com/jemise111/react-native-swipe-list-view/issues/87

**Comment by jemise111** [comment]
@devonhuangcodes  👍
