### ISSUE TITLE
Fix shouldComponentUpdate method

### ISSUE THREAD

**Issue by maniloo** [jemise111/react-native-swipe-list-view#260]
Please fix shouldComponentUpdate method as it is described in this [comment](https://github.com/jemise111/react-native-swipe-list-view/pull/251). Is very important because now I have to provide `shouldComponentUpdate={true}` to have shouldItemUpdate functionality working correctly

**Comment by jemise111** [comment]
@maniloo Oops! My bad good catch. Fixed in v1.5.1, thanks!
