### ISSUE TITLE
Different stopRightSwipe per row?

### ISSUE THREAD

**Issue by dsandmark** [jemise111/react-native-swipe-list-view#261]
Thanks for this library @jemise111, it's very helpful.

I have a problem when swiping to reveal buttons behind a row. On some rows, I'd like the user to swipe to reveal one button and on others swipe to reveal three buttons. The buttons all have a width of `100`. That means a row with one buttons needs `stopRightSwipe` to be `100` while a row with three buttons need it to be `300`. Is there a way to accomplish this?

I could solve this by removing `stopRightSwipe` but I think it looks quite a lot better using it than allowing a user to swipe the whole row away.

If it helps any, here's how I'm using `SwipeListView`:

```javascript
<SwipeListView
  closeOnRowBeginSwipe
  data={this.items}
  disableRightSwipe
  keyExtractor={item => item.id}
  previewRowKey={first(this.items).id}
  renderHiddenItem={({ item }) => this.renderHiddenRow(item)}
  renderItem={({ item }) => this.renderRow(item)}
  rightOpenValue={-100}
  stopRightSwipe={-100}
  useFlatList
/>
```

**Comment by jemise111** [comment]
Hey @dsandmark yes you can definitely achieve that! Check out the docs for per-row-behavior here:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/per-row-behavior.md

Going to close this but please re-open if you have problems or any questions, thanks!

**Comment by dsandmark** [comment]
That's exactly what I was looking for, thanks @jemise111.
