### ISSUE TITLE
How to prevent bounce when using closeRow() with standalone SwipeRow

### ISSUE THREAD

**Issue by stonepreston** [jemise111/react-native-swipe-list-view#263]
Whenever I call closeRow() on a standalone swipe row, it closes it but has a bounce effect that exposes the hidden row on the far left side of the row. I would prefer to not have that bounce, is there a way to disable it?

I have disableRightSwipe = {true} on my swipe row.

**Comment by jemise111** [comment]
Hey @stonepreston I think you're referring to the spring animation that's used to close the row. By default I think the spring animation overshoots the final value a bit before finishing.

You should be able to change the `friction` and `tension` props to achieve what you're looking for. See more here:

https://facebook.github.io/react-native/docs/animated#spring
https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeRow.md#props

Please let me know if this answers your question, thanks!

**Comment by stonepreston** [comment]
awesome I increased the friction and its working great. Thanks for the quick reply!

**Comment by jemise111** [comment]
Sweet, glad to hear!
