### ISSUE TITLE
ScrollTo mehod is not working in react native 0.57.8 and react native swipe listview 1.5.0.

### ISSUE THREAD

**Issue by vykumar** [jemise111/react-native-swipe-list-view#266]
this.swipeListViewRef && this.swipeListViewRef.scrollTo && this.swipeListViewRef.scrollTo({x: 10000000, y: 10000000, animated: true})
 This above code was working with older version but after upgrading, it's not working.

**Comment by jemise111** [comment]
Hey @vykumar I assume you're using a flatList, in which case `scrollTo` isn't a supported method. RN may have deprecated it at some point. See here for a list of methods:

https://facebook.github.io/react-native/docs/flatlist#methods

I'm guessing you will achieve the same behavior with the following:

```
      this.swipeListViewRef && this.swipeListViewRef.scrollTo && this.swipeListViewRef.scrollTo({offset: 10000000, animated: true});
```

If not, please reopen and let me know, thanks!
