### ISSUE TITLE
onpress not work when rendering

### ISSUE THREAD

**Issue by canh-tran-niteco** [jemise111/react-native-swipe-list-view#270]
I have 20k rows and need fill to SectionList or FlatList. it's very large so I need to render by paging (50 rows/page). with 50 rows was rendering I can not press with TouchableOpacity (onPress). If I using the SectionList or FlatList it's work fine. Pls help me, thanks

**Comment by canh-tran-niteco** [comment]
I have 20k rows and need fill to SectionList or FlatList. it's very large so I need to render by paging (50 rows/page). with 50 rows was rendering I can not press with TouchableOpacity (onPress). If I using <FlatList /> it's work fine. Pls help me, thanks

**Comment by jemise111** [comment]
@canh-tran-niteco just to confirm have you followed these instructions:

https://github.com/jemise111/react-native-swipe-list-view#note

?

**Comment by canh-tran-niteco** [comment]
Yep, was followed and work well, thanks man
