### ISSUE TITLE
How to add "pull to refresh" in swipe list?

### ISSUE THREAD

**Issue by sarangpm18** [jemise111/react-native-swipe-list-view#273]
I want to implement "pull to refresh" in swipe list, is there any simple ways to do that?

**Comment by jemise111** [comment]
Hi @sarangpm18, a `SwipeListView` is just a `FlatList` (or ListView or SectionList) so you can pass the same props to achieve pull to refresh. See more here:

https://facebook.github.io/react-native/docs/refreshcontrol#usage-example

Closing.. please reopen if you have problems, thanks!
