### ISSUE TITLE
Programatically disable swipe behavior?

### ISSUE THREAD

**Issue by Slapbox** [jemise111/react-native-swipe-list-view#275]
Is there any way to disable the swipe behavior? I know that sounds like a ridiculous request, but I'd like to use this library, but not allow users access to the swipe functionality until I've had some more time to build it out.

**Comment by jemise111** [comment]
@Slapbox I haven't tried it but would `disableLeftSwipe={true}` and `disableRightSwipe={true}` do the trick?

Might not be the most efficient way but they do already exist

**Comment by Slapbox** [comment]
@jemise111 that sounds like exactly what I'd need! Thanks for your quick response!

Oddly, swiping right is still something I can do after adding those to the `<SwipeListView />` component. It seems to prevent it about 90% of the time, but sometimes I can still swipe it. Swiping left seems to be 100% disabled, but swiping right is not 100% disabled.

**Comment by jemise111** [comment]
@Slapbox Hm, can you post your code? Will try to take a look when I can

Additionally the real "right" way to do this is to prevent the gesture handler from accepting gestures in the first place if a certain prop is passed. Will also try to do then when I can but if you want to give it a shot and submit a PR, it's always welcome :)

**Comment by jemise111** [comment]
Closing, please reopen if this is still an issue, thanks!

**Comment by ilibilibom** [comment]
@jemise111 - this is still not working for me. 
I have 2 issues now: 

this is my code: 
```
<SwipeListView
            data={groupUsers}
            renderItem={(user, rowMap) => (
              <SwipeRow
                disableRightSwipe={true}
                disableLeftSwipe={true}
                // leftOpenValue={20 + parseInt(user.item.key) * 5}
                // rightOpenValue={-150}
              >
                {/* {console.log('user', user)} */}
                <View style={styles.rowFront}>
                  <View
                    style={[
                      styles.groupItem,
                      !isLastElement(groupUsers, user.index)
                        ? styles.borders
                        : null,
                    ]}>
                    <View style={styles.groupData}>
                      <View style={{width: 60}}>
                        <Avatar.Image
                          style={styles.groupActionIcon}
                          size={50}
                          source={
                            isSet(user.item) && user.item.profileImage
                              ? {
                                  uri: user.item.profileImage,
                                }
                              : require('./../../public/images/default-group-sm.png')
                          }
                        />
                      </View>
                      <View style={{justifyContent: 'center'}}>
                        <Text style={styles.groupTitle}>
                          {user.item.displayName}
                        </Text>
                      </View>
                    </View>
                  </View>
                </View>
              </SwipeRow>
            )}
            renderHiddenItem={(user, rowMap) => (
              <View
                style={[
                  styles.rowBack,
                  {
                    backgroundColor: theme.colors.primary,
                    flexDirection: 'row',
                    justifyContent: 'flex-end',
                    alignItems: 'center',
                  },
                ]}>
                <IconButton
                  size={30}
                  color="#fff"
                  icon="close"
                  style={{paddingTop: 10}}
                  onPress={() =>
                    dispatch(removeUserFromGroup(groupId, user.item))
                  }
                />
              </View>
            )}
            rightOpenValue={-60}
            keyExtractor={(item, index) => index.toString()}
          />
```

1) I'm getting this error: 
![Screen Shot 2019-12-17 at 10 57 47](https://user-images.githubusercontent.com/12745414/70980498-18309900-20bc-11ea-8dc1-3922a66ac1ff.png)
oddly enough, when I uncomment the console.log('user'), this error goes away ... 

2) When this does render (byI add the console.log), no effect is taking place, and the swipe is is not disabled.

**Comment by jemise111** [comment]
Hi @kpietrzak-web please see this doc https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/per-row-behavior.md
