### ISSUE TITLE
Using multiple TouchableOpacity in a row

### ISSUE THREAD

**Issue by saeid85** [jemise111/react-native-swipe-list-view#277]
In the **Readme.md** file, there is a part about **Good** and **bad** practice of using `TouchableOpacity`. What if you need multiple `TouchableOpacity` for each row? For example, a button on right side of the row and another on the other side.

Something like this:
```javascript
renderItem={ data => (
    <View>
        <TouchableHighlight onPress={this.doSomething.bind(this)}>
            <View>
               ...
            </View>
        </TouchableHighlight>
        <TouchableHighlight onPress={this.doSomething.bind(this)}>
            <View>
               ...
            </View>
        </TouchableHighlight>
    </View>
)}
```

What is the best practice in this case?
I'm working on an app and for a part I need to implement 3 different buttons (TouchableOpacity) per row. Right now I wraped them in a `View` but the issue is **sometimes** when one of them is pressed, the onPress function doesn't execute.

**Comment by jemise111** [comment]
Hey @saeid85, what you are proposing should work just fine. That section of the Readme is only referring to when you want to wrap the entire row in a touchable. You can have as many child Touchables as you like :)

If you have any issue please reopen, thanks!

**Comment by saeid85** [comment]
Thanks
