### ISSUE TITLE
Detect scroll end

### ISSUE THREAD

**Issue by KushalDesai1** [jemise111/react-native-swipe-list-view#280]
How to acheive pagination when end of list is reached after scrolling?

**Comment by jemise111** [comment]
Hey @KushalDesai1 you can use a `<SwipeListView>` exactly as you would a regular `<FlatList>`. So you can use the [onEndReached](https://facebook.github.io/react-native/docs/flatlist#onendreached) prop like so:

```
<SwipeListView
    ...
    onEndReached={() => this.loadMoreData()}
    ...
/>
```
