### ISSUE TITLE
##Onpress close open row is not Working

### ISSUE THREAD

**Issue by Uzama** [jemise111/react-native-swipe-list-view#281]
When I try to add a Touchable component as the parent component to Visible Component, then it called Touchable's onPress method without closing the open row. Any solution??

**Comment by jemise111** [comment]
Hi @Uzama have you tried following this?

https://github.com/jemise111/react-native-swipe-list-view#note

**Comment by davidleee** [comment]
I am having the same issue here.

Here is my SwipeListView:
```
<SwipeListView
            useFlatList
            keyExtractor={this._keyExtractor}
            style={styles.list}
            data={this.props.allChats}
            renderItem={this._onItemRender}
            renderHiddenItem={this._renderQuickActions}
            rightOpenValue={-80}
            closeOnRowPress
            closeOnRowOpen
            closeOnRowBeginSwipe
            closeOnScroll
            disableRightSwipe
            />
```

and this is my `_onItemRender` function:
```
_onItemRender({ item, index }) {

   // ... some setup to generate itemData

    return <ChatListItem key={index} index={index} item={itemData} onSelect={this._onPressItem} />
  }
```

and here is the what I am returning from `render` of my ChatListItem:
```
<TouchableHighlight onPress={this._selectItem}>
// ... many subviews
</TouchableHighlight>
```

I have bind `_onItemRender`, `_onPressItem` and `_selectitem` in their own constructors.

All the press logic works fine but `closeOnRowPress` seems broken to me, any ideas?

**Comment by davidleee** [comment]
Aha! I see what's going on here.

The `onRowPress` function is handled in *SwipeRow.js* with a check of children's `onPress` function:
```
renderVisibleContent() {
	  // handle touchables
	  const { onPress } = this.props.children[1].props

	  if (onPress) {
	    const newOnPress = (...args) => {
	      this.onRowPress()
	      onPress(...args)
	    }
	    return React.cloneElement(
	      this.props.children[1],
	      {
	        ...this.props.children[1].props,
	        onPress: newOnPress
	      }
	    )
	  }

// ... other return logic ...
```

In my case, rename ChatListItem's `onSelect` function to `onPress` will do the trick.

Anyway to make this logic more user friendly? ... or maybe consider highlight this somewhere in the document?

**Comment by jemise111** [comment]
Hey @davidleee please see the Readme here: https://github.com/jemise111/react-native-swipe-list-view#note

PR's always welcome if you'd like to add anything to it :)

**Comment by bashen1** [comment]
my workaround

**ChatListItem**
```javascript
<TouchableHighlight
          onPress={() => {
                    this.props.itemClickCB && this.props.itemClickCB();
          }}
>
          <Text>Test</Text>
</TouchableHighlight>
```

**ChatListItem parent component**
```javascript
 <SwipeListView
          data={listData}
          keyExtractor={item => `${item.id}`}
          renderItem={({item, index}, rowMap) => (
                    <ChatListItem
                              {...this.props}
                              index={index}
                              itemData={item}
                              itemClickCB={() => {
                                        rowMap[`${item.id}`].closeRow();
                              }}
                      />
          )}
/>
```

**Comment by jemise111** [comment]
Closing as this issue has been addressed and/or solved
