### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'VisibleComponent.props')

### ISSUE THREAD

**Issue by Uzama** [jemise111/react-native-swipe-list-view#282]
This is my code

<img width="776" alt="Screen Shot 2019-03-30 at 1 03 06 PM" src="https://user-images.githubusercontent.com/21138952/55273191-16386700-52ee-11e9-90e5-eaff4b704f8d.png">

I got TypeError: undefined is not an object (evaluating 'VisibleComponent.props')
<img width="1193" alt="Untitled 4" src="https://user-images.githubusercontent.com/21138952/55273226-a2e32500-52ee-11e9-858a-0108ca73b148.png">

**Comment by jemise111** [comment]
Hi @Uzama, it doesn't look like you're returning anything for `renderItem` or `renderHiddenItem`.

Change this:

```
renderItem={data => { 
    <FrontFace ... />
}}
```

to this:

```
renderItem={data => <FrontFace ... />}
```

That should fix it. If you have any problems, please reopen, thanks!
