### ISSUE TITLE
DeadObjectException on Android when implementing SwipeRow

### ISSUE THREAD

**Issue by FloPMT** [jemise111/react-native-swipe-list-view#283]
After the latest React Native update (0.59), implementing SwipeRow crashes the app on Android only, with the following exception:

```
RemoteException occurs on reporting focusChanged, w=Window{2470935 u0 bundle_id/bundle_id.MainActivity}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3879)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5426)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by DineshSutar** [comment]
+1

**Comment by suvodeep-pyne** [comment]
Getting the same error but only in release builds. Debug build seems to work fine.

**Comment by jemise111** [comment]
Hey guys, sorry but I'm not able to repro this. Just updated the example to RN 59.9 and I'm not getting any crashes. If someone could post a reproducible example that would be super helpful. Also the two exceptions posted are slightly different so I'm not sure if you're facing the same issue.

Lastly also try upgrading to the latest version of RN. Perhaps it exists only in <59.9?

**Comment by suvodeep-pyne** [comment]
Tried that already. 0.59.9 doesn’t solve the problem. However the crash seems difficult to reproduce. I was able to reproduce it a few times on Nexus 5x and another even older phone on a release build. Even though I have crashlytics installed, it wasn’t capturing the stacktrace. I’ll try and see if I can find a reliable way of reproducing the issue.

**Comment by kyle-ssg** [comment]
@suvodeep-pyne @jemise111 @DineshSutar @FloPMT I've been able to efficiently reproduce this in an application I'm developing, I can confirm that upgrading to 59.10 definitely fixes it for me

**Comment by kyle-ssg** [comment]
I've replicated this issue now on 2 production apps now on 59.9, to be clear though this is totally not to do with react-native-swipe-list-view

**Comment by jemise111** [comment]
@kyle-ssg Thanks for finding that! Would love to hear if upgrading fixes it for the rest of you

**Comment by KiranUppunda** [comment]
Hi, 
I'm facing something similar to that. 

`RemoteException occurs on reporting focusChanged, w=Window{ec2f368 u0`
`/my.com.my.app/my.com.my.app.MainActivity}`
   ` android.os.DeadObjectException`
      `  at android.os.BinderProxy.transactNative(Native Method)`
        `at android.os.BinderProxy.transact(Binder.java:1140)`
       ` at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)`
       ` at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3855)`
       ` at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5430)`
     `   at android.os.Handler.dispatchMessage(Handler.java:106)`
     `   at android.os.Looper.loop(Looper.java:214)`
       ` at android.os.HandlerThread.run(HandlerThread.java:65)`
       ` at com.android.server.ServiceThread.run(ServiceThread.java:44)`

I have already asked here - https://github.com/facebook/react-native/issues/25903

Thank you.

**Comment by jemise111** [comment]
Closing as this doesn't appear to be related to this library
