### ISSUE TITLE
Uneven row separator width

### ISSUE THREAD

**Issue by bcklup** [jemise111/react-native-swipe-list-view#284]
I've been experiencing this issue throughout all the instances on my app. It's become apparent that it's an issue with either RN or the library. I'm going with the former since my normal flatlists don't seem to display the said issues.. here's a screenshot:

![Pasted Image at 2019_04_01_04_50 pm_big](https://user-images.githubusercontent.com/23238488/55372666-1f674500-5535-11e9-9aee-2f6d9cbd1587.png)

The magnitude of difference is even accentuated with other devices..
I've tried to use multiple methods of applying the separators, namely:
- Adding a borderBottom to the front-most element
- ItemSeparator props
- a separate component(View) that appears as a separator

But in the end they all display the same uneven separator widths

**Comment by jemise111** [comment]
Hi @bcklup can you please post the code you're using to generate this issue, along with what device you're seeing this on? Happy to take a look, thanks!

**Comment by jemise111** [comment]
Closing as inactive
