### ISSUE TITLE
Render Hidden Row values are undefined

### ISSUE THREAD

**Issue by Messi10AP** [jemise111/react-native-swipe-list-view#285]
renderHiddenItem={(item, secId, rowId, rowMap) => (
                        <View style={styles.rowBack}>
                            <TouchableOpacity
                                onPress={() => {
                                    console.log("AAB", rowMap);
....

When I tried to print out the contents of secId, rowId, and rowMap, they were all undefined

**Comment by jemise111** [comment]
Hey @Messi10AP I just tried the above code and I'm not seeing any issues. Can you post a full example of how you're using the SwipeList and I can give it another look? Thanks!

**Comment by tientruongvan1995** [comment]
you mean renderHiddenRow? it's deprecated, using renderHiddenItem = (rowData, rowRef) instead. See the latest docs

**Comment by mitchdowney** [comment]
@Messi10AP I ran into an issue like this where rowMap/rowRef was undefined, and it turned out my keyExtractor in the SwipeListView was not setup properly, and was using undefined values for IDs.

**Comment by Messi10AP** [comment]
yep, forgot to update this, but I fixed it by adding a properly defined keyextractor
