### ISSUE TITLE
closeOnScroll not working

### ISSUE THREAD

**Issue by Messi10AP** [jemise111/react-native-swipe-list-view#287]
https://codeshare.io/2jPMRM

However when the code above renders, none of those values seem to work 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11220954/55987872-73c69f00-5c70-11e9-8a16-d6e9558a8e35.gif)

**Comment by jemise111** [comment]
Hey @Messi10AP typically when those props aren't working it's an issue with the unique keys for your data. I see you're using a `keyExtractor` prop. Can you try giving each piece of individual data a unique key and seeing if that fixes it?

If you could show me an example of what's in `this.state.notes` I might be able to help further, thanks!

**Comment by Messi10AP** [comment]
Yep, i forgot to close this issue, but using ’math.random()’ as my keyExtractor fixed it, thanks!

**Comment by val-fom** [comment]
> https://codeshare.io/2jPMRM

```
...
  keyExtractor={(item, index) => {
        index.toString();
    }}
...
```
You forgot to return the value of the extracted key

**Comment by GuillaumeMunsch** [comment]
For anyone using this with `useSectionList`, the `index` is reset in each section.
You'll need to make the returned key unique.

Here's what I did for example:
```
 keyExtractor={
    (item, index) => `${index}-${item?.ID}`;
}
```

Depends on which available values you have in each of your items
