### ISSUE TITLE
onSwipeValueChange on SwipeRow is only called once

### ISSUE THREAD

**Issue by conradjonp** [jemise111/react-native-swipe-list-view#288]
When I implemented onSwipeValueChange on my individual SwiperRow component, it is only called once when I swipe right, or left. This is pretty much useless as I need the X movement in real time.

When onSwipeValueChange is implemented on the SwipeListView, this function is called multiple times per second which is the correct behaviour.

Am I missing something on the onSwipeValueChange implementation? Here's a snip of my code below:

```
<SwipeRow 
    leftOpenValue={Dimensions.get('window').width}
    rightOpenValue={-Dimensions.get('window').width}
    onSwipeValueChange={this.onSwipeValueChange}>

    <HiddenView/>
    <VisibleView/>

</SwipeRow>
```

**Comment by jemise111** [comment]
Hey @conradjonp. Nope not missing anything. Just double checked and everything seems to be working properly... anything else you could tell me to help diagnose this? Platform, version numbers, stuff like that? Thanks!

![](http://g.recordit.co/Lv5ppPPWky.gif)

**Comment by conradjonp** [comment]
@jemise111 thanks alot for checking, I figured out what was wrong, it was a mistake on my side, apologies :)
