### ISSUE TITLE
Per Row Behavior documentation could use a note

### ISSUE THREAD

**Issue by timoisalive** [jemise111/react-native-swipe-list-view#290]
Seems like using `SwipeRow` as `renderItem` causes the list to ignore `closeOnScroll` and other similar flags. If this is intended behaviour, it could be beneficial to add in the documentation. :)

**Comment by jemise111** [comment]
Hey @timoisalive, nope that's not intended behavior. I just double checked and it's working properly on my end. If you're having issues please reopen and post your code and I'd be happy to take a look, thanks!

**Comment by bockc** [comment]
@timoisalive hey, I'm currently having the same issue as you. Did you fix it and if yes, how ?
