### ISSUE TITLE
Does not swipe + length undefined?

### ISSUE THREAD

**Issue by mikeKane** [jemise111/react-native-swipe-list-view#292]
I am getting an error located at ListView (at SwipeListView.js:255) stating cannot read property 'length' of undefined. 

Also I cannot seem to get swipe working? It just won't swipe. The options show to the left of my cells

```
<View style={{ marginTop: 10, marginBottom: 100 }}>
          <SwipeListView
            useFlatList={true}
            data={this.state.metaData}
            // extraData={this.state.shouldRender}
            leftOpenValue={75}
            rightOpenValue={-75}
            renderHiddenItem={(data, rowMap) => (
              <View style={styles.rowBack}>
                <Text>Left</Text>
                <Text>Right</Text>
              </View>
            )}
            onRowOpen={(secId, rowId, rowMap) => {
              setTimeout(() => {
                rowMap[`${secId}${rowId}`].closeRow();
              }, 2000);
            }}
            previewFirstRow={true}
            renderItem={({ item, index }) => (
              <TouchableOpacity onPress={() => this.selectResult(index)}>
                {this.showCheckBox(index)}
                <Results result={item} />
              </TouchableOpacity>
            )}
          />
        </View>
```

**Comment by mikeKane** [comment]
This is being rendered inside of a drawer navigator , is that a problem?

**Comment by mikeKane** [comment]
![IMG_3173](https://user-images.githubusercontent.com/7225808/59301694-35ddfb00-8c60-11e9-98a0-64cec58268f5.PNG)

**Comment by jemise111** [comment]
Hey @mikeKane do you think you could set up a reproducible example? It'll be tough to figure out what's this without knowing the styles of your components, how you're using the drawer navigator, the data you're passing to the SwipeListView, etc. Thanks!

**Comment by jemise111** [comment]
Closing as inactive

**Comment by Sydney-o9** [comment]
Confirming I have the same issue inside a DrawerNavigator
