### ISSUE TITLE
Expo does not work with this

### ISSUE THREAD

**Issue by eleallegue** [jemise111/react-native-swipe-list-view#293]
Hi,

I have a Snack with the code I am trying to use, and I just paste it into my project (in Visual Studio Code, for a whole app) the thing is that whenever I click on the button that redirects me to the compoenent where the Snack will appear, I get this error:
![image](https://user-images.githubusercontent.com/15983836/59304991-99384f00-8c99-11e9-8168-97f9205d7594.png)

You can take a look at the snack HERE: https://snack.expo.io/@guardme/react-native-swipe-list-view

As you can see, that works perfectly both in iOS and Android. But the problem that I describe above arrises....

If you could help me please and thank you

**Comment by Slapbox** [comment]
It works fine for me with Expo 31 and 33.

**Comment by elioncho** [comment]
It's also working for me with Expo 35

**Comment by jemise111** [comment]
Doesn't seem like this is an issue anymore, please re-open if it is, thanks!
