### ISSUE TITLE
how to achieve section headers?

### ISSUE THREAD

**Issue by rjuevesano** [jemise111/react-native-swipe-list-view#295]
How to achieve section headers? See picture below for reference.

![image](https://user-images.githubusercontent.com/4033035/59750539-8df4ad00-92b1-11e9-9afd-aaf4d30a24ab.png)

**Comment by jemise111** [comment]
Hey @rjuevesano if you run the example you'll see there's a `SwipeListView` that uses section headers. Please see here: 

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L233

Let me know if you have any problems, thanks! (love the diagram btw :)

**Comment by rjuevesano** [comment]
Wow! I just saw it. Thanks a lot!
