### ISSUE TITLE
TouchableOpacity not pressable if out-of-window 

### ISSUE THREAD

**Issue by Bartozzz** [jemise111/react-native-swipe-list-view#297]
I need to display two `<TouchableOpacity />` in a row:
- the first one (red) must take all the available space on the screen;
- the second one (blue) should be displayed when the row is swiped left;

![image](https://user-images.githubusercontent.com/6741707/59760015-9937e080-9291-11e9-8a04-d3fd6cd5b861.png)

```jsx
<SwipeListView
  useFlatList
  data={data}
  keyExtractor={item => item.id}
  renderItem={(data, rowMap) => (
    <View style={styles.itemContainer}>
      <TouchableOpacity
        style={[styles.item, styles.itemFront]}
        onPress={() => console.log(`Pressed ${data.item.id}`)}
      >
        <Text>{data.item.id}</Text>
      </TouchableOpacity>

      <TouchableOpacity
        style={[styles.item, styles.itemBack]}
        onPress={() => rowMap[data.item.id].closeRow()}
      >
        <Text>Close</Text>
      </TouchableOpacity>
    </View>
  )}
  renderHiddenItem={() => <View />}
  disableRightSwipe={true}
  rightOpenValue={-(height + marginHorizontal)}
/>
```
The problem is that the second `<TouchableOpacity />` is not pressable on Android devices (on iOS everything works good):
- https://snack.expo.io/rkYb7cvyB (implemented using container wider than 100%);
- https://snack.expo.io/SkClm5vJS (implemented using absolute positioning);

What is the issue with the demos above? Are there any alternative implementations which will fulfill those design specifications while working on Android?

---

Tested on Android & iOS:
- `react-native`: v. 0.59
- `react-native-swipe-list-view`: latest (v. 1.5.5)

**Comment by jemise111** [comment]
Hey @Bartozzz, sorry man but it looks like this one is a RN issue, it's out of my hands:

https://github.com/facebook/react-native/issues/24046

Hope they can fix that soon :)
