### ISSUE TITLE
Not working in ios

### ISSUE THREAD

**Issue by lsbiosite** [jemise111/react-native-swipe-list-view#298]
So I have the library working on android but I can't get it to work on IOS. I've looked at https://github.com/jemise111/react-native-swipe-list-view/issues/85 and I'm (guessing) it's caused by a conflicting issue with https://github.com/wix/react-native-navigation (?). Hopefully this can get resolved as that seems to be the de facto standard navigation library for RN!

Thanks for all your work so far on this though @jemise111 - it's really appreciated :)

**Comment by Kirill-Cherkalov** [comment]
I ran into the same problem that the swipe effect didn't work well on ios(assuming you have `` react-native-navigation `` ). I managed to solve the problem by setting the value of `` openGestureMode: 'bezel' `` in `` Navigation.setDefaultOptions ``
```
  Navigation.setDefaultOptions({
    sideMenu: {
     openGestureMode: 'bezel',
    },
  });
```
Perhaps the same problem will be solved if you use [react-native-swipeout](https://github.com/dancormier/react-native-swipeout) .
I hope this helps you, because I spent a lot of time on it myself.

**Comment by jemise111** [comment]
Hey @lsbiosite this is going to be a little tough to diagnose given it depends on how you're using the navigation library. Do you think you could make a small example app with the problem? I'd be more than happy to take a look and try to figure out what's going on.

Also IMO I'm not sure rnn is the de facto standard, FB still recommends react-navigation https://facebook.github.io/react-native/docs/navigation. Either way it'd be great to get these issues fixed, thanks! :)

**Comment by lsbiosite** [comment]
@Kirill-Cherkalov  - thanks. I'll look into that, but for now I've changed what I'm using unfortunately as I needed to finish the ticket for the sprint!

@jemise111  I can have a look at whacking one up after work :). I'm new to react-native (I'm an angular developer by experience) so I'm being baptised by fire here! Thanks for the prompt reply though :)

**Comment by Stacyadam** [comment]
@Kirill-Cherkalov you just saved me several hours worth of pain. Thank you!

**Comment by terreb** [comment]
@Kirill-Cherkalov, I thought I've tried just everything... Thank you a lot!!!

**Comment by jemise111** [comment]
Seems like this issue was solved, please reopen if it's still a problem, thanks!
