### ISSUE TITLE
Types are broken

### ISSUE THREAD

**Issue by undercase** [jemise111/react-native-swipe-list-view#302]
@MaShizhen's recent PRs to add types are breaking-he declares every single prop (the majority of which are optional) as mandatory.

**Comment by MaShizhen** [comment]
ok, I will fix the problem as soon as possible

**Comment by undercase** [comment]
They are also broken in a number of other ways. For example, they define function parameters for every function prop the wrong way (using a `params` argument).

**Comment by taoqf** [comment]
@undercase Will this do? Could u pls take some time and review the pr?

**Comment by jemise111** [comment]
@undercase +1, my typescript type definition review skills are lacking. Would love it if you could take a look, thanks!

**Comment by vinithreddy3** [comment]
Hi all , if we are using a flatlist in swipelistview can we use all properties of flatlist directly as properties for swipelistview ?
