### ISSUE TITLE
renderHiddenitem values are undefined

### ISSUE THREAD

**Issue by SubashManian** [jemise111/react-native-swipe-list-view#304]
this is my code 

> <SwipeListView
                        useFlatList
                        ref= {refs => this.swipelist = refs}
                        closeOnScroll={true}
                        closeOnRowBeginSwipe={true}
                        closeOnRowPress={true}
                        style={{marginBottom: 0}}
                        data={this.state.dataSource}
                        renderItem={ ({item}) => (
                            <ProfileWaiting userImg={item.profileImages[0].thumbnail_url}
                                            source={item.message.text === "" ? require('./../../../assets/icons8-screenshot-filled-25.png') : ""}
                                            photoVal={item.message.text === "" ? "Photo" : ""}
                                            isTrue={item.message.text === "" ? true : false}
                                            chatCount={item.unReadCount}
                                            goToChatRoom={() => {
                                                if(this.state.NoNetwork){
                                                    reactotron.log(item,this.state.senderUserName),
                                                    clearInterval(timer),
                                                    this.setState({loaderState:true},()=>{
                                                        this.props.navigation.navigate("chatRoom", {
                                                            item: item,
                                                            roomId: item.id,
                                                            fullName: item.fullname,
                                                            profileId: item.profileImages[0].profile_id,
                                                            senderUserName: this.state.senderUserName,
                                                            userImg: item.profileImages[0].thumbnail_url,
                                                            receiverId: item.sender_id
                                                        })
                                                    })
                                                }else{
                                                    this.showAlert('Please check your network connection and try again','danger');
                                                }
                                            }}
                                            userName={item.fullname}
                                            subtitle={item.message.text === 'MissedCall_'? "Missed Video Call" : item.message.text}
                                            roomId={item.id}
                                            profileId={item.profileImages[0].profile_id}
                                            senderUserName={this.state.senderUserName}
                                            loaderState={this.state.loaderState}
                            />
                        )}
                        renderHiddenItem={ ({rowData, rowMap}) => (
                            <View style={styles.rowBack}>
								<TouchableOpacity onPress={()=>{
reactotron.log("rowData",rowData, "rowMap",rowMap)}
} style={[styles.backRightBtn, styles.backRightBtnRight]}>

> <T>Delete</T>
> </TouchableOpacity>
> </View>
> )}
> rightOpenValue={-75}
> keyExtractor={(item, index) => index.toString()}
> />

in that row data and row map values are printing as undefined in the render item i use my customized view for the list. is any another way to close the swiped row without rowmap in code wise.

![Screen Shot 2019-07-02 at 4 22 48 PM](https://user-images.githubusercontent.com/45756921/60507422-c2bb2800-9ce5-11e9-9a6f-8ce6da063a8a.png)

**Comment by jemise111** [comment]
Hey @SubashManian you have unnecessary `{ }` in your `renderHiddenItem` callback. Instead of 
```
renderHiddenItem={({ rowData, rowMap }) => (
```
it should be
```
renderHiddenItem={(rowData, rowMap ) => (
```

That should fix your issue, thanks!

**Comment by SubashManian** [comment]
Thanks for the reply @jemise111  after removing `{ }` also it not printing the rowMap it gives the error of circular reference JSON object but the opened row's are closing now it works fine. but i'm not able view the values in the rowMap.

thanks

**Comment by nicefella** [comment]
Same here

**Comment by serialbandicoot** [comment]
I have the same issue, it looks like `renderItem` has the following implementation:

```javascript
let { key } = item
if (!key && this.props.keyExtractor) {
	key = this.props.keyExtractor(item, index);
}
```
So if it can't find `key` it defaults with `undefined`.

My datasource is external so there is no key in the example it looks like a key is being applied.

**Comment by Urolovshohjahon** [comment]
ok
