### ISSUE TITLE
useNativeDriver causes onRowPress bug

### ISSUE THREAD

**Issue by zavin27** [jemise111/react-native-swipe-list-view#306]
when using useNativeDriver, if I swipe in a direction, let's say to the left, then I tap on the row for the onRowPress to be called, the row animates back to the original state which is good so far, but then if I try to swipe again to the left it'll instantly snap back to the swiped position that it was from the first time I swiped and then continue the animation from there based on the direction that I'm swiping.
This bug only happens if I use the NativeDriver.

**Comment by lorenc-tomasz** [comment]
Similar issue. From 1.5.8 you can disable native driver for now.

**Comment by jemise111** [comment]
@zavin27 Yeah I ran into this myself so I pushed a quick change to allow you to pass `useNativeDriver={false}` to disable it on the SwipeListView or SwipeRow

**Comment by lorenc-tomasz** [comment]
@jemise111 Will fix it, so we will be able use Native Driver?

**Comment by jemise111** [comment]
@lorenc-tomasz opened a new issue to address it. I'll get to it as soon as possible, it's a bit tricky.

 https://github.com/jemise111/react-native-swipe-list-view/issues/312
