### ISSUE TITLE
Support for keyboardShouldPersistTaps and other ScrollView and FlatList  props

### ISSUE THREAD

**Issue by Slapbox** [jemise111/react-native-swipe-list-view#307]
It would be great to be able to pass the list component `react-native-swipe-list-view` renders props like `keyboardShouldPersistTaps` .

Something like:

```js
 <SwipeListView
    useFlatList
    keyboardShouldPersistTaps="always"
/>
```

**or**

```js
 <SwipeListView
    useFlatList
    componentProps={
        keyboardShouldPersistTaps: "always"
    }
/>
```

**Comment by jemise111** [comment]
Hey @Slapbox you can! (as in your first example) I pass all props to the underlying FlatList. See here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L234
