### ISSUE TITLE
Change background JSX depending on swipe direction

### ISSUE THREAD

**Issue by jobetdelima** [jemise111/react-native-swipe-list-view#308]
I want to render a different JSX depending on whether the user has swiped left or right. I could determine the swipe direction from  onSwipeValueChange but I'm needing to force re-render (i.e. I'm using forceUpdate()) to trigger renderHiddenItem (and renderItem) again. 

Doing the latter is super expensive and is slowing down the animation drastically.

Is there a way to just render the row currently being swiped?

Thanks!

**Comment by jemise111** [comment]
Hey @jobetdelima so this isn't perfect, I threw it together quickly. But it achieves what you want without calling `forceUpdate` and performs pretty well on my crappy Android phone so it should do the trick with a little modification.

Note I used `renderItem` instead of `renderHiddenItem` so you could better see the effect but it should work for both

Hope this helps! If you're still having problems please re-open, thanks!

```
onSwipeValueChange = (swipeData) => {
	const { key, direction } = swipeData;
	const newState = {};
	if (key !== this.state.activeRowKey) {
		newState.activeRowKey = key;
	}
	if (direction !== this.state.swipeDirection) {
		newState.swipeDirection = direction;
	}

	if (Object.keys(newState).length > 0) {
		this.setState(newState);
	}
}

renderItem = (data, rowMap) => {
	if (this.state.activeRowKey === data.item.key && this.state.swipeDirection === 'right') {
		return (
			<TouchableHighlight
				onPress={ _ => console.log('This is the new jsx') }
				style={[styles.rowFront, {backgroundColor: 'yellow'}]}
				underlayColor={'#AAA'}
			>
				<View>
					<Text>This is completely different JSX!</Text>
				</View>
			</TouchableHighlight>
		);
	}

	return (
		<TouchableHighlight
			onPress={ _ => console.log('This is the old jsx') }
			style={styles.rowFront}
			underlayColor={'#AAA'}
		>
			<View>
				<Text>I am {data.item.text} in a SwipeListView</Text>
			</View>
		</TouchableHighlight>
	);
};

render() {
	return (
		<SwipeListView
			useFlatList
			data={this.state.listViewData}
			renderItem={this.renderItem}
```

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/4265163/61015838-00a5f500-a353-11e9-89a5-8977d4acefe0.gif)

**Comment by jobetdelima** [comment]
@jemise111 First, 'Appreciate the feedback :)

We ended up doing something similar except we're monitoring that the `value` from SwipeData is within an acceptable range to determine whether we're swiping left or right, instead of just looking at `direction`. The latter tends to change a lot so it was resulting in lots of state changes, hence re-rendering. Re-rending fires renderItem() and renderHiddenItem() for all rows, which is slowing things down.

Thanks for the library!

**Comment by jemise111** [comment]
👍 sounds good, glad you found a solution

**Comment by manosKas** [comment]
@jobetdelima 
May I take a look at your code? I'm trying to accomplish something similar where on long press goes into multiple selection mode and then every onPress on an item highlights it as selected. In my case its re-rendering all of the items in the list and I have a lag on every selection. I'm trying to wrap renderItem with memo properly but I can't find the proper syntax for this specific case cause the props for renderItem are exported like ({ item, index }) and memo can't pass them... I think... item is undefined is all I get

> @jemise111 First, 'Appreciate the feedback :)
> 
> We ended up doing something similar except we're monitoring that the `value` from SwipeData is within an acceptable range to determine whether we're swiping left or right, instead of just looking at `direction`. The latter tends to change a lot so it was resulting in lots of state changes, hence re-rendering. Re-rending fires renderItem() and renderHiddenItem() for all rows, which is slowing things down.
> 
> Also, we've used `React.memo` for rendering the background JSX for a bit of optimization.
> 
> Thanks for the library!
