### ISSUE TITLE
Warning: componentWillMount is deprecated

### ISSUE THREAD

**Issue by pa-bouly** [jemise111/react-native-swipe-list-view#309]
I've just upgraded my app to react-native 0.60 and added the eslint from @react-native-community and now I'm getting this warning.
I think we just have to change **componentWillMount** to **componentDidMount** in SwipeRow.js What do you think? 

<img width="446" alt="Capture d’écran 2019-07-08 à 09 52 50" src="https://user-images.githubusercontent.com/10745291/60792542-2cb05300-a166-11e9-8dc1-2864c3aaad3d.png">

Btw, thanks for this great component :)

**Comment by jemise111** [comment]
@pa-bouly thanks for reporting! I moved it to the `constructor` instead. It'll be fixed in the next release
