### ISSUE TITLE
how to make "rightOpenValue" a dynamic value?

### ISSUE THREAD

**Issue by cmdillon** [jemise111/react-native-swipe-list-view#31]
hi, i was wondering how i can make "rightOpenValue" value dynamic? i tried adding "ref=" to a "View" element, and then doing something like: facebook/react-native#953 
but that didn't work seems the "ref" is not available inside "renderHiddenRow". any ideas or examples would be appreciated.

**Comment by jemise111** [comment]
Hey @cmdillon, good find, as of now there isn't support for this. Currently whatever is passed to the `renderRow` and `renderHiddenRow` props is wrapped in a `SwipeRow` and each row is passed the same properties for `rightOpenValue`, `leftOpenValue` etc.

It would be great if there was an option to just pass a `SwipeRow` to the `renderRow` function and the `SwipeListView` could check for that and not do the wrapping. I think that would do the trick as far as dynamic values are concerned.

I'll try to get to this asap but PR's are always welcome 😃

**Comment by cmdillon** [comment]
thanx for the feedback!

**Comment by jemise111** [comment]
@cmdillon Finally got around to it. Npm install the latest version and check out the docs [here](https://github.com/jemise111/react-native-swipe-list-view#per-row-behavior) for dynamic values on SwipeRows.

Let me know if you have any further problems or questions!
