### ISSUE TITLE
RN 0.60 Support?

### ISSUE THREAD

**Issue by Psiiirus** [jemise111/react-native-swipe-list-view#310]
Hiya,
this component seems to be broken if you upgrade to RN 0.60 because you still use ListView.
is there already a branch where its already fixed which can I use?

**Comment by gtaylor44** [comment]
try adding this property:

<SwipeListView useFlatList ... />

**Comment by Psiiirus** [comment]
> try adding this property:
> 
> <SwipeListView useFlatList ... />

I already use this prop :) but i guess the code-checker sees deprecated usages.

**Comment by jemise111** [comment]
@Psiiirus this should be fixed in the latest version! (v2.0.0)
