### ISSUE TITLE
Wrong swipe row briefly shown when swiping in the other direction

### ISSUE THREAD

**Issue by ryandt** [jemise111/react-native-swipe-list-view#311]
In the `SwipeListExample`, I'm seeing a bug where the wrong swipe row is briefly shown when swiping in the other direction. I'm able to reproduce this in Android and iOS running the example and running my own usage of `SwipeListView` in my app.

react-native-swipe-list-view version: 1.5.8

**Steps to reproduce**:
1. Swipe to the right on a row (the text "Left" is shown)
2. Close the row by clicking the overlay row or scrolling
3. Swipe to the left on the same row

**Actual result**:

The left row ("Left" text) briefly slides in before opening the row to the right ("Right" and "Delete" text)

**Expected result**:

The right row ("Right" and "Delete" text) opens and the left row ("Left" text) does not slide in

**Slowed down gif of the issue**:

![swipe-bug](https://user-images.githubusercontent.com/4073952/60934853-70ea4300-a28d-11e9-853b-f7905a6e3e71.gif)

**Comment by jemise111** [comment]
Hey @ryandt I believe this is the same issue as #306. Can you try passing `useNativeDriver={false}` to your SwipeListView and see if that fixes it? Thanks

**Comment by ryandt** [comment]
Hey @jemise111. That resolved the issue I was seeing, thanks!
