### ISSUE TITLE
how can I close the swiped row on a condition?

### ISSUE THREAD

**Issue by blueturtle13g** [jemise111/react-native-swipe-list-view#313]
I want to be able to close the swiped row under some circumstances! is there any callback function or `ref` thing that I can call to close it?

**Comment by jemise111** [comment]
Hey @blueturtle13g yup you can see an example of this in action here: 

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L194

Let me know if you have any problems!
