### ISSUE TITLE
Preview Left and Right Swipe

### ISSUE THREAD

**Issue by adteague** [jemise111/react-native-swipe-list-view#317]
Hi, is it possible to preview a left-to-right swipe then a right-to-left swipe? I am able to do one, but not both

**Comment by jemise111** [comment]
Hey @adteague, this is a pretty unique use case so rather than use the preview props I'd do this one manually. You can get a reference to the `rowMap`, then whenever you want to preview get the row from the `rowMap` using its `key` and call `manuallySwipeRow` to swipe it whichever direction you like. Here's an example that worked for me:

```
setMap = (rowMap) => () => {
	if (!this.rowMap) {
		this.rowMap = rowMap;
	}
}

componentDidMount() {
	const firstRowRef = this.rowMap['0'];
	setTimeout(() => {
		firstRowRef.manuallySwipeRow(-150);
		setTimeout(() => {
			firstRowRef.manuallySwipeRow(75);
			setTimeout(() => {
				firstRowRef.manuallySwipeRow(0);
			}, 2000);
		}, 2000);
	}, 2000);
}

render() {
	return (
		<SwipeListView
			renderItem={ (data, rowMap) => (
				<TouchableHighlight
					ref={this.setRef(rowMap, data.item.key)}
					onPress={ _ => console.log('You touched me') }
					style={styles.rowFront}
					underlayColor={'#AAA'}
				>
					<View>
						<Text>I am {data.item.text} in a SwipeListView</Text>
					</View>
				</TouchableHighlight>
			)}
			...
			leftOpenValue={75}
			rightOpenValue={-150}
		/>
```

**Comment by adteague** [comment]
I'm getting a `Cannot read property '0' of undefined` error when pasting in your code

**Comment by jemise111** [comment]
@adteague That's just an example using my data from `example.js`. You need to replace the `'0'` with the key for the row you want to preview
