### ISSUE TITLE
how to delete a row?

### ISSUE THREAD

**Issue by cmdillon** [jemise111/react-native-swipe-list-view#32]
hi, is there an example of how to delete a row?

**Comment by jemise111** [comment]
Yes! Check out `example.js` here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L71

Let me know if you have any further questions.

**Comment by cmdillon** [comment]
i saw that, but it seems not to work. the row closes, but the row doesn't get removed. any ideas?
btw: used your example code and my rn is 0.27.0

**Comment by jemise111** [comment]
What version of React are you using. I'll try to replicate

**Comment by cmdillon** [comment]
i'm using the fallowing:
"react": "^15.1.0",
"react-native": "^0.27.0",

**Comment by jemise111** [comment]
Updated my package.json. Reinstalled all node_modules.
Using:
React 15.1.0
React Native 0.27.2

I'm not seeing any problems:

![](http://g.recordit.co/YyQ873caCA.gif)

Maybe remove node_modules, upgrade to 0.27.2, reinstall the app, and give it another shot?
If it's still not working let me know what device you're using, OS, etc and if I can I'll use the same.

**Comment by cmdillon** [comment]
ok, i'll give it a try later and see if that helps. i'll keep you posted. thanx again for the quick feedback.

**Comment by cmdillon** [comment]
hi, i removed node_modules, upgrade to 0.27.2, reinstall the app, and give it another shot. but unfortunately no effect.

i'm using a mac and i'm testing in the simulator with iphone 6. i'm also using redux.

**Comment by cmdillon** [comment]
ok—so used exactly your code example and all works. i guess it must the the structure that i'm using in my lists. hmmm...

**Comment by jemise111** [comment]
Okay well I'm glad it's working in at least that case. I'm happy to take a look at some code if it's public. Or feel free to send me a private gist or something - jesse [dot] sessler [at] gmail
