### ISSUE TITLE
Disable swipe only for one section

### ISSUE THREAD

**Issue by BesartD** [jemise111/react-native-swipe-list-view#320]
Im using "SwipeListView" with "useSectionList" option and I have 2 sections. I want to disable swiping left or right for one section only. Is it somehow possible?

**Comment by jemise111** [comment]
@BesartD off the top of my head this might work for you: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/per-row-behavior.md#setting-per-row-behavior-using-data

If not LMK

**Comment by BesartD** [comment]
@jemise111 it worked, thank you :)
