### ISSUE TITLE
Undocumented feature: Multiple buttons in same swipe

### ISSUE THREAD

**Issue by nferrara100** [jemise111/react-native-swipe-list-view#321]
In the example picture in the readme it is possible to have two buttons revealed in one swipe ("Right 1" and "Right 2"). However, after looking through the documentation I do not see how this is accomplished. If someone could provide example code that would be much appreciated!

**Comment by jemise111** [comment]
Hey @nferrara100 if you have a look at the example in `example.js` you can see how that is achieved with some sample code. See here for the 2 buttons in the hidden row: https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L124

Thanks!
