### ISSUE TITLE
Hidden Row is overlapping with the Render Item

### ISSUE THREAD

**Issue by wilsonting** [jemise111/react-native-swipe-list-view#322]
Hi, when trying to use the SwipeListView, the hidden item always visible once the components is mounted. Is there any properties need to be defined ?? The code below is simplified and the screenshot shows the problem I faced. Thanks.

`class DummyList extends Component {
	renderRow(data){
        return (
            <DummyListItem data={data} />
        );
    }
	renderLeft(){
        return (
            <Text>TESTING</Text>
        );                   
    }
	render() {
        return (
            <Container>
                <SwipeListView
                    data={this.props.dummyDatas}
                    renderItem={this.renderRow}
                    renderHiddenItem={this.renderLeft}
                />
            </Container>
        );
    }
}`

![IMG_7411](https://user-images.githubusercontent.com/14285635/61992703-2db51000-b094-11e9-8f04-522103af4b34.PNG)

**Comment by jemise111** [comment]
Hi @wilsonting you need to define styles for your row and hidden row and give your row a background color to hide the hidden row. It is only "hidden" in the sense that it is positioned behind the row.

You can see `example.js` for some example code of styling that will achieve this. If you have more issues please re-open, thanks!

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L108
