### ISSUE TITLE
 right view (Swipe left)  is blank while left view (swipe right) contains all content of right and left

### ISSUE THREAD

**Issue by lincdh** [jemise111/react-native-swipe-list-view#323]
>           <SwipeRow
>                 leftOpenValue={75}
>                 rightOpenValue={-75}
>             >
>                 <View style={styles.rowList}>
>                     <Text style={styles.row}>Left</Text>
>                     <Text style={styles.row}>Right</Text>
>                 </View>
>                 <View style={styles.rowList}>
>                     <Text style={styles.row}>I am a standalone SwipeRow</Text>
>                 </View>
>             </SwipeRow>

I got below result:
[https://imgur.com/NBsS7Tn](https://imgur.com/NBsS7Tn)

It also happens with SwipeListView

**Comment by Caglankaan** [comment]
i do have same problem +++

**Comment by jemise111** [comment]
@lincdh Would be super helpful if you could post the styles as well!

**Comment by lincdh** [comment]
> @lincdh Would be super helpful if you could post the styles as well!

hi,
i had to remove current style and add position: and right: css in right <Text> to make it works

also how can i close other opening rows while i am swiping new row in the lists?
i see the SwipeListView has closeOnRowOpen and closeOnRowBeginSwipe but none works?

thank u

**Comment by lincdh** [comment]
> > @lincdh Would be super helpful if you could post the styles as well!
> 
> hi,
> i had to remove current style and add position: and right: css in right to make it works
> 
> also how can i close other opening rows while i am swiping new row in the lists?
> i see the SwipeListView has closeOnRowOpen and closeOnRowBeginSwipe but none works?
> 
> thank u
