### ISSUE TITLE
Question: How do I know which rows have been swiped?

### ISSUE THREAD

**Issue by crypt0d3v** [jemise111/react-native-swipe-list-view#324]
I want to have a list of values, and track which ones have been swiped. I don't want them deleted - I want to use the swipe to mark data as chosen but I am struggling to get it to work.

render fn:

<SwipeListView
                    data={this.state.data}
                    leftOpenValue={125}
                    rightOpenValue={0}
                    onSwipeValueChange={this.handleSwipeValueChange}
                    disableLeftSwipe={true}
                    renderItem={({ item }) => (
                        <View style={styles.rowFront} underlayColor={'#AAA'}>
                            <Text>{ item.text }</Text>
                        </View>
                    )}
                    renderHiddenItem={ (data, rowMap) => (
                        <View style={styles.rowBack}>
                            <Text>Marked!</Text>
                        </View>
                    )}
                />

handleSwipeValueChange( { isOpen }, key ) {
        const { data } = this.state

        const words = data.map(d => 
            {
                const chosen = d.key === key
                    ? isOpen
                    : d.chosen

                return {
                    ...d,
                    chosen,
                    isOpen: chosen
                }
            })

        this.setState({
             data
        })
    }

**Comment by jemise111** [comment]
Hey @crypt0d3v I'd suggest using the `onRowOpen` prop instead of tracking the swipe value changes. Here's a working example for you (rows turn green when they are "marked"). Hope this helps, if you have more questions please ask, thanks!

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/4265163/63230225-56ca4b80-c1cf-11e9-851d-3c4aedb6f987.gif)

```
class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
    markedKeys: [],
      listType: 'FlatList',
      listViewData: Array(20).fill('').map((_,i) => ({key: `${i}`, text: `item #${i}`})),
    };
  }

  mark = rowKey => {
    this.setState({
      markedKeys: [
        ...this.state.markedKeys,
        rowKey
      ],
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <SwipeListView
          data={this.state.listViewData}
          onRowOpen={this.mark}
          renderItem={ (data, rowMap) => (
            <View style={[
               styles.rowFront,
               this.state.markedKeys.includes(data.item.key) && {backgroundColor: 'green'}
            ]}>
              <Text>I am {data.item.text} in a SwipeListView</Text>
            </View>
          )}
          renderHiddenItem={ (data, rowMap) => (
            <View style={styles.rowBack}>
              <Text>Left</Text>
              <View style={[styles.backRightBtn, styles.backRightBtnRight]}>
                <Text style={styles.backTextWhite}>Marked!</Text>
              </View>
            </View>
          )}
          leftOpenValue={75}
          rightOpenValue={-75}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
    paddingTop: 50,
  },
  backTextWhite: {
    color: '#FFF'
  },
  rowFront: {
    alignItems: 'center',
    backgroundColor: '#CCC',
  justifyContent: 'center',
  borderBottomColor: 'black',
  borderBottomWidth: 1,
  height: 50,
  },
  rowBack: {
    alignItems: 'center',
    backgroundColor: '#DDD',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 15,
  },
  backRightBtn: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 75
  },
  backRightBtnLeft: {
    backgroundColor: 'blue',
    right: 75
  },
  backRightBtnRight: {
    backgroundColor: 'red',
    right: 0
  },
});
```
