### ISSUE TITLE
Can't change the renderHiddenRow height?

### ISSUE THREAD

**Issue by msqar** [jemise111/react-native-swipe-list-view#325]
I copy pasted the example.js code into mine so I could test it out, adapt it to my needs and so on. It works fine so far, except for the fact that I can't seem to change the hidden row height, seems to be stuck at 30-40ish ... I'm able to change the frontRow, though. So it looks ugly when I swipe and I see the delete button container is half the size of the actual front row.

Is this a bug?

Attempted adding the `height: 70` to absolutely every element on the backRow with 0% success.

**Comment by wuxiii** [comment]
did you achieve this feature？
