### ISSUE TITLE
Question: Is there support for sliding in the hidden view?

### ISSUE THREAD

**Issue by robjweiss** [jemise111/react-native-swipe-list-view#326]
Is it possible to have the hidden view slide in from off screen rather than be revealed from under the main view?

**Comment by jemise111** [comment]
Hey @robjweiss unfortunately that's a very different component hierarchy than what this library is doing. As a sort of hack you could try to set the width of your `renderItem` to be the width of the screen + the additional width needed to render your hidden buttons. I do believe you'll have some issues on Android, as RN does not handle `overflow` very well

I'd suggest looking into these libraries for that:
https://github.com/jshanson7/react-native-swipeable
https://github.com/kmagiera/react-native-gesture-handler

Hope that helps!
