### ISSUE TITLE
Using a SwipeRow Component

### ISSUE THREAD

**Issue by robjweiss** [jemise111/react-native-swipe-list-view#327]
I'm experiencing the same issue as #222. 

I need to individually manage the state of a component within my SwipeRow when it is being swiped. I have a component that returns a SwipeRow and the state is managed within that component.

However since I am returning this component in `renderItem` in my SwipeListView, the rows do not close when another row is opened.

Here's what it looks like:

**Row.js**
```
export default class Row extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      showRightBorder: false,
    };
  }


  // Display or remove right border
  onSwipeValueChange = (value) => {
    if (value < -1) { // Open
      this.setState({ showRightBorder: true });
    } else if (value > -1) { // Closed
      this.setState({ showRightBorder: false });
    }
  }


  render() {
    const { hiddenItemContainer } = styles;
    const { item } = this.props;
    const { showRightBorder } = this.state;

    return (
      <SwipeRow
        rightOpenValue={-120}
        stopRightSwipe={-120}
        disableRightSwipe
        onSwipeValueChange={({ value }) => this.onSwipeValueChange(value)}
      >
        <HiddenItem />
        <visibleItem
          showRightBorder={showRightBorder}
        />
      </SwipeRow>
    );
  }
}
```

**List.js**
```
export default class List extends React.Component {
  render() {
    return (
        <SwipeListView
          data={data}
          renderItem={({ item }) => (
            <Row item={item} />
          )}
        />
    );
  }
}
```

I tried the following, but I could not get it to work:

> Working (for me) example to use SwipeRow, not as a top level component: 
> ```
> class YourComponent extends React.Component {
> 
>   //SwipeListView use references to close rows.
>   //For now passing reference to child component causes problems, so closeRow function is passed to child component.
>   setRef = (ref) => {
>     this.rowRef = ref
>   }
> 
>   closeRow = () => {
>     this.rowRef.closeRow()
>   }
> 
>   render(){
>     return(
>       <SwipeRow
>         ref={this.setRef}
>       >
>         {swipeRowBody}
>       </SwipeRow>
>     )
>   }
> }
> ```
> 
> Each object in data has a unique key.
> 
> 
> I tried to use [Forwarding Refs](https://reactjs.org/docs/forwarding-refs.html) but SwipeRow was wrong displayed.

_Originally posted by @maniloo in https://github.com/jemise111/react-native-swipe-list-view/issues/222#issuecomment-450621667_

**Comment by bockc** [comment]
I have the exact same issue, I am using a keyExtractor so every row should have a unique key. However props like `closeOnScroll` or `closeOnRowOpen` don't work.

**Comment by jemise111** [comment]
Hey @robjweiss @bockc the most important thing for the `closeOnScroll` or `closeOnRowOpen` props to work correctly is the use of unique `key`s for each row. You either need to pass a `keyExtractor` to the `SwipeListView` or include a `key` with every object in your `data`.

It doesn't matter if you're using individual `SwipeRow`s or not. You can see an example of that in action here:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L163 (make sure you look at `this.state.listViewData`

If you're still having problems please give me an example of the `data` you're using and I can try to reproduce. Thanks!

**Comment by bockc** [comment]
I am using a custom component for my list, here's how I use it with your list component:
```
<SwipeListView
        data={this.props.conversations}
        closeOnScroll
        closeOnRowOpen
        renderListView={() => (
          <EListView
            component={ConversationTeaser}
            data={this.props.conversations}
            error={this.props.error}
            isFull={this.props.isFull}
            isLoadingMore={this.props.status === 'requesting' && this.props.offset > 0}
            isRefreshing={
              this.props.conversations.length > 0 &&
              this.props.namesStatus === 'requesting' &&
              this.props.offset === 0
            }
            itemProps={{ updateConversationMessage: this.updateConversationMessage }}
            loadingPlaceholder="chatRoster"
            onEndReached={this.onEndReached}
            onRefresh={this.onRefresh}
            status={this.props.status}
            testID="eventsList"
          />
        )}
      />
```

Inside my component, here's what the render function returns:
```
<View ref={this.props.generateTestHook(`${this.props.testRef}.success`)} style={{ flex: 1 }}>
        <ListComponent
          {...this.listViewProps}
          onEndReached={this.props.isFull ? null : this.listViewProps.onEndReached}
          testID={this.props.testID}
          data={this.props.groupRowsBy ? undefined : this.props.data}
          sections={this.props.groupRowsBy ? this.props.data : undefined}
          keyExtractor={this.keyExtractor}
          removeClippedSubviews={false}
          renderItem={this.renderItem}
          keyboardShouldPersistTaps="handled"
        />
        {this.props.bottomMargin !== 0 && (
          <View style={{ height: this.props.bottomMargin, width: 1 }} />
        )}
      </View>
```

With `renderItem` being:
```
renderItem = ({ item, index }) => {
    const ItemComponent = this.props.component;
    return <ItemComponent rowID={index} key={index} {...this.props.itemProps} data={item} />;
  };
```

I told you I don't think this problem is caused by wrong keys, as you can see in the `renderItem` function, which returns a `<SwipeRow>`. I checked myself by logging the data, every key is different, I even tried to manually pass it everywhere until getting to the `<SwipeRow>`, it still does not work. React-native does not give me the warning that my components don't have unique keys, so I really think the problem does not come from here.

Maybe with the code I posted you will be able to pinpoint the issue, otherwise I will post a data example so you can check deeper.

Thanks for your help :)

**Comment by robert-narrate** [comment]
I too am running into a similar issue, If I use something similar to:
```
<SwipeRow>
    <View style={hiddenRowStyle} />
    <View style={visibleRowStyle} />
</SwipeRow>
```

setting:
```
closeOnRowBeginSwipe
closeOnRowPress
closeOnRowOpen
closeOnScroll
```

on SwipeListView does nothing

**Comment by jemise111** [comment]
Hey guys using a custom list view was a community addition to this library so I'm not 100% familiar with how it should work. If you are using a standard Flatlist with custom SwipeRows I can assure you this works as intended. If you are using a custom list view (perhaps a third party list view library) please provide a fully reproducible example and I'd be happy to try to figure out what's going on @robert-narrate

**Comment by jemise111** [comment]
Closing as inactive
