### ISSUE TITLE
Delete the first line problem

### ISSUE THREAD

**Issue by stoneWeb** [jemise111/react-native-swipe-list-view#334]
There is a problem with swap the first row to delete, which continuously triggers `onSwipeValueChange`

```
onSwipeValueChange = (swipeData) => {
    const { key, value, direction } = swipeData;
    console.log(key);
    if (direction === 'right' && value < -width && !this.animationIsRunning) {
        this.animationIsRunning = true;
        Animated.timing(this.rowTranslateAnimatedValues[key], { toValue: 0, duration: 200 }).start(() => {
            const newData = [...this.state.tasks];
            const prevIndex = this.state.tasks.findIndex(item => item.key === key);
            if (prevIndex > -1) {
              newData.splice(prevIndex, 1);
              this.setState({tasks: newData});
            }
            this.animationIsRunning = false;
        });
    }
  }
```

![git](https://user-images.githubusercontent.com/4115730/63414349-39df8380-c42e-11e9-929f-cb209d3e172d.gif)

**Comment by jemise111** [comment]
Hey @stoneWeb I cannot reproduce your issue, I'm really not sure what's going on. But clearly your `onSwipeValueChange` function is being called with the wrong key. Perhaps you could try keeping track of the key of the row you're deleting and don't let the animation run if it's being called with the wrong key?

I might be able to help more if you post more \code, or better yet a fully reproducible example :)

**Comment by jemise111** [comment]
Closing as inactive
