### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this._pandResponder.panHandlers')

### ISSUE THREAD

**Issue by codenaz** [jemise111/react-native-swipe-list-view#335]
![Screenshot_1566558777](https://user-images.githubusercontent.com/19376441/63588879-78e11680-c59f-11e9-90e3-c5d733129511.png)
This error shows up whenever I navigate to the screen where this component is rendered.

```jsx
<FlatList
          removeClippedSubviews={true}
          scrollEventThrottle={16}
          data={this.state.list}
          keyExtractor={(item, index) => index.toString()}
          renderItem={({ item, index }) => (
            <SwipeRow
              key={item.id}
              rightOpenValue={-75}
              disableRightSwipe
              body={
                <View >
                  <Text >{item.name}</Text>
                  <Text >{item.number}</Text>
                </View>
              }
              right={
                <TouchableOpacity
                  onPress={() => this.toggleModal(item, index)}
                >
                  <Image source={trash} />
                </TouchableOpacity>
              }
            />
          )}
        />
```

**Comment by jemise111** [comment]
Hey @codenaz it doesn't look like you're using the correct props for SwipeRow. Please refer to this part of the example:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L166

**Comment by codenaz** [comment]
This issue was a result of my index.android.bundle file being outdated updated, I fixed it by deleting and regenerating that file. Not an issue with this package
