### ISSUE TITLE
Section list item swipe not following touch

### ISSUE THREAD

**Issue by benjamarle** [jemise111/react-native-swipe-list-view#337]
I am having a strange issue with Section Lists on Android (tested on emulator Android 7.0, and device on Android 9.0)

It happens on the sample app as well and you just have to swipe right and keep doing it several time on the open item. You will see that the item is moving further and further away from the touch position to the point which you just have to click to see it disappear.

It does not happen with flat lists.

![untitled](https://user-images.githubusercontent.com/18249796/63703312-ba1f3380-c7f6-11e9-817d-6d90d78f4e97.gif)

**Comment by proof666** [comment]
I have the same issue. Also it can be reproduced by `swipe element => close => swipe same element`.
