### ISSUE TITLE
react-native-swipe-list-view  flatlistView demo

### ISSUE THREAD

**Issue by Mscynol** [jemise111/react-native-swipe-list-view#341]
can anyone gave one demo , use the flatlistView demo with react-native-swipe-list-view

**Comment by jemise111** [comment]
@Mscynol I'm not sure I understand the issue?

Here is the example with FlatList + RNSLV https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L108

Hope that helps!

**Comment by Mscynol** [comment]
thanks!!!
