### ISSUE TITLE
Performance issue with Touchables on large lists

### ISSUE THREAD

**Issue by outaTiME** [jemise111/react-native-swipe-list-view#342]
Hi @jemise111, 
A few days ago I started using this library and I found a potential performance issue with touchables, I'm using a large flat list (also with high level of uptates too) and the following method generates a large number of re-renders:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L338

For the moment my alternative to solve this problem was to use a function with another name (instead of `onPress`) on the topmost Touchable element from `renderItem`.

I think it would be very useful that when using the `closeOnRowPress` attribute in `false` on `SwipeListView` don't capture the `onPress` touchables.

Also the wrapper function that captures the `onPress` from touchable should be generated only once instead of in each update:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L334

Sorry but I don't have much time to generate a PR with this fixes, but I leave my code for the community.

```js
class RowItem extends React.PureComponent {
  _onPress = () => {
    const { onDevicePress, id } = this.props;
    onDevicePress(id);
  };
  render() {
    return (
      <TouchableWithoutFeedback onPress={this._onPress}>
        {/* content */}
      </TouchableWithoutFeedback>
    );
  }
}

class QuickActions extends React.PureComponent {
  _onPress = () => {
    const { onPress, id } = this.props;
    onPress(id);
  };
  render() {
    return (
      <View style={styles.actionsContainer}>
        <Touchable style={styles.actionButton} onPress={this._onPress}>
          {/* content */}
        </Touchable>
      </View>
    );
  }
}

class HomeScreen extends React.PureComponent {
  constructor(props) {
    super(props);
    this._listRef = React.createRef();
  }
  _keyExtractor = (item, _index) => item.id;
  _showDetail = id => {
    // manual close of swipeable
    this._listRef.current.safeCloseOpenRow();
    // actions here
  };
  _renderItem = ({ item }) => (
    <RowItem
      id={item.id}
      // onPress={this._showDetail}
      onDevicePress={this._showDetail}
    />
  );
  _onPressActionRow = id => {
    // manual close of swipeable
    this._listRef.current.safeCloseOpenRow();
    // actions here
  };
  _renderQuickActions = ({ item }) => (
    <QuickActions id={item.id} onPress={this._onPressActionRow} />
  );
  render() {
    // filtered_list comes from redux 
    return (
      <SwipeListView
        listRef={this._listRef}
        data={filtered_list}
        keyExtractor={this._keyExtractor}
        renderItem={this._renderItem}
        disableRightSwipe
        renderHiddenItem={this._renderQuickActions}
        rightOpenValue={-88}
      />
    );
  }
}
```

**Comment by jemise111** [comment]
Hey @outaTiME great ideas! Created a PR to address your suggestions, #350. Feel free to try it out in the next release and reopen this if you have other issues, thanks!
