### ISSUE TITLE
ListView issue for RN 0.60.5

### ISSUE THREAD

**Issue by rsokz** [jemise111/react-native-swipe-list-view#344]
I'm noticing that ListView is still referenced in`test.tsx` inside the types folder.

![Screen Shot 2019-09-19 at 12 58 02 PM](https://user-images.githubusercontent.com/6425523/65276729-3eef2b80-dadd-11e9-9677-8deccf0e1a5d.png)

This is the only module in my app that has this reference. Could it be causing the issue?

**Comment by jemise111** [comment]
Good call @rsokz, that file should have been removed, fixed in #351
