### ISSUE TITLE
Auto close swiped row

### ISSUE THREAD

**Issue by MOHAMMADArsalan** [jemise111/react-native-swipe-list-view#347]
Hello! First of all, thank you so much for such a library. Great job.

I need a functionality auto close swiped row after some time. but unfortunately, I did not get any option in documentation.

**Comment by riguy14** [comment]
Would setting a setTimeout on the row opening work for you?
`
onRowOpen={(secId, rowId, rowMap) => {
        setTimeout(() => {
            rowMap[`${secId}${rowId}`].closeRow()
        }, 2000)
    }}
`

Got the idea the docs here https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/migrating-to-flatlist.md. There's a regular example and one for when using a FlatList.

**Comment by jemise111** [comment]
Hey @MOHAMMADArsalan, @riguy14 is right, that's exactly how I'd suggest doing it. If that doesn't work for you please let me know some more specifics around what you're trying to achieve and I can help more, thanks!

**Comment by kampretosjr** [comment]
hey @jemise111 i have bug with this issue ,i open the row and try to go to previous screen ,there is an error  "TypeError: Cannot  read Property 'closeRow' of null, js engine: hernes"

**Comment by jemise111** [comment]
Hey @kampretosjr I'd need to see some code to help figure out what's going on, thanks!

**Comment by pop-thanit** [comment]
> Hey @MOHAMMADArsalan, @riguy14 is right, that's exactly how I'd suggest doing it. If that doesn't work for you please let me know some more specifics around what you're trying to achieve and I can help more, thanks!

How to auto close when using standalone_row ?

**Comment by pop-thanit** [comment]
> Hey @MOHAMMADArsalan, @riguy14 is right, that's exactly how I'd suggest doing it. If that doesn't work for you please let me know some more specifics around what you're trying to achieve and I can help more, thanks!

How to auto close when using standalone_row ?  
I didn't use <SwipeListView> so i can not use this 

onRowOpen={(rowKey, rowMap) => {
        setTimeout(() => {
            rowMap[rowKey].closeRow()
        }, 2000)
    }}

Is there any other way to do that ? 

<SwipeRow leftOpenValue={75} rightOpenValue={-75}>
                    <View style={styles.standaloneRowBack}>
                        <Text>Left</Text>
                        <Text>Right</Text>
                    </View>
                    <View style={styles.standaloneRowFront}>
                        <Text>I am standalone SwipeRow #1</Text>
                    </View>
</SwipeRow>
