### ISSUE TITLE
[feature]: add `flatListProps` or similar

### ISSUE THREAD

**Issue by wkoutre** [jemise111/react-native-swipe-list-view#348]
I've recently run into the need to pass in the `extraData` prop to a RNSLV-driven (with FlatList) component.

It'd be nice if the `SwipeListView` component took in something like `flatListProps?: Partial<FlatListProps<any>>` and spread them, in `render` (not `this.listViewProps`) accordingly.

Update: made a [quick PR](https://github.com/jemise111/react-native-swipe-list-view/pull/349)

**Comment by jemise111** [comment]
Hey @wkoutre I'll look at your PR as well but I think this is already being done here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L245

You can either pass `listViewProps` or just additional `props` to a `<SwipeListView />` component and they will be passed to the underlying `FlatList`

**Comment by wkoutre** [comment]
Hm, well I think it’s just the latter (passing additional props) that’s the valid option. `listViewProps` is a class variable (line 23).

I stumbled upon this trying to pass `extraData` but it didn’t respond as expected. I’ll double check myself, though, before cleaning up that PR.

**Comment by wkoutre** [comment]
Yeah, not sure what I was thinking/looking at earlier! But any extra props are, indeed, already being spread to whichever List component is being used. Closing.
