### ISSUE TITLE
Missing `useNativeDriver` type def

### ISSUE THREAD

**Issue by karlmarxlopez** [jemise111/react-native-swipe-list-view#354]
**Describe the bug**
Missing `useNativeDriver` on TS type definition.  I can submit a PR for this.

**To Reproduce**
`<SwipeListView useNativeDriver /> // TS throws an error` 

**Screenshots**
`n/a`

**Comment by jemise111** [comment]
@karlmarxlopez PR would be great if you could, thanks!

**Comment by jemise111** [comment]
Closing as inactive
