### ISSUE TITLE
Get index of data in new flatlist version

### ISSUE THREAD

**Issue by anjucheran** [jemise111/react-native-swipe-list-view#355]
When rendering a row, I need to know how to identify the index of the item in the data array. Is there a way to get it?

previously it was rowId

`renderRow={ (data, secId, rowId) => {
    return()
}}`

**Comment by jemise111** [comment]
Hey @anjucheran you can use this

```
renderItem={(data, rowMap) => {
    console.log(`This is the index: ${data.index}`)
}}
```

Hope that helps!

**Comment by ilibilibom** [comment]
Hi 
data.index is returning 0 for all items: 
```
<SwipeListView
            data={userRequests}
            renderItem={(data, rowMap) => (
              <View style={styles.rowFront}>
                {console.log(data.index)}
```
