### ISSUE TITLE
scroll to top when tapping on the active tab

### ISSUE THREAD

**Issue by Helongzhou** [jemise111/react-native-swipe-list-view#356]
> React Navigation exports its own ScrollView, FlatList, and SectionList. The built-in components are wrapped in order to respond to events from navigation that will scroll to top when tapping on the active tab as you would expect from native tab bars.
[https://reactnavigation.org/docs/en/scrollables.html](url)

**Comment by jemise111** [comment]
Hey @Helongzhou. Not exactly sure what you're question is but if you're looking to use your own List component with swipeable rows you can either use a standalone `<SwipeRow />` or you can pass your own list component. See the prop `renderListView` here https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeListView.md

**Comment by Hirbod** [comment]
This is actually easy. Register a NavigationEvent, set a ref to your ScrollView/Flatlist (lets call it this.scroll) and trigger
```
this.scroll.current.getNode().scrollTo()....
```

**Comment by jemise111** [comment]
Closing as inactive / there are a few solutions here. Thanks!
