### ISSUE TITLE
Opening SwipeRow programatically 

### ISSUE THREAD

**Issue by ochrostowska** [jemise111/react-native-swipe-list-view#361]
Hello! 

I wanted to know if there is a way for opening the SwipeRow programatically. I need to manually adjust leftOpenValue and rightOpenValue, because my hidden content width is dynamically changing. Once I open the row with leftOpenValue=100 and rightOpenValue=-100 it doesn't seem to be possible to swipe it back to leftOpenValue=50 and rightOpenValue=-50.
I am able to close row programatically, as SwipeRow gives me the closeRow method:

```
export class SwipeRow<T> extends Component<Partial<IPropsSwipeRow<T>>> {
	closeRow: () => void;
	closeRowWithoutAnimation: () => void;
	render(): JSX.Element;
} 
```
But that's not exactly what I'm looking for. I don't need to close it, just slide an opened row from 100 to 50. 
Is there any way to do this? :)

Here is a vid that may give a notion of my problem: 
![swipe_issue](https://user-images.githubusercontent.com/15039955/67103847-35351280-f1c6-11e9-9daa-f74d4bce0677.gif)

I am using only SwipeRow, not the SwipeListView :)
Thank you very much for your incredible work :) It works smoooooth like butter :) :) :)

**Comment by jemise111** [comment]
Hey @ochrostowska this is a bit untested but instead of using `swipeRow.closeRow()` try using `swipeRow.manuallySwipeRow(value)` in your case I think something like `swipeRow.manuallySwipeRow(-50)`

LMK if that works for you

**Comment by ochrostowska** [comment]
I've read your answer in previous issues mentioning manuallySwipeRow  function, but I dont have   available for SwipeRow... Do I have some deprecated dependency? It seems I can call only declared functions: 

```
export class SwipeRow<T> extends Component<Partial<IPropsSwipeRow<T>>> {
	closeRow: () => void;
	closeRowWithoutAnimation: () => void;
	render(): JSX.Element;
} 
```

These are the suggestions IDE is giving me: 
![Screenshot 2019-10-21 at 10 36 19](https://user-images.githubusercontent.com/15039955/67189766-1a91b200-f3ef-11e9-9ccf-5161faf40906.png)
![Screenshot 2019-10-21 at 10 36 26](https://user-images.githubusercontent.com/15039955/67189770-1d8ca280-f3ef-11e9-9096-bd44b7f1e7f2.png)

`manuallySwipeRow(value)` cannot be found: 
![Screenshot 2019-10-21 at 10 39 17](https://user-images.githubusercontent.com/15039955/67189793-29786480-f3ef-11e9-9e81-f66d2a64ba13.png)
current is `SwipeRow` reference
![Screenshot 2019-10-21 at 10 39 29](https://user-images.githubusercontent.com/15039955/67189798-2bdabe80-f3ef-11e9-8cce-09582526d713.png)

**Comment by jemise111** [comment]
Hey @ochrostowska sorry for the delay. I think the IDE is complaining because it is using the types from `types/index.d.ts` which was an open source contribution that doesn't have `manuallySwipeRow` function declared in it. I'm hesitant to add it to `types` because it's not really supported functionality (though a PR is always welcome if you'd like to add it)

But I have tested using `manuallySwipeRow` in my own code. As long as you have a valid `ref` to the `SwipeRow` it should work :)

Were you able to give it a try?

**Comment by arghyaExicube** [comment]
It is working when js debugger is enabled, but in release build the process hanged and app is not responding.Any idea why?

**Comment by jemise111** [comment]
Closing as I believe this was solved
