### ISSUE TITLE
Can I use SwipeRow without SwipeListView?

### ISSUE THREAD

**Issue by elioncho** [jemise111/react-native-swipe-list-view#366]
Hi,

I am trying to use the SwipeRow component inside a DraggableListView (see this https://github.com/computerjazz/react-native-draggable-flatlist). It is rendering correctly along with all the animations, but I have not been able to close the row. I tried to do exactly what was explained in issue https://github.com/jemise111/react-native-swipe-list-view/issues/151, but the closeRow() doesn't do anything. Here I copy parts of the code:

```
export default function ListDetailsScreen() {
...
..
  const rows = {};
..
...
// inside DraggableListView renderItem prop
<SwipeRow
  key={item.id}
  rightOpenValue={-75}      
  ref={ref => {
    rows[item.id] = ref
  }}
  >
  <View style={{...}}>
    <TouchableOpacity
      style={{...}}
      onPress={() => rows[item.id].closeRow()}
    >
      <Text>Delete</Text>
    </TouchableOpacity>
  </View>
  <ListItemComponent item={item}/>
</SwipeRow>
```

Any help is appreciated.

**Comment by jemise111** [comment]
Hey @elioncho I just double checked to confirm that this works in a standalone swipe row without a `SwipeListView`. Can you move your `rows` object to the constructor of the component. 

i.e.

```
constructor(props) {
  super(props);
  this.rows = {};
}

render() {
  ...
  <SwipeRow ref={ref => this.rows[item.id] = ref}>
    ...
    onPress={() => this.rows[item.id].closeRow()}
```

LMK if that helps

**Comment by elioncho** [comment]
Thanks for the response. I am using a functional component so I don't have a constructor method. Can this be a problem? I tried again and added a couple of logs just to see what's going on. The swipe shows, but when I click on the action it just scrolls back.

```
            onPress={() => {
              console.log(Object.keys(rows)); // returns the item ids correctly
              console.log(item.id); // returns the id correctly
              console.log(rows[item.id]); // returrns the SwipeRow object
              console.log(rows[item.id].closeRow()); // returns undefined
              rows[item.id].closeRow(); // 
            }}
```

**Comment by jemise111** [comment]
@elioncho Well `closeRow()` doesn't return anything so it makes sense that it would return undefined.

At this point I'm not sure what's going on. You could try debugging further by putting some breakpoints in the source code for rnslv. Maybe start by putting a breakpoint here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L336

And making sure it's hitting inside there and properly doing the closeRow animation

**Comment by elioncho** [comment]
It was a mistake from my part. It is working correctly. Thanks and sorry for the inconvenience.

**Comment by JayM96** [comment]
@elioncho can you please tell me how you managed it? because i also getting the undefined values.

Thanks.
