### ISSUE TITLE
scrollToLocation is not a function.

### ISSUE THREAD

**Issue by sagargondaliya** [jemise111/react-native-swipe-list-view#368]
**Describe the bug**
I am trying to implement scroll to top function on tap of button to scroll on top position of swipe list view and trying to access method `scrollToLocation` from SectionList but I am not able to access it using the reference of SwipeListView. So I need help how to achieve it.Below is code from `render` function.

```
<SwipeListView
                        useSectionList={true}
                        sections={this.state.data}
                        keyExtractor={(item, section) => item.key }
                        renderItem={this.renderRow}
                        renderHiddenItem={this.renderHiddenItems}
                        renderSectionHeader={this.renderSectionHeader}
                        rightOpenValue={-75}
                        stopRightSwipe={-75}
                        previewRowKey={'0'}
                        closeOnRowPress={true}
                        previewOpenValue={-40}
                        onRowDidOpen={this.onRowDidOpen}
                        stickySectionHeadersEnabled={false}
                        bounces
                        disableRightSwipe={true}
                        enableEmptySections={false}
                        tension={20}
                        scrollsToTop={true}
                        onEndReachedThreshold={0.99}
                        onEndReached={() => {
                          this.setState({ isScrollToTopVisible: !this.state.isScrollToTopVisible })
                        }}
                        ref={(ref) => this.sectionListRef = ref }
        />
```
Code for scroll to top of list.

```
scrollToTop() {
   this.sectionListRef.scrollToLocation({ offset : 0, animated : true })
}
```

**To Reproduce**

1. Scroll to bottom of SwipeList View.
2. Tap on button at bottom of screen to perform scrollToTop.

**Environment (please complete the following information):**
 - OS: [iOS 12.1]
 - RNSLV Version: [v2.0.3]
 - RN Version: [v0.59.8]

**Comment by sagargondaliya** [comment]
I have made mistake for identify reference. Here is proper way to do it.

Replace 
`ref={(ref) => this.sectionListRef = ref }`
with
`listViewRef ={ ref => this.sectionListRef = ref }`

And then, `scrollToLocation` works fine.

```
scrollToTop() {
   this.sectionListRef.scrollToLocation({
            animated: true,
            itemIndex: 0,
            sectionIndex: 0,
            viewOffset: 0,
        });
}
```
https://stackoverflow.com/questions/58704814/scrolltolocatoin-is-not-a-function-react-native-swipe-list-view

**Comment by fontenele** [comment]
The only function that exists at listViewRef is scrollToEnd()
