### ISSUE TITLE
SwipeRow height

### ISSUE THREAD

**Issue by baicuhaha** [jemise111/react-native-swipe-list-view#377]
![05418A4F-7390-4550-B720-989FF8930AB8](https://user-images.githubusercontent.com/20334376/69607858-23fee180-1061-11ea-9473-0514288f7f3f.png)
![BFEE7EA7-9C19-4E76-92AB-570E29BC9CAF](https://user-images.githubusercontent.com/20334376/69608194-dafb5d00-1061-11ea-9bfd-b0dd70de43f6.png)
![77277BAD-3C30-41A8-8596-E7DD5ED868E0](https://user-images.githubusercontent.com/20334376/69608199-de8ee400-1061-11ea-8ff9-c181a183364f.png)

When I updated the 2 component because the height was dynamic, after I refreshed the view, the 1 component was not at the same height as it was the first time

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android] ：ios
 - RNSLV Version: [e.g. v2.0.2]:2.0.6
 - RN Version: [e.g. v60.0.5]:0.61.2
![FE96D2B1-DD74-4D2D-A407-52FF44795EF7](https://user-images.githubusercontent.com/20334376/69608068-8f48b380-1061-11ea-9284-762061358c65.png)
![ADE1F5DC-ED00-4349-A0F6-93FFFC845E45](https://user-images.githubusercontent.com/20334376/69608089-97a0ee80-1061-11ea-9eb0-8fea51841375.png)

**Comment by jonnynfb** [comment]
I have the same issue. Have you found the solution?

**Comment by jemise111** [comment]
Hey @baicuhaha @jonnynfb try adding `recalculateHiddenLayout={true}` as a prop to your `SwipeRow`. Let me know if that works, thanks!

**Comment by baicuhaha** [comment]
@jemise111 I've solved my problem. Thank you

**Comment by baicuhaha** [comment]
@jonnynfb Using this recalculateHiddenLayout can be solved

**Comment by jonnynfb** [comment]
@jemise111 @baicuhaha Thank guys! That fixed it for me.

**Comment by kopax** [comment]
I have tried to set `rowFront.height to 90` after settings `recalculateHiddenLayout` on `SwipeListView`, this is my code:
```jsx
        renderItem={data => (
          <Animated.View
            style={{
              height: this.rowTranslateAnimatedValues[data.item.key].interpolate({
                inputRange: [0, 1],
                outputRange: [0, 50],
              }),
            }}
          >
            <TouchableRipple
              onPress={() => console.log('You touched me')}
              style={styles.rowFront}
              underlayColor={'#AAA'}
            >
              <View>
                <Text>
                  {data.item.description}
                </Text>
              </View>
            </TouchableRipple>
          </Animated.View>
        )}
```

and my view looks like this:


![image](https://user-images.githubusercontent.com/1866564/74132839-ea7a5300-4c19-11ea-91ba-811c2deb23e3.png)

How do you set the height to be dynamic?

**Comment by pravinsphinx** [comment]
@jemise111 recalculateHiddenLayout={true} is solved problem. But it's visible for moment if row height is different.
