### ISSUE TITLE
closeOnRowOpen inoperative

### ISSUE THREAD

**Issue by luobao1207** [jemise111/react-native-swipe-list-view#378]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android]
 - RNSLV Version: [e.g. v2.0.2]
 - RN Version: [e.g. v60.0.5]

**Comment by jemise111** [comment]
Hi @luobao1207, 9 out of 10 times if `closeOnRowOpen` doesn't work it is an issue with your data's `key`s or `keyExtractor`. Please double check these. If the issue persists can you show me some example code so I can take a look at the problem? Thanks

**Comment by densk1** [comment]
Was trying to debug this for a while.

**Comment by dayaki** [comment]
Yes, I can confirm ``keyExtractor`` prop is the culprit. Adding it to mine solved this issue for me.

**Comment by jemise111** [comment]
Closing as inactive
