### ISSUE TITLE
Preview Repeat

### ISSUE THREAD

**Issue by phyzical** [jemise111/react-native-swipe-list-view#379]
Hey there!

i thought id ask incase im just blind but is there currently functionality to repeat the preview animation? if not i spent literally 30 seconds and found i can do the following to force a loop

```
getPreviewAnimation(toValue, delay) {
        return Animated.loop(Animated.timing(this._translateX, {
            duration: this.props.previewDuration,
            toValue,
            delay,
            useNativeDriver: this.props.useNativeDriver,
        }));
    }
```

i can make a pr to integrate this with a bool prop of say "repeatPreview". but my current usage is extremely basic. on preview should the open/close event fire ect? or is preview just a visual effect of the open close (if so the pr should be quite straight forward i think).  Also let me know if you think there would be a more appropriate place to place the loop call.

Let me know and i will tackle this to save me need to fork it for my own usage :D (and you the time to implement)

Thanks!

Edit: hmm having leaving this in places for a while i did notice it seems to cause Somme heavy performance issue though, maybe there is a better way to execute the loop of the animation?  any idea why this would cause such a performance hit?

**Comment by phyzical** [comment]
i also noticed i was only repeating half the animation so potential implementation would look something like this

```

    onContentLayout(e) {
        this.setState({
            dimensionsSet: !this.props.recalculateHiddenLayout,
            ...(!this.props.disableHiddenLayoutCalculation
                ? {
                      hiddenHeight: e.nativeEvent.layout.height,
                      hiddenWidth: e.nativeEvent.layout.width,
                  }
                : {}),
        });

        if (this.props.preview && !this.ranPreview) {
            this.ranPreview = true;
            const previewOpenValue =
                this.props.previewOpenValue || this.props.rightOpenValue * 0.5;
            this.props.repeatPreview ? setInterval(() => {doFullAnimation()},this.props.previewDuration * 2.5) : doFullAnimation();
        }
    }

    doFullAnimation() {
        return this.getPreviewAnimation(
            previewOpenValue,
            this.props.previewOpenDelay
        ).start(() => {
            this.getPreviewAnimation(0, PREVIEW_CLOSE_DELAY).start();
        })
    }
```

**Comment by jemise111** [comment]
Hey @phyzical PR's are always welcome :)

I think what you have in your second comment looks good, do you have a way of stoping the repeated preview animations?

I'd also add another prop to set the preview interval time instead of hardcoding to `this.props.previewDuration * 2.5`.

Otherwise put in a PR and I'll have a look, thanks!

**Comment by phyzical** [comment]
sweet ill send the pr your way in the next few days when i get a chance, will do in regards to adding a prop for the 'previewRepeatInterval' or How about 'previewRepeatDelay' `(this.props.previewDuration * 2.5) + this.props.previewRepeatDelay` that way its more obvious it will be the time between each finished animation and wont require updating both props when changing duration

> do you have a way of stoping the repeated preview animations?

What do you mean by this? when the component is mounted and the component isnt destroyed? i.e progressing in a stack?

if so hmmm ill implement this once the pr is done and test a console.log to see if it keeps firing i suppose it would. off the top of my head i cant think of anything to bind to detect the component isnt visible to stop animating until it comes back (.. i mean i can but its specific to dependencies i.e navigate events so thats a no go)

if not ill wait for your reply haha

**Comment by jemise111** [comment]
Hey @phyzical no no I don't think you need to handle the case you described.

I was just envisioning a scenario where maybe you'd want the preview animation to continue opening and closing and opening and closing until the user swiped a row, at which point you might want the loop to stop.

I thought maybe we'd want to run a `clearInterval` if a certain prop is set. Or maybe if repeatPreview is set to `false` from `true`. Just some thoughts.. I'm open to either way

**Comment by phyzical** [comment]
ah yes ofc. my current use case it a literal preview window :D but that will be needed now that you mention it for other cases. 

i think we could keep it simpler and call `clearInterval ` in `onRowPress ` on `SwipeRow`

**Comment by jemise111** [comment]
Yeah I mean I lean towards my way because it allows the dev to decide which events trigger the loop to stop. onRowPress vs onRowSwipe vs onRowOpen vs (like you said) a dialog with a confirm button or anything else.

But I'll leave the final decision up to you :)

**Comment by phyzical** [comment]
hey man,

pr submitted. one thing i noticed is that on re-render, as in when saving and the code reloads another setInterval is called. i couldnt think of a good way to avoid duplicating this but i didnt notice any issues caused by it so i think itll be okay.
https://github.com/jemise111/react-native-swipe-list-view/pull/380

let me know if there is anything else you suggest should be changed

thanks!

**Comment by jemise111** [comment]
@phyzical left some comments on the PR! Let's continue any discussion over there, I'm going to close this issue in the meantime
