### ISSUE TITLE
rowMap is empty on the first render

### ISSUE THREAD

**Issue by VitaliiK91** [jemise111/react-native-swipe-list-view#381]
**Describe the bug**
On the initial render of the component rowMap passed to renderHiddenItem and renderItem is an empty object. It almost seems that rowMap is async value and gets resolved afterwards.
If I try to log and inspect it in console it shows as:
![Screen Shot 2019-12-04 at 1 06 52 PM](https://user-images.githubusercontent.com/7388109/70181704-457e4f80-1697-11ea-849e-84cce9e6b8f6.png)
![Screen Shot 2019-12-04 at 1 07 21 PM](https://user-images.githubusercontent.com/7388109/70181711-4a430380-1697-11ea-9a6d-2aae81587516.png)
But after new data is passed to component (it fetches new data every N seconds), the rowMap is the expected object:
![Screen Shot 2019-12-04 at 1 07 43 PM](https://user-images.githubusercontent.com/7388109/70181777-6ba3ef80-1697-11ea-9535-cf9a193cc78b.png)

Here is a little snippet of the component:
```js
<SwipeListView
      style={styles.container}
      keyExtractor={item => item.System_Notifications_ID.toString()}
      data={searchActive ? data : data.filter(i => !i.hidden
        && i.System_Notifications_Status !== statusTypes.DISMISSED)}
      renderItem={renderItem}
      renderHiddenItem={({ item }, rowMap) => {
        console.log(rowMap);
        const row = rowMap[item.System_Notifications_ID.toString()];
        const closeAction = row && row.closeRow.bind(row);

        const newActions = actions.map((actionObj) => {
          const newItem = { ...actionObj };
          newItem.action = _.isFunction(actionObj.action)
            ? newItem.action.bind(null, item)
            : closeAction;
          return newItem;
        });
        return <HiddenItem actions={newActions} actionsStyle={actionsStyle} />;
      }}
      rightOpenValue={-width}
      disableRightSwipe
    />
```

 - OS: [iOS, haven't tested on Android]
 - RN Version: [e.g. v60.0.5]

**Comment by VitaliiK91** [comment]
I debugged it a bit and it appears that `ref={row => (this._rows[key] = row)` method of `<SwipeRow/>` is called after `renderHiddenItem` and `renderItem`, since they are called here:
```js
renderItem(rowData, rowMap) {
        const Component = this.props.renderItem(rowData, rowMap);
        const HiddenComponent =
            this.props.renderHiddenItem &&
            this.props.renderHiddenItem(rowData, rowMap);
        const { item, index } = rowData;
        let { key } = item;
        if (!key && this.props.keyExtractor) {
            key = this.props.keyExtractor(item, index);
        }

        const shouldPreviewRow =
            typeof key !== 'undefined' && this.props.previewRowKey === key;

        return this.renderCell(
            Component,
            HiddenComponent,
            key,
            item,
            shouldPreviewRow
        );
    }
``` 
so `rowMap` is not filled at the time of first render of items

**Comment by VitaliiK91** [comment]
Closing the issue as I found a solution. In case anyone runs in the problem. Don't create bound functions at the time of rendering (hidden)items. I added a function to my component:
```js
const closeRow = (key, map) => map[key] && map[key].closeRow();
```
and changed renderHiddenItem to:
```js
 renderHiddenItem={({ item }, rowMap) => {
          const closeAction = () => closeRow(item.System_Notifications_ID, rowMap);
          const newActions = actions.map((actionObj) => {
            const newItem = { ...actionObj };
            newItem.action = _.isFunction(actionObj.action)
              ? newItem.action.bind(null, item)
              : closeAction;
            return newItem;
          });
          return <HiddenItem actions={newActions} actionsStyle={actionsStyle} />;
        }}
```

**Comment by GuillaumeMunsch** [comment]
Worked for me ! Thanks.
For some reason the keys in my `rowMap` are like `1-undefined`, but eh, whatever, this still works
