### ISSUE TITLE
[TS] Definitions are out of date

### ISSUE THREAD

**Issue by ItsNoHax** [jemise111/react-native-swipe-list-view#382]
**Describe the bug**
When running the typescript compiler we get the following message:
```js
$ tsc
node_modules/react-native-swipe-list-view/types/index.d.ts:333:11 - error TS2320: Interface 'IUseSectionListProps<T>' cannot simultaneously extend types 'SectionListProps<T>' and 'IPropsSwipeListView<T>'.
  Named property 'renderItem' of types 'SectionListProps<T>' and 'IPropsSwipeListView<T>' are not identical.

333 interface IUseSectionListProps<T> extends SectionListProps<T>, IPropsSwipeListView<T> {
              ~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-swipe-list-view/types/index.d.ts:337:11 - error TS2320: Interface 'IUseFlatListProps<T>' cannot simultaneously extend types 'FlatListProps<T>' and 'IPropsSwipeListView<T>'.
  Named property 'renderItem' of types 'FlatListProps<T>' and 'IPropsSwipeListView<T>' are not identical.

337 interface IUseFlatListProps<T> extends FlatListProps<T>, IPropsSwipeListView<T> {
              ~~~~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
Run the typescript compiler when using SwipeListView

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: All
 - RNSLV Version: 2.0.6
 - RN Version: 0.60.5

**Comment by jemise111** [comment]
@ItsNoHax My typescript knowledge is limited at best.

Seems the issue here is that SwipeListView props are identical to FlatList or SectionList props with one exception, the signature of `renderItem`

I did some quick research and _I think_ I fixed it. Can you (or anyone else) please have a look?

https://github.com/jemise111/react-native-swipe-list-view/pull/384

Thank!

**Comment by ItsNoHax** [comment]
Great, fixed with the newest release! Thanks for picking it up on such a short notice @jemise111
