### ISSUE TITLE
Is there a way to disable the swiper on an item ?  

### ISSUE THREAD

**Issue by ilibilibom** [jemise111/react-native-swipe-list-view#383]
Hi 
I'm rendering a list of users, and I want the option to disable swiping on a list item - if a user is an admin.
Is there a way to tell  SwipeListView to do that?

**Comment by Dag0n** [comment]
You can, however you'll need to use SwipeRow.

` <SwipeRow`
`            disableRightSwipe={parseInt(rowId) % 2 !== 0}`
`            disableLeftSwipe={parseInt(rowId) % 2 === 0}`
`            leftOpenValue={20 + parseInt(rowId) * 5}`
`            rightOpenValue={-150}`
`        >`

Example [here](https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/per-row-behavior.md)

**Comment by ilibilibom** [comment]
I'm using the example in the link you sent: 
```
<SwipeListView
        dataSource={dataSource.cloneWithRows(data)}
        renderItem={(rowData, rowMap) => (
          <SwipeRow
            disableRightSwipe={parseInt(rowId) % 2 !== 0}
            disableLeftSwipe={parseInt(rowId) % 2 === 0}
            leftOpenValue={20 + parseInt(rowId) * 5}
            rightOpenValue={-150}>
            <View style={styles.rowBack}>
              <Text>Left Hidden</Text>
              <Text>Right Hidden</Text>
            </View>
            <View style={styles.rowFront}>
              <Text>Row front | {data.item.key}</Text>
            </View>
          </SwipeRow>
```
I'm getting data is not defined. 
What should ```data``` be ?

**Comment by jemise111** [comment]
Hi @ilibilibom, like @Dag0n said you'll have to customize the rows to configure each one to be either swipeable or not depending on your `admin` condition. You can see all examples here:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/per-row-behavior.md

The guide is a little out of date (I'll try to update today). Don't pay attention to dataSource. You can use the `data` prop as you would normally. Just be sure to return a `<SwipeRow />` for `renderItem` and configure it how you like

Please reopen if you still have problems

**Comment by ilibilibom** [comment]
@jemise111 - this is still not working for me. 
I have 2 issues now: 

this is my code: 
```
<SwipeListView
            data={groupUsers}
            renderItem={(user, rowMap) => (
              <SwipeRow
                disableRightSwipe={true}
                disableLeftSwipe={true}
                // leftOpenValue={20 + parseInt(user.item.key) * 5}
                // rightOpenValue={-150}
              >
                {/* {console.log('user', user)} */}
                <View style={styles.rowFront}>
                  <View
                    style={[
                      styles.groupItem,
                      !isLastElement(groupUsers, user.index)
                        ? styles.borders
                        : null,
                    ]}>
                    <View style={styles.groupData}>
                      <View style={{width: 60}}>
                        <Avatar.Image
                          style={styles.groupActionIcon}
                          size={50}
                          source={
                            isSet(user.item) && user.item.profileImage
                              ? {
                                  uri: user.item.profileImage,
                                }
                              : require('./../../public/images/default-group-sm.png')
                          }
                        />
                      </View>
                      <View style={{justifyContent: 'center'}}>
                        <Text style={styles.groupTitle}>
                          {user.item.displayName}
                        </Text>
                      </View>
                    </View>
                  </View>
                </View>
              </SwipeRow>
            )}
            renderHiddenItem={(user, rowMap) => (
              <View
                style={[
                  styles.rowBack,
                  {
                    backgroundColor: theme.colors.primary,
                    flexDirection: 'row',
                    justifyContent: 'flex-end',
                    alignItems: 'center',
                  },
                ]}>
                <IconButton
                  size={30}
                  color="#fff"
                  icon="close"
                  style={{paddingTop: 10}}
                  onPress={() =>
                    dispatch(removeUserFromGroup(groupId, user.item))
                  }
                />
              </View>
            )}
            rightOpenValue={-60}
            keyExtractor={(item, index) => index.toString()}
          />
```

1) I'm getting this error: 
![Screen Shot 2019-12-17 at 10 57 47](https://user-images.githubusercontent.com/12745414/70980498-18309900-20bc-11ea-8dc1-3922a66ac1ff.png)
oddly enough, when I uncomment the console.log('user'), this error goes away ... 

2) When this does render (byI add the console.log), no effect is taking place, and the swipe is is not disabled.

**Comment by jemise111** [comment]
@ilibilibom if you are returning a `<SwipeRow />` in your `renderItem` function you should remove the `renderHiddenItem` prop entirely. 

See the SwipeRow.md doc for instructions on how to pass the visible and hidden item

https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeRow.md

**Comment by ilibilibom** [comment]
@jemise111 thanks! 
removing the renderHiddenItem ,and following the guidelines in the readme worked for me.

**Comment by jemise111** [comment]
Excellent @ilibilibom , closing this then

**Comment by fukemy** [comment]
> defined.
> What should `data` be ?

what is rowId??????
