### ISSUE TITLE
onScroll event not working with android

### ISSUE THREAD

**Issue by gvsakhil** [jemise111/react-native-swipe-list-view#386]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**
onScroll is working fine in ios but not working in android

**To Reproduce**
const isCloseToBottom = ({ layoutMeasurement, contentOffset, contentSize }) => {
        const paddingToBottom = 20;
        console.log(layoutMeasurement.height + contentOffset.y >=
            contentSize.height - paddingToBottom);
        return layoutMeasurement.height + contentOffset.y >=
            contentSize.height - paddingToBottom;
    };

<SwipeListView
                    useFlatList={true}
                    onScroll={({ nativeEvent }) => {
                        if (isCloseToBottom(nativeEvent)) {
                            showMore();
                        }
                    }}
                    keyExtractor={(item, index) => index.toString()}
                    data={dataList.slice(0, count)}
                    renderItem={(data, rowMap) => (
                        <SwipeList goToDetailed={goToDetailedPageClick} item={data.item} />
                    )}
                    renderHiddenItem={(data, rowMap) => (
                        <View style={Styles.rowBack}>
                            <View></View>
                            <View style={{ flexDirection: 'row' }}>
                                <TouchableOpacity onPress={() => shareFile(data.item)}>
                                    <Image style={{ height: 30, width: 30 }} source={require('../../../assets/share_file_a.png')} />
                                </TouchableOpacity>
                            </View>
                        </View>
                    )}
                    rightOpenValue={-50}
                    onRowOpen={(rowKey, rowMap) => {
                        setTimeout(() => {
                            rowMap[rowKey].closeRow()
                        }, 2000)
                    }}
                />

**Screenshots**

**Environment (please complete the following information):**
 - OS: android
 - RNSLV Version: 2.0.6
 - RN Version: 0.61.5

**Comment by jemise111** [comment]
Hey @gvsakhil I tried your issue in my example using RN 60.3 and didn't see any issues with the onScroll event firing. Can you do me a favor and change the SwipeListView to a regular FlatList and see if the onScroll event is working in that case?

If it is I will upgrade to RN 61.5 and try to reproduce again.

If it is not this is an issue with RN itself and not this package.

Please let me know, thanks!

**Comment by kopax** [comment]
Hi @gvsakhil I would have had a look if this was properly formated for displaying code.

**Comment by jemise111** [comment]
Closing as I do not believe this is an issue with this library
