### ISSUE TITLE
When the disableRightSwipe is true, swipe right after opening again to open the right button.

### ISSUE THREAD

**Issue by jevonsofcode** [jemise111/react-native-swipe-list-view#387]
[the line](https://github.com/jemise111/react-native-swipe-list-view/blob/12a85eb55bd25d6ab13eb02afeda11750bac06e8/components/SwipeRow.js#L314)  should not exist

**Describe the bug**
When the disableRightSwipe is true, swipe right after opening again to open the right button.

**Show BUG**
[codesandbox](https://codesandbox.io/embed/issue-react-native-for-web-sectionlist-sticky-header-sl8kh?fontsize=14&hidenavigation=1&theme=dark)

step:
1 : swipe left one item (open the right button)
2 : Manual reset （close the right button）
3 : swipe right (You will find that you swipe right BUT open the right button)

**Environment (please complete the following information):**
 - OS: web & android & ios
 - RNSLV Version: latest
 - RN Version: latest

**Comment by perroudsky** [comment]
I have the same issue!

**Comment by jevonsofcode** [comment]
> I have the same issue!

sorry, I solved the problem but forgot to say

you just delete [this](https://github.com/jemise111/react-native-swipe-list-view/blob/6f22515c1d404d51bf8a6d1591ec51d241b77b9b/components/SwipeRow.js#L314) "if" 

if u don't want to change the source code, u just set left||right is 0

**Comment by perroudsky** [comment]
Works great! Thanks you so much!

**Comment by jevonsofcode** [comment]
> Works great! Thanks you so much!

 ; )

**Comment by loodsite** [comment]
@jevonsofcode @perroudsky 

> if u don't want to change the source code, u just set left||right is 0

What need to be set to 0?
I am using SwipeRow and I also notice this glitch, and don't want to change source code before new version
`<SwipeRow
          disableLeftSwipe={false}
          disableRightSwipe={true}
          rightOpenValue={-88}
          style={styles.swipeRow}>`
rightOpenValue={-88} is because i want to see my back delete button

**Comment by jevonsofcode** [comment]
> @jevonsofcode @perroudsky
> 
> > if u don't want to change the source code, u just set left||right is 0
> 
> What need to be set to 0?
> I am using SwipeRow and I also notice this glitch, and don't want to change source code before new version
> `<SwipeRow disableLeftSwipe={false} disableRightSwipe={true} rightOpenValue={-88} style={styles.swipeRow}>`
> rightOpenValue={-88} is because i want to see my back delete button

TRY:
set leftOpenValue & stopLeftSwipe is 0 or 0.01 （I forgot , sorry ）and don't use disableXxxxSwipe  ,  if you only want to open "right button"

**Comment by loodsite** [comment]
@jevonsofcode fixed in new version 2.2.0, thanks anyway
