### ISSUE TITLE
Sending "onAnimatedValueUpdate" with no listeners registered.

### ISSUE THREAD

**Issue by lixuanle** [jemise111/react-native-swipe-list-view#388]
**Describe the bug**
On some occasions, React Native will spit this warning out: Sending "onAnimatedValueUpdate" with no listeners registered.

**To Reproduce**
Usually happens after you remove a row, happens occasionally in the Example when you switch Lists without swiping.

**Screenshots**
![Screen Shot 2019-12-23 at 3 31 28 PM](https://user-images.githubusercontent.com/37774901/71379623-f773b200-2599-11ea-8f3b-2143ce5c71bf.png)

**Environment (please complete the following information):**
 - OS: iOS
 - RNSLV Version: 1.5.8 and 2.1.2
 - RN Version: 0.60.3 and 0.61.4

**Comment by lixuanle** [comment]
Any update on this? 

Just wondering if this warning can/will cause performance issues? As far as I know, everything is still working as intended its just react native giving me this warning.

Thanks!

**Comment by jemise111** [comment]
Hey @lixuanle, thanks for reporting and sorry for the delay - you're right this is an issue but I don't think there's much I can do about it. I've double checked and every listener that is added to the SwipeRow is removed on `componentWillUnmount`.

I'm guessing if a SwipeRow is animating while it is unmounting (like in the cases you described) than there will be a few pixels of animation where the event is fired before the listener is removed. 

As long as you're not seeing actual performance problems and as long as the warning doesn't persist on subsequent row swipes I don't think this will be an issue. Can you confirm those things? Thanks!

**Comment by lixuanle** [comment]
No problem! Thanks for replying. 😁 

After a bit more testing, the warning actually fires on rare occasions when using `SwipeRow` as well.

As far as performance problems, I haven't seen any issues currently since it only fires the warning once per swipe and when the row is removed it doesn't continue to send the same warning.

`SwipeListView` however, when switching to a screen that renders out the list, the warning may fire a few times without even interacting with the rows as seen in the example.

**Comment by jemise111** [comment]
@lixuanle I believe the reason it fires in the example is because there's a preview row swipe running when you switch tabs to the one of the other list views.

Would you possible be able to upload a video of what you're seeing? I'm curious if you're doing some sort of swipe animation while the row is deleting? I'm seeing the warning in some instances but not after a deletion

**Comment by lixuanle** [comment]
I figured out a way to recreate what I'm seeing fairly consistently when using `SwipeRow`.

If you try to delete a row after doing swipes in quick succession, it'll fire off the warning. I have 2 implementations of deletion in my own code. One is to click on a button in the back row and the other is to swipe across. 

[I've uploaded a video here](https://streamable.com/loa75) for you to see what I'm talking about.

For example, in the 1st row I am deleting, I swiped halfway and let go to let the row snap back into place and then immediately swiped across all the way and it fired the warning because I made 2 quick swipes. 

I think what you mentioned previously about the few pixels of animation is correct. The rows are being deleted before all the listeners have been sent.

**Comment by jemise111** [comment]
@lixuanle the video was very helpful, thanks! I just tried to add some more code to kill a running animation if the component unmounts and not only did the warnings still show but the UI looked a lot worse.

Given all you've told me I think you're right that there are a few events being fired without registered listeners but since it's always in the case of a row unmounting I'm not really worried about performance issues here.

I'll keep an eye on it and see if others report and performance problems with a similar issue but for now I feel comfortable closing this and saying it's a non-issue.

If you want to ignore the yellowbox warning you can always do so using `console.ignoredYellowBox`.

Does that sound okay?

**Comment by lixuanle** [comment]
Yea, as long as performance isn't an issue I have no problems with the warnings. That's all I needed to confirm was that there wouldn't be anything impactful.

Thanks so much for your help! Happy holidays! 😁

**Comment by doruxan** [comment]
I think I have a problem with this actually.

I'm using rn 0.61.5 and react navigation v5.

when I open a full screen modal with rnv5, and while modal is open, make a request for the items thats placed in SwipeRows, when I come back, I have this yellow warning and I cant swipe theese rows.

**Comment by rickysullivan** [comment]
Getting the same issue here during dev mode, I think that in prod mode it's crashing my app.

**Comment by perfecten** [comment]
I have the same issue

**Comment by kenzo23312** [comment]
some issue

**Comment by flavio0567** [comment]
I have the same issue :(

**Comment by slolkunchik** [comment]
me too (

**Comment by ghasemikasra39** [comment]
same issue

**Comment by IamMasterWayne** [comment]
**1**
Facing...
Sending `onAnimatedValueUpdate` with no listeners registered

**Comment by pmclachlan** [comment]
This warning seems to be related to the call to _translateX.removeAllListeners() during componentWillUnmount().

If I change componentWillUnmount() to call .stopAnimation() & .runAfterInteractions() before removing the listeners, I don't get the warning anymore.


    componentWillUnmount() {
        clearTimeout(this._ensureScrollEnabledTimer);
        this._translateX.stopAnimation(()=>{
            InteractionManager.runAfterInteractions().then( () => {
                this._translateX.removeAllListeners();
            })
        });
    }

**Comment by jemise111** [comment]
Hey guys sorry for the delay. I really have trouble producing this locally so I'm relying on y'all a bit here. If people want to try to verify @pmclachlan 's solution I'm happy to merge it, or push an rc tag or something

**Comment by RamProg** [comment]
> This warning seems to be related to the call to _translateX.removeAllListeners() during componentWillUnmount().
> 
> If I change componentWillUnmount() to call .stopAnimation() & .runAfterInteractions() before removing the listeners, I don't get the warning anymore.
> 
> ```
> componentWillUnmount() {
>     clearTimeout(this._ensureScrollEnabledTimer);
>     this._translateX.stopAnimation(()=>{
>         InteractionManager.runAfterInteractions().then( () => {
>             this._translateX.removeAllListeners();
>         })
>     });
> }
> ```

How can I do this with a function component?

**Comment by tkieft** [comment]
I'm able to repro this pretty easily: Have a single `FlatList` which swaps out its data based on some user-tappable buttons. Try tapping one of those buttons while the `SwipeRow` is animating open and you will get a bunch of these warnings.

@pmclachlan's solution didn't quite remove all the warnings for me; I think the correct solution is:

```
this._translateX.stopAnimation(() => {
    requestAnimationFrame(() => {
        this._translateX.removeAllListeners();
    })
});
```

**Comment by kjoonas1** [comment]
How come this issue was closed? I'm still facing the same problem, when the data changes by some button press. Is there a way to prevent that in functional components? After that warning comes, rows can't be swiped anymore.

**Comment by Selenestica** [comment]
> > This warning seems to be related to the call to _translateX.removeAllListeners() during componentWillUnmount().
> > If I change componentWillUnmount() to call .stopAnimation() & .runAfterInteractions() before removing the listeners, I don't get the warning anymore.
> > ```
> > componentWillUnmount() {
> >     clearTimeout(this._ensureScrollEnabledTimer);
> >     this._translateX.stopAnimation(()=>{
> >         InteractionManager.runAfterInteractions().then( () => {
> >             this._translateX.removeAllListeners();
> >         })
> >     });
> > }
> > ```
> 
> How can I do this with a function component?

@kjoonas1 @RamProg I went to my node_modules folder > react-native-swipe-list > components > then in SwipeRow.js on around line 176 I changed the following code to use the solution posted by @tkieft, like below
```
    componentWillUnmount() {
        clearTimeout(this._ensureScrollEnabledTimer);
        // old code
        // this._translateX.removeAllListeners();

        // add in the code below to remove the warning
        this._translateX.stopAnimation(() => {
            requestAnimationFrame(() => {
                this._translateX.removeAllListeners();
            })
        });
    }
```

This worked for me to remove the warning and things seem to be working fine.

**Comment by ucwealth** [comment]
> > > This warning seems to be related to the call to _translateX.removeAllListeners() during componentWillUnmount().
> > > If I change componentWillUnmount() to call .stopAnimation() & .runAfterInteractions() before removing the listeners, I don't get the warning anymore.
> > > ```
> > > componentWillUnmount() {
> > >     clearTimeout(this._ensureScrollEnabledTimer);
> > >     this._translateX.stopAnimation(()=>{
> > >         InteractionManager.runAfterInteractions().then( () => {
> > >             this._translateX.removeAllListeners();
> > >         })
> > >     });
> > > }
> > > ```
> > 
> > 
> > How can I do this with a function component?
> 
> @kjoonas1 @RamProg I went to my node_modules folder > react-native-swipe-list > components > then in SwipeRow.js on around line 176 I changed the following code to use the solution posted by @tkieft, like below
> 
> ```
>     componentWillUnmount() {
>         clearTimeout(this._ensureScrollEnabledTimer);
>         // old code
>         // this._translateX.removeAllListeners();
> 
>         // add in the code below to remove the warning
>         this._translateX.stopAnimation(() => {
>             requestAnimationFrame(() => {
>                 this._translateX.removeAllListeners();
>             })
>         });
>     }
> ```
> 
> This worked for me to remove the warning and things seem to be working fine.

Thanks. I tried this and it worked.

**Comment by ucwealth** [comment]
> 
> @kjoonas1 @RamProg I went to my node_modules folder > react-native-swipe-list > components > then in SwipeRow.js on around line 176 I changed the following code to use the solution posted by @tkieft, like below
> 
> ```
>     componentWillUnmount() {
>         clearTimeout(this._ensureScrollEnabledTimer);
>         // old code
>         // this._translateX.removeAllListeners();
> 
>         // add in the code below to remove the warning
>         this._translateX.stopAnimation(() => {
>             requestAnimationFrame(() => {
>                 this._translateX.removeAllListeners();
>             })
>         });
>     }
> ```
> 
> This worked for me to remove the warning and things seem to be working fine.

Thanks. I tried this and it worked.
