### ISSUE TITLE
Unable to display SwipeRows of variable height

### ISSUE THREAD

**Issue by zamiang** [jemise111/react-native-swipe-list-view#39]
I am in the process of transitioning a react native 0.29 ListView to your SwipeListView.

I've noticed that due to properties on a container I cannot style, the list items are all of equal height.

ListView on the left, SwipeListView on the right. 
![row-height](https://cloud.githubusercontent.com/assets/110563/16676545/2c0f04be-4499-11e6-8dbd-0f148afaea29.jpg)

Happy to help out here -- maybe passing style down the chain? -- but i'm not sure where to start.

Thanks

**Comment by jemise111** [comment]
Hey @zamiang happy to look into this but I think I'm missing the issue. The first two items look like they're of equal height. The third item looks larger on the right but it's not equal to the height of any other items. So is the issue that the height of the third item is unexpectedly larger?

If you could provide some snippets of code for the ```ListView``` and ```SwipeListView``` that would be really helpful.

Also if you'll take a look at this line:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L104

you'll see that any props you pass to the ```SwipeListView``` are passed to the underlying ```ListView```, meaning a ```style``` or ```contentContainerStyle``` prop will be passed along and you can style the container as you need.

**Comment by zamiang** [comment]
Thanks! Here is a bit more detail. TLDR - All rows have `flex: 1` applied in a way that I cannot override. https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L250

Color key: 
- yellow is background of the the SwipeListView
- purple and gray are alternating backgrounds of SwipeRow

With `flex: 1`:
![screenshot 2016-07-08 11 15 17](https://cloud.githubusercontent.com/assets/110563/16692415/aef4e2a8-44fe-11e6-8fa3-09b4196b507e.png)

`flex: 1` removed
![screenshot 2016-07-08 11 21 40](https://cloud.githubusercontent.com/assets/110563/16692417/b22f5412-44fe-11e6-930e-1d38eb9b28d9.png)

I believe the correct fix would be to allow passing custom styles to the SwipeRow (similar to the SwipeListView) rather than removing that line.

**Comment by jemise111** [comment]
@zamiang Okay so without your code to run and I can't really test if this will fix your problem. But when checkout this PR, #40,  when you have a sec and let me know if it fixes your issue. Then I'll merge and release a new version. Thanks!

**Comment by zamiang** [comment]
That looks great! 

I have gained a bit more insight into the root issue. React-native 0.28 made changes to how flex: 1 vs flex: 0 works. I have been seeing similar pull requests / issues with other projects. In [the release notes ](https://github.com/facebook/react-native/releases/tag/v0.28.0) you will see this note:

"flex styling property behavior now behaves slightly differently. If you previously used flex: 1 where not necessary this change will likely break your layout as the measuring behavior is slightly different than before due to performance optimizations. Removing that unnecessary flex: 1 will solve your layout in most cases."

**Comment by jemise111** [comment]
@zamiang I merged in the PR to allow for passing in styles. I'll do a release over the weekend. Good call on the flex: 1 issue, I'll take a look and see if it makes sense to remove it. Leaving this open until then. Thanks!

**Comment by jemise111** [comment]
Removed flex: 1, closing. Fixed by #40 and #43

**Comment by zamiang** [comment]
Thanks!
