### ISSUE TITLE
Does it work with react-native-web

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#390]
Hello everyone, I am new to react-native and started to build my first app with expo sdk 36.

I am not able to view the demo as the snack is broken but I strongly believe 2.x will help me achieve what I want. 

One prerequisite I have is to do a web view, for that expo does it by default. Since I am not seing an compatibility for web, I assume it does not work for the web.

As anybody tested it on the web?

Thanks and best wishes for 2020, happy new year!

**Comment by jemise111** [comment]
Hey @kopax, sadly I have not tested this with react-native-web, would be interested to know what you find though, thanks!

**Comment by proof666** [comment]
@kopax, I am not sure about 100% compatibility, but in my simple case it is work as expected on web platform with react-native-web (not Expo).

**Comment by kopax** [comment]
Excellent @proof666 , I will have a try. I must pop an item when I swipe left (like remove it, and scroll the list up). I only say this in case you already if that is impossible.

**Comment by kopax** [comment]
I am currently testing and it seems to work fine. So I am closing it and if necessary will reopen.
