### ISSUE TITLE
SwipeRow doesn't open when using react-native-draggable-flatlist

### ISSUE THREAD

**Issue by lixuanle** [jemise111/react-native-swipe-list-view#392]
**Describe the bug**
When using the `DraggableFlatList` component from [`react-native-draggable-flatlist`](https://github.com/computerjazz/react-native-draggable-flatlist) v2.0.0+ to render `SwipeRow`, the row instantly closes upon swiping.

Using `onRowOpen` and `onRowClose` shows that the row does not actually make a callback to `onRowOpen` and only on `onRowClose`.

To clarify, I am on the latest version of `react-native-swipe-list-view` and is working as intended, but when using `react-native-draggable-flatlist` with a version higher of v2.0.0 or higher, `SwipeRow` breaks.

**To Reproduce**
1) Install `react-native-draggable-flatlist` with any version above v2.0.0.
2) Use `DraggableFlatList` to render a list of `SwipeRow`.
3) Swipe.

**Screenshots**
Example of `SwipeRow` working as intended with `DraggableFlatList` using v1.1.19: https://streamable.com/a5mvv

Example of `SwipeRow` working unintended with `DraggableFlatList` using v2.0.0+:
https://streamable.com/wwkdg

**Environment (please complete the following information):**
 - OS: iOS and Android
 - RNSLV Version: v2.1.2
 - RN Version: v0.61.4

**Note:** I've also notified the developer of `react-native-draggable-flatlist` of the problem, and hopefully one of us can figure out where the conflict is coming from.

**Comment by lixuanle** [comment]
computerjazz/react-native-draggable-flatlist#107

**Comment by jemise111** [comment]
Hi @lixuanle I see you were able to close your issue in the draggable-flatlist library. Is everything working for you now? If so can we close this issue? Thanks and sorry for the delay in responding!

**Comment by LyricL-Gitster** [comment]
I was also unable to get this working using the latest versions of both libraries. According to the issue @lixuanle posted in [react-native-draggable-flatlist](https://github.com/computerjazz/react-native-draggable-flatlist/issues/107), they decided to implement [react-native-swipeable-item](https://github.com/computerjazz/react-native-swipeable-item#example) instead. I went that route as well after not being able to make this work.
