### ISSUE TITLE
Can swipe-list-view swipe up and down when horizontal ={true} ?

### ISSUE THREAD

**Issue by BaoNguyen1815** [jemise111/react-native-swipe-list-view#394]
When i set <SwipeListView horizontal = {true}>, the swipe action is still left and right.
I expect swipe action to be up and down. Is there any way to make it work?

**Comment by jemise111** [comment]
Hey @BaoNguyen1815 sorry but that isn't supported. There's a lot of code dealing with left and right swiping and it would be essentially an entirely new library to create a horizontal swipeable list view. I've added a note in the readme, thanks!
