### ISSUE TITLE
How to avoid tap while doing swipe?

### ISSUE THREAD

**Issue by mohitmishra22** [jemise111/react-native-swipe-list-view#399]
**Describe the bug**
Whenever I swipe to see the options, the touch triggers the tap and goes to a child's view. I would like to know if there is any way to differentiate between tap and swipe.

Not sure if this qualifies as the bug but I really need help.

**To Reproduce**
In render item return TouchableHighlight and give onPress event to it. When you try to swipe it will trigger the onPress function as well.

**Environment (please complete the following information):**
 - OS: Android & iOS
 - RN Version: 0.60.5

**Comment by salmanitb** [comment]
just control opacity different for tap and swipe....

**Comment by mohitmishra22** [comment]
can you give more details on how I can handle the opacity for tap and swipe?

**Comment by jemise111** [comment]
Hi @mohitmishra22 can you confirm you have set up your Touchable exactly in this way:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L128

I do not see the onPress triggered when I swipe the row

Also see this note please: https://github.com/jemise111/react-native-swipe-list-view#note

If you have any other info that would be very helpful

**Comment by jasonwadsworth** [comment]
I'm having a similar problem. I'm not using `TouchableOpacity`, I'm using `TouchableHighlight`. When I swipe the `onPress` for the `Touchable` is firing.

**Comment by odogono** [comment]
I experienced this - it turned out I was importing TouchableHighlight/TouchableOpacity from react-native-gesture-handler. Importing from 'react-native' solved it.

**Comment by jemise111** [comment]
Closing as inactive, and possibly solved

**Comment by FGhavamian** [comment]
> I experienced this - it turned out I was importing TouchableHighlight/TouchableOpacity from react-native-gesture-handler. Importing from 'react-native' solved it.

In my case, the solution was to do exactly the opposite.

**Comment by NTJ3** [comment]
> > I experienced this - it turned out I was importing TouchableHighlight/TouchableOpacity from react-native-gesture-handler. Importing from 'react-native' solved it.
> 
> In my case, the solution was to do exactly the opposite.

Same, works for me @FGhavamian

**Comment by Sotatek-QuanDo** [comment]
I have tested on both react-native-gesture-handler and react-native. OnPress still fired when swiping, any update?

**Comment by dannybit** [comment]
I am experiencing the same issue

**Comment by Ascension499** [comment]
This answer might interest you https://stackdev.space/questions/android-tap-to-select-items-in-swipelistview
