### ISSUE TITLE
Please provide RTL support.

### ISSUE THREAD

**Issue by dev7050** [jemise111/react-native-swipe-list-view#400]
**Describe the bug**
swipe issues if device is set to RTL specific locale.

**Environment (please complete the following information):**
 - OS: [iOS & Android]
 - RNSLV Version: [e.g. v2.0.1]
 - RN Version: [v0.60.5]

**Comment by jemise111** [comment]
Hi @dev7050 I've tried setting my region / language to a RTL region and didn't see any issues. What problem specifically are you having?

**Comment by dev7050** [comment]
Hello @jemise111 , I am building an app that provides multilingual support. On RTL specific the whole UI is changes to RTL but RNSLV swipe direction is not affected which is wrong and also menu options does not appear.
![Screenshot 2020-04-08 at 5 45 40 PM](https://user-images.githubusercontent.com/58287483/78785406-bbd3eb00-79c4-11ea-91b8-9169d9b9355b.png)
![Screenshot 2020-04-08 at 5 46 52 PM](https://user-images.githubusercontent.com/58287483/78785437-c9897080-79c4-11ea-9000-29098f5f9701.png)

**Comment by jemise111** [comment]
Hey @dev7050 this isn't supported out of the box. I can try to implement it but in the meantime I don't think it would be too difficult to switch the `rightOpenValue` / `leftOpenValue` when RTL is enabled.

See this thread for an example where I believe someone was able to achieve thishttps://github.com/jemise111/react-native-swipe-list-view/issues/426
