### ISSUE TITLE
[RFR] Update snack demo

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#402]
**Describe the bug**

The snack from the readme is broken.

**To Reproduce**

Click on that link: https://snack.expo.io/@jemise111/react-native-swipe-list-view

**Screenshots**

![snack on README.md](https://user-images.githubusercontent.com/1866564/74122266-189d6a00-4bfd-11ea-9404-f2f1066b5717.png)

![snack is broken](https://user-images.githubusercontent.com/1866564/74082223-7b222900-4a8a-11ea-8afa-efc688f8c25a.png)

**Related Issues**

- https://github.com/jemise111/react-native-swipe-list-view/issues/401#issuecomment-583749977

> Open a separate issue for this and I'm happy to try and fix it

**Comment by kopax** [comment]
I have created a snack here: https://snack.expo.io/@kopax/swipelistview

All you need to do is fork to have the proper account and upadte the readme.

I am now trying to add examples and solve https://github.com/jemise111/react-native-swipe-list-view/issues/403

**Comment by jemise111** [comment]
@kopax Thanks for creating the snack. As I had trouble running some of your examples locally, I decided to just redo them myself. They are now broken into different folders under `SwipeListExample/examples` and I have fixed the Snack as well
