### ISSUE TITLE
Cannot run the example on Android

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#405]
**Describe the bug**

I am trying to run the example on android, I have the followed this guide:

https://github.com/jemise111/react-native-swipe-list-view#running-the-example

**To Reproduce**

The application under ./SwipeListExample will produce the above example. To run execute the following:

```
git clone https://github.com/jemise111/react-native-swipe-list-view.git
cd react-native-swipe-list-view
cd SwipeListExample
yarn
// USB plug the android phone in developer mode
react-native run-android
cd android/app/ && keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
// answer the questions
cd ../..
react-native start
```

**Screenshots**

![image](https://user-images.githubusercontent.com/1866564/74123155-41732e80-4c00-11ea-86d3-f4e48d63ace3.png)

I have a blank view.

**Related issues**

- https://github.com/jemise111/react-native-swipe-list-view/issues/401

**Environment**
 - OS: Android
 - RN Version: expo SDK36
- Device: Samsung Galaxy S9 on Android 9

**Comment by jemise111** [comment]
@kopax given I have merged this PR: https://github.com/jemise111/react-native-swipe-list-view/pull/404 can we close this issue?

**Comment by kopax** [comment]
Hi @jemise111, It's your choice to close it. I was not able to test the `example.js`. I was able to test it with the snack I have created. Perhaps we should replace the example.js with my snack, which is more copy/pastable and separate concerns making it more readable.

**Comment by jemise111** [comment]
Closing as this is now done
