### ISSUE TITLE
How to preview the left btn instead of the right button

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#409]
Hi again,

I have two swipe actions:
- swipe left to delete 
- swipe right to add to my favorite

I want to display the preview for the add to my favorite action, which is starting the left side.

Currently, the demo show the right side.

Is it possible to animate the left button?

**Comment by jemise111** [comment]
Hi @kopax this isn't currently possible but it would be a pretty simple code change. Any chance you could put in a PR for this?

**Comment by ramisalem** [comment]
Hello @jemise111 anyupdates for above request

**Comment by kopax** [comment]
@jemise111 not yet, I will have to have to invest some of my free time, which I am currently investing on another topic. Ping me back in about 4 month and I might have a look then.

**Comment by jemise111** [comment]
@kopax @ramisalem Oops! This one is totally supported, not sure what I was thinking above. See the prop `"previewOpenValue"` here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeListView.md

Passing a positive value will preview the row to the left. i.e. `previewOpenValue={100}`
