### ISSUE TITLE
Swipe list gesture bad on Android and very bad on iOS

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#410]
## Description

I have configured a swipe left to delete, swipe right to add to favorite action with the sample code from `example.js`.

I am comparing the swipe from my app when I try to swipe left/right with another app I am referring to as an example of valid user experience.

## 1\ iOS 

The focus get lost super quickly in iOS interrupting the action, this require the user to be careful and the user experience gets badly degraded. I explain down below what cause the issue.

## 2\ Android

On Android, the scroll works way better, but compare to my sample application, if I try to swipe fast (like on tinder app), instead of swiping, there is some delay making it look not fluid at all and degrading the user experience.

## Reproduction

https://snack.expo.io/@kopax/react-native-swipe-list-view-408

## Environment

 - OS: iOS and Android
 - RNSLV Version: 2.1.3
 - RN Version: expo SDK36

## Possible fix

For **(1)**, I have locked my wrapper `<ScrollView />` to use `onScrollEnable`:

```jsx
function ListView({
  Link,
  pages,
  t,
  theme,
  dimensions,
  ...rest
}) {
  const { colors } = theme;
  const [scrollEnabled, setScrollEnable] = useState(true);
  return (
    <ScrollView
      bounces={false}
      scrollEnabled={scrollEnabled}
      {...rest}
    >
        <SwipeListView
          // make the list longer for optimization testing purposes
          listViewData={[...itemList, ...itemList, ...itemList, ...itemList]}
          dimensions={dimensions}
          onScrollEnabled={setScrollEnable}
        />
    </ScrollView>
  );
}
```

This work properly on Android and iOS, it locks the scroll of the wrapper view, but on iOS, `onScrollEnabled` is called way more times than it should, switching from `true/false` while swiping.

This is probably why it loses the event focus, and it seems the value that causes the error is from this library and could be fixed.

I am not used to iOS and Android development, do you know if I should configure every parent view to disable events and make it more smooth for the user experience?  

## Possibly related issues

- https://github.com/jemise111/react-native-swipe-list-view/issues/34

Thanks and best

**Comment by kopax** [comment]
I am considering to **add some infinite scrolling** (loading list while scrolling), I feel like the longer the list is, the worst is the user experience when swiping.

Has anyone ever tried to implement such feature using `react-native-swipe-list-view`. Thanks again?

**Comment by jemise111** [comment]
@kopax This is a recording of your snack. I see absolutely no issues with gesture recognizing, scrolling, locking scrolling, anything like that. I really don't understand this issue..?

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/4265163/75098298-e1727580-5579-11ea-8e7f-6440f3702953.gif)

**Comment by kopax** [comment]
Hi jemise, I believe if you don't see the same issue perhaps you should test on a real devices. let's close this for now. I replaced react native swipe list view with react native gesture handler swipeable. This solved my issue.

**Comment by jemise111** [comment]
Sure thing, just FYI this was on real device
