### ISSUE TITLE
Optimize the list rendering with lazy loading to imprive swipe effects

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#411]
## Description

The longer the list is, the slowest are the animation making it hard to have a correct user experience.

A way to optimize that is to add dynamic loading of the list to produce the infinite scrolling effect.

This feature request will allow a way to implement infinite to solve slow swipe rendering issues.

## Reproduction

- https://snack.expo.io/@kopax/react-native-swipe-list-view-408

## Environment

 - OS: iOS and Android
 - RNSLV Version: 2.1.3
 - RN Version: expo SDK36

## Related issues

- #34
- #410

## Community question

As anybody ever tried to implement an infinite scroll with this library? It would be nice to know about any attempt and result.

**Comment by jemise111** [comment]
@kopax this is not an issue with this library. The `SwipeListView` is just a wrapper around a `FlatList`. Anything you can do with a FlatList you can do here. There are lots of tutorials out there to achieve this affect. Here's one to get you started: https://levelup.gitconnected.com/react-native-firebase-cloud-firestore-implementing-infinite-scroll-lazy-loading-with-flatlist-a9e942cf66c6
