### ISSUE TITLE
Upgrade to react-native-web 0.12.1 is not supported due to ViewPropTypes import being removed

### ISSUE THREAD

**Issue by kopax** [jemise111/react-native-swipe-list-view#412]
**Describe the bug**

I have tried to upgrade from `react-native-web` v0.11.7 to 0.12.1 and it break my app:

     Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in '/home/dka/workspace/test-native/node_modules/react-native-swipe-list-view/components'

See:

https://github.com/jemise111/react-native-swipe-list-view/blob/6f22515c1d404d51bf8a6d1591ec51d241b77b9b/components/SwipeRow.js#L11

**To Reproduce**

upgrade to react-native-web v0.12.1

**Environment (please complete the following information):**
 - OS: web
 - RNSLV Version: 2.1.3
 - RN Version: expo SDK 36

**Related issues**

- https://github.com/necolas/react-native-web/issues/1537

**Comment by jemise111** [comment]
Fixed by #454
