### ISSUE TITLE
Question: Swipe as toggle — no need to stay open.  How?

### ISSUE THREAD

**Issue by StevenBlack** [jemise111/react-native-swipe-list-view#416]
Hi Jesse @jemise111, great component!  I love it.  

I can't seem to figure this out: in one instance, I'm using the Swipe as a toggle, that's all.  So there's no need to keep the swipe open.

How can I automatically close the Swipe once its been open past a threshold, and released?

I must be missing something obvious...  Thank you in advance.

**Comment by jemise111** [comment]
Hey @StevenBlack that's a good question. You'll be very interested in this PR https://github.com/jemise111/react-native-swipe-list-view/pull/395 and the work that @proof666 is doing. Until that is merged the best solution I could think of until then is as follows:

```
closeRow(rowMap, rowKey) {
  if (rowMap[rowKey]) {
    rowMap[rowKey].closeRow();
  }
}

onRowDidOpen = (rowKey, rowMap) => {
  this.closeRow(rowMap, rowKey);
};

render() {
  return (
    <SwipeListView
      data={this.state.listViewData}
      stopLeftSwipe={75}
      onRowDidOpen={this.onRowDidOpen}
      renderItem={data => (
        <TouchableHighlight
          style={styles.rowFront}
```

Which produces this:

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/4265163/74947113-fe634900-53bf-11ea-9864-c5ec017354cd.gif)

**Comment by StevenBlack** [comment]
Thanks Jesse @jemise111, that'll work!  Duh, how was this not obvious, now that I see your suggestion? 🙃  Honestly, I'm losing it.

Looking at the PR.... Sergey @proof666 rocks!  That's a tremendous PR.

**Comment by jemise111** [comment]
@StevenBlack glad to hear it, going to close this, please reopen if you still have issues, thanks!

**Comment by proof666** [comment]
@StevenBlack, i think i am done with PR #395, it would be great if you can check it out from https://github.com/proof666/react-native-swipe-list-view master branch before it lands here and provide your feedback.
