### ISSUE TITLE
onRowClosed/onRowDidClose not called if fully closed by user

### ISSUE THREAD

**Issue by benzman81** [jemise111/react-native-swipe-list-view#418]
**Describe the bug**
The functions for _onRowClosed_ and _onRowDidClose_ do not get called if the user fully swipes back to position _0_ and _disableRightSwipe_ is _true_. The issue is in line https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L314 . Since this is commented out in master only a release with this commented out code that fixed #387 is missing to fix this, too.

**To Reproduce**
1 : Add a function for _onRowDidClose_
2 : swipe left one item (open the right button)
3 : Manual reset to fully close the item so that no animation happens
4 : As a result the function for _onRowDidClose_ does not get called.

**Screenshots**

**Environment (please complete the following information):**
 - OS: iOS
 - RNSLV Version: 2.1.3
 - RN Version: 0.61.5

**Comment by jemise111** [comment]
@benzman81 that's my bad! I didn't realize I never released it.

This code should be released in v2.2.0. If this is still an issue there please re-open, thanks!
