### ISSUE TITLE
Re-render renderHiddenItem?

### ISSUE THREAD

**Issue by tudiantuan** [jemise111/react-native-swipe-list-view#420]
I want to re-render HiddenItem when item.Notify change status. How can i do that?
<img width="775" alt="Screen Shot 2020-02-18 at 14 51 38" src="https://user-images.githubusercontent.com/39153315/74714958-2dfa4000-525e-11ea-8c99-173fbf727366.png">

**Comment by jemise111** [comment]
Hi @tudiantuan I tried this in my local example and I don't have any problems. Are you doing anything to prevent re-renders like using a `PureComponent` or `shouldComponentUpdate`?

Maybe if you could provide and example of what `this.props.chatList` looks like it'd help me?

**Comment by tudiantuan** [comment]
This is chatList initial : [{"CreDt":"2020-02-20T08:35:41Z","GrpId":"fa416091-53bb-11ea-a076-06305e00006b","GrpNm":"PersonA","GrpTp":"0","GrpFlg":"Y","GrpSec":"0","Status":"","TotMem":2,"Unread":0,"LastMsg":"","LastSeq":39,"OwnerId":"7d76cbbe-0600-11ea-a076-06305e00006b","UpdDate":"2020-02-20T12:35:49Z","AvatarID":"4ed92231-4c97-11ea-a076-06305e00006b","Notify":true},{"CreDt":"2020-02-20T07:57:15Z","GrpId":"9c32560e-53b6-11ea-a076-06305e00006b","GrpNm":"PersonB","GrpTp":"0","GrpFlg":"Y","GrpSec":"0","Status":"","TotMem":2,"Unread":0,"LastMsg":"","LastSeq":1,"OwnerId":"7d76cbbe-0600-11ea-a076-06305e00006b","UpdDate":"2020-02-20T07:59:34Z","AvatarID":"","Notify":true}]

After I change status notify of PersonB to false: [{"CreDt":"2020-02-20T08:35:41Z","GrpId":"fa416091-53bb-11ea-a076-06305e00006b","GrpNm":"PersonA","GrpTp":"0","GrpFlg":"Y","GrpSec":"0","Status":"","TotMem":2,"Unread":0,"LastMsg":"","LastSeq":39,"OwnerId":"7d76cbbe-0600-11ea-a076-06305e00006b","UpdDate":"2020-02-20T12:35:49Z","AvatarID":"4ed92231-4c97-11ea-a076-06305e00006b","Notify":true},{"CreDt":"2020-02-20T07:57:15Z","GrpId":"9c32560e-53b6-11ea-a076-06305e00006b","GrpNm":"PersonB","GrpTp":"0","GrpFlg":"Y","GrpSec":"0","Status":"","TotMem":2,"Unread":0,"LastMsg":"","LastSeq":1,"OwnerId":"7d76cbbe-0600-11ea-a076-06305e00006b","UpdDate":"2020-02-20T07:59:34Z","AvatarID":"","Notify": false}]

**Comment by tudiantuan** [comment]
This is 2 file template https://github.com/tudiantuan/TestList

**Comment by jemise111** [comment]
https://github.com/tudiantuan/TestList/blob/master/ChatList.js#L149

This is your problem, remove this and your changes will work just fine
