### ISSUE TITLE
Delay of about 1.3 seconds for functions onRowDidOpen and onRowDidClose after Animation finished

### ISSUE THREAD

**Issue by benzman81** [jemise111/react-native-swipe-list-view#421]
**Describe the bug**
The functions for _ onRowDidOpen_ and _onRowDidClose_ have a delay of about 1.3 seconds after animation visually ends. This leads to wring behavior in my code if the user is fast. There is an issue in react native about it here https://github.com/facebook/react-native/issues/20783 . The suggestion is to use _restSpeedThreshold_ and _restDisplacementThreshold_ in _Animated_. I added _restSpeedThreshold: 100, restDisplacementThreshold: 40,_ to your code at https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L411 . This got the delay down to about 300ms. So my suggestion is to make _restSpeedThreshold_ and _restDisplacementThreshold_ settable by props just like _tension_ and _friction_ .

**To Reproduce**
1 : Add a function for _onRowDidOpen_ and log Date.now()
2: Add a function for _onRowOpen_ and log Date.now()
3 : swipe left one item (open the right button)
4 : You will see a delay of about 1.3 seconds

**Environment (please complete the following information):**
 - OS: iOS
 - RNSLV Version: 2.2.0
 - RN Version: 0.61.5

**Comment by jemise111** [comment]
Hey @benzman81 great suggestion! Do you think you could put in a PR for this?

**Comment by benzman81** [comment]
@jemise111 created a pull request
