### ISSUE TITLE
Set dynamic open values

### ISSUE THREAD

**Issue by sadikyalcin** [jemise111/react-native-swipe-list-view#424]
**Describe the bug**
Open values expect a number so we cannot pass a string. Is there anyway we can modify the module to allow a percentage value? This is an issue when a device is rotated. Unless I do a orientation change detection and update the value.

`rightOpenValue={-Dimensions.get('window').width / 2}` => `rightOpenValue={'-50%'}`

**To Reproduce**
Set a fixed number on an open value and rotate the device.

**Screenshots**
Portrait:

<img width="839" alt="Screenshot 2020-02-28 at 14 14 27" src="https://user-images.githubusercontent.com/8109619/75555746-bcc44500-5a34-11ea-96c6-6fa4afa69f81.png">

Landscape:
<img width="1203" alt="Screenshot 2020-02-28 at 14 14 33" src="https://user-images.githubusercontent.com/8109619/75555753-c188f900-5a34-11ea-89dd-36cd6413f0c2.png">

**Environment (please complete the following information):**
 - OS: Both
 - RNSLV Version: v2.3.0
 - RN Version: 0.61.5

**Comment by jemise111** [comment]
Hey @sadikyalcin unfortunately if you look through the code of `SwipeRow.js` you'll see that we're doing a good amount of math with the assumption that the `rightOpenValue` and `leftOpenValue` are numbers. It would take a significant rewrite to allow for percentage strings, and even then I'm not sure how it would work.

I would ask that you apply the percentage to the window width like you showed above i.e. `Dimensions.get('window').width * 0.5`.

As for the value not updating on an orientation change, can you try setting the prop `recalculateHiddenLayout={true}` and give it another go, I think this may fix your issue.

See more here: https://github.com/jemise111/react-native-swipe-list-view/issues/87

**Comment by sadikyalcin** [comment]
> Hey @sadikyalcin unfortunately if you look through the code of `SwipeRow.js` you'll see that we're doing a good amount of math with the assumption that the `rightOpenValue` and `leftOpenValue` are numbers. It would take a significant rewrite to allow for percentage strings, and even then I'm not sure how it would work.
> 
> I would ask that you apply the percentage to the window width like you showed above i.e. `Dimensions.get('window').width * 0.5`.
> 
> As for the value not updating on an orientation change, can you try setting the prop `recalculateHiddenLayout={true}` and give it another go, I think this may fix your issue.
> 
> See more here: #87

Hi Jesse, thanks for that, that has solved my problem.

**Comment by jemise111** [comment]
Awesome, glad to hear it
