### ISSUE TITLE
Props onSwipeGestureEnd 

### ISSUE THREAD

**Issue by matcwi** [jemise111/react-native-swipe-list-view#425]
I don't see any similar issue. Is it possible to use something which is opposite to onSwipeGestureBegan?
I want to call a function after my swipe action (not open).

**Comment by jemise111** [comment]
Hey @matcwi, there are currently props for `onRowClose`, `onRowDidClose`, `onRowOpen`, and `onRowDidOpen`

What would you be looking for in addition to these?

**Comment by matcwi** [comment]
I want to use this props, when user will start swiping but not open the row - he will drop row and row will be not opened(it will return to previous position) - i want to call my function in this moment.

I am using onSwipeGestureBegan when i start swiping and i want to use onSwipeGestureEnd when user will swipe but drop row and not open it.

**Comment by jemise111** [comment]
Hey @matcwi I just tested this. The `onRowClose` and `onRowDidClose` props **will** fire even if the row hasn't been opened. So if you have props for `onSwipeGestureBegan`, `onRowOpen`, and `onRowClose`, you should be able to tell exactly what is going on with swiping and each row

**Comment by kampretosjr** [comment]
hey @matcwi did you find any solution for this issue yet ? i looking for this feature too

**Comment by proof666** [comment]
@jemise111,
Sometimes you don’t need to sort through different events. It would not be bad to have an event triggered when you just stop touching the row. This can be useful when other parts of the interface depend on touch (for example, they hide or blur when you touch a row)

just my 2 cents

**Comment by jemise111** [comment]
@matcwi @kampretosjr @proof666 see #440, this is done, please use prop `swipeGestureEnded`
