### ISSUE TITLE
Way to disable left or right swipe 

### ISSUE THREAD

**Issue by ramisalem** [jemise111/react-native-swipe-list-view#426]
Hello thanks for such an awesome library, my app supports the Arabic language which is RTL.
 it would be easy for me if there is a way to disable left or right swipe respectively. when either right or left  swipe is enabled I need to show delete button

I am looking for somthing similar to fowlling screenshots
 when  lyout is RTL 
![photo_2020-03-02_18-19-44](https://user-images.githubusercontent.com/25037017/75677915-8267db80-5cb2-11ea-9aed-7aaea52153d0.jpg)

when lyout  LTR 
![photo_2020-03-02_18-22-46](https://user-images.githubusercontent.com/25037017/75678096-d7a3ed00-5cb2-11ea-9290-6e88f12f4eeb.jpg)

**Comment by jemise111** [comment]
Hey @ramisalem this isn't something currently supported out of the box but by changing the style for your delete button and changing things like `rightOpenValue` / `leftOpenValue` depending on if RTL is enabled or not this is definitely achievable

**Comment by NHuebner1983** [comment]
@jemise111 first off, this is the only swipe system we can get working with Expo - so grats to you on making this possible!

I am also looking to completely disable a drag direction.

**Comment by jemise111** [comment]
@NHuebner1983 Is that specific to RTL support?

There are props to disable a swipe direction such as `disableRightSwipe` | `disableLeftSwipe`. Does that solve your issue?

**Comment by NHuebner1983** [comment]
That totally did the trick.

**Comment by jemise111** [comment]
@NHuebner1983 Excellent!
