### ISSUE TITLE
在iPhone11中不支持左滑的效果

### ISSUE THREAD

**Issue by lm1073330969** [jemise111/react-native-swipe-list-view#430]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android]
 - RNSLV Version: [e.g. v2.0.2]
 - RN Version: [e.g. v60.0.5]

**Comment by jemise111** [comment]
Hey @lm1073330969 can you post some example code of a gif of your issue? It's had to diagnose what is going on without additional context.

Also you can try updating to the latest version of rnslv (2.4.0)
