### ISSUE TITLE
need to click 2 times to be able to open another swipe...

### ISSUE THREAD

**Issue by salmanitb** [jemise111/react-native-swipe-list-view#431]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android]
 - RNSLV Version: [e.g. v2.0.2]
 - RN Version: [e.g. v60.0.5]

**Comment by salmanitb** [comment]
` onRowPress(rowMap,rowKey) {
        const rowRef = rowMap[rowKey]
        if (this.rowIsOpen) {
          this.rowIsOpen = false;
          rowRef.closeRow();
        //   console.log(rowMap[rowKey])



        } else {
            this.rowIsOpen = true;
            rowRef.manuallySwipeRow(normalize(-160));

        }
      }
`

**Comment by salmanitb** [comment]
i use manuallysiperow to open and close swipe.. but need click 2 time to open another swipe

**Comment by jemise111** [comment]
Hey @salmanitb, so I think what you're saying is that when you tap on a different row than the currently opened row you have to tap a second time to get that row to open. I think what you're missing is keeping track of both the `rowKey` that was tapped and the previously opened `rowKey`. Here is an abbreviated example of how I was able to get this to work:

```
let rowIsOpen = false;
let previouslyOpenedRowKey = null;

export default function Example() {
    const [listData, setListData] = useState(
        Array(20)
            .fill('')
            .map((_, i) => ({ key: `${i}`, text: `item #${i}` }))
    );

    const onPress = (rowMap, rowKey) => () => {
        const row = rowMap[rowKey];
        if (rowIsOpen) {
            if (rowKey === previouslyOpenedRowKey) {
                row.closeRow();
                rowIsOpen = false;
                previouslyOpenedRowKey = null;
            } else {
                const previouslyOpenedRow = rowMap[previouslyOpenedRowKey];
                previouslyOpenedRow.closeRow();
                row.manuallySwipeRow(-150);
                rowIsOpen = true;
                previouslyOpenedRowKey = rowKey;
            }
        } else {
            row.manuallySwipeRow(-150);
            rowIsOpen = true;
            previouslyOpenedRowKey = rowKey;
        }
    };

    const renderItem = (data, rowMap) => (
        <TouchableHighlight
            onPress={onPress(rowMap, data.item.key)}
            style={styles.rowFront}
            underlayColor={'#AAA'}
        >
            <View>
                <Text>I am {data.item.text} in a SwipeListView</Text>
            </View>
        </TouchableHighlight>
    );

    return (
        <View style={styles.container}>
            <SwipeListView
                data={listData}
                renderItem={renderItem}
                renderHiddenItem={renderHiddenItem}
                leftOpenValue={75}
                rightOpenValue={-150}
            />
        </View>
    );
}
```

![RPReplay_Final1584806387 MP4](https://user-images.githubusercontent.com/4265163/77231096-aeb2a180-6b66-11ea-8906-c2741ef70753.gif)

**Comment by salmanitb** [comment]
@jemise111 ty so much.... this library help me so much.
