### ISSUE TITLE
Scrollbar appearing on left instead of far right (iOS)

### ISSUE THREAD

**Issue by downtowndev** [jemise111/react-native-swipe-list-view#432]
**Describe the bug**
The scrollbar shows up near the left side of the screen instead of the far right.

**To Reproduce**
Add enough items to the list so that they don't all appear on the screen, causing the device to show a scrollbar. Observe that the scrollbar is shown to the left instead of the far right.

**Screenshots**
![Scroll list view](https://user-images.githubusercontent.com/54512894/77244513-c1fb5680-6bd2-11ea-9e35-dfb2aa1e295b.PNG)

**Environment**
 - OS: iOS (can't reproduce on Android)
 - RNSLV Version: v2.4.0
 - RN Version: v0.60.5

**Comment by jemise111** [comment]
Hey @downtowndev, this is almost certainly not an issue with this library. There's nothing special happening with the styling of scroll indicators here, as underneath the hood this library just uses a plain FlatList (or SectionList).

e.g. this is from me scrolling in the example from the repo (https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/basic.js)

![image](https://user-images.githubusercontent.com/4265163/77250962-846dec00-6c19-11ea-9cfe-ecd6fc3fcdf2.png)

I can try to help diagnose your issue if you want to post some of your code

**Comment by downtowndev** [comment]
Thanks for the info, I will look into it a bit more. The issue doesn't appear when the app is first opened, it only appears sometimes after switching to a new list. I'm using `react-native-side-menu` which I think may be part of the issue. The scrollbar is drawn near the left of the screen, which is actually the far right *when* the sidemenu is open. I think the list view may calculate the scrollbar position before the sidemenu is closed, causing it to be drawn near the left side of the list when the sidemenu is closed.

Not sure if that makes sense, but below is another pic with the sidemenu open. I'm going to close this. I haven't found a fix yet, but I'm thinking of replacing `react-native-side-menu` with a sidemenu using `react-navigation` which may also fix this issue.

![Sidemenu](https://user-images.githubusercontent.com/54512894/77282539-735bc400-6c87-11ea-822d-685cfcce14f9.PNG)
