### ISSUE TITLE
Lack of documentation around importance of `key` in data array

### ISSUE THREAD

**Issue by iKrushYou** [jemise111/react-native-swipe-list-view#434]
**Describe the bug**
I have spent about an hour now trying to debug as to why I couldn't get the rows to auto-close when touching other rows. And it finally came down to the fact that my data items did not have a `key` property. They did have a `uuid` property, but that wouldn't map for obvious reasons. So, I finally found the solution after digging through the examples and slowly recreating my own implementation line by line until the bug appeared.

**To Reproduce**
- Open this example: https://snack.expo.io/@jemise111/react-native-swipe-list-view
- Edit this line:
```javascript
    const [listData, setListData] = useState(
        Array(20)
            .fill('')
            .map((_, i) => ({ key: `${i}`, text: `item #${i}` }))
    );
```
to remove the `key` field:
```javascript
    const [listData, setListData] = useState(
        Array(20)
            .fill('')
            .map((_, i) => ({ text: `item #${i}` }))
    );
```
- swipe open multiple rows

Now, the `key` property is obviously necessary for tracking each row. However, this should absolutely be documented somewhere (and if it is, I do apologize but I was unable to find it)

**Comment by jemise111** [comment]
Hey @iKrushYou, any chance you could submit a PR and add this to the readme?

**Comment by iKrushYou** [comment]
@jemise111 sure thing, just wanted to make sure it was actually a bug
