### ISSUE TITLE
getScrollResponder() is not a function

### ISSUE THREAD

**Issue by npomfret** [jemise111/react-native-swipe-list-view#44]
I'm unable to call the getScrollResponder() function on my ListView.  I get:

`TypeError: messagesList.getScrollResponder is not a function`

**Comment by jemise111** [comment]
Hey @npomfret I've added a prop to get a ref to the ListView called listViewRef in #47.

I'll release it shortly and you should be able to do

```
<SwipeListView
    listViewRef={ref => this.messagesList = ref}
/>
```

and then ```this.messagesList.getScrollResponder``` should work just fine. Let me know if you have any issues!

**Comment by npomfret** [comment]
Thanks!
