### ISSUE TITLE
Get row details when swiping to delete

### ISSUE THREAD

**Issue by aravi365** [jemise111/react-native-swipe-list-view#444]
I've managed to store the list items data in a state and then pass it to SwipeListView as data={this.state.data} . Everything went ok till the swipe to delete implementation, but the thing is i need to get the id of every item (row) thats swiped so as to make an api call along with removing the item from state. How to achieve this? @jemise111

**Comment by jemise111** [comment]
Hey @aravi365 this would be a little easier to answer if I could see some example code but in general the `onSwipeValueChange` function passes you a `key` you can use to find the data of the row being swiped. Here is a modification of the example from https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/swipe_to_delete.js

```
export default function SwipeToDelete() {
  const [listData, setListData] = useState(
    Array(20)
      .fill('')
      .map((_, i) => ({ key: `${i}`, text: `item #${i}` }))
  );

  const onSwipeValueChange = swipeData => {
    const { key, value } = swipeData;

    const rowData = listData.find(data => data.key === key);
```

And now you have the `rowData` for the row being swiped

**Comment by aravi365** [comment]
@jemise111  Cool, thats what i wanted. Can you please make the readme more userfriendly, i feel like getting confused for minute things. Anyways a big thumbs up for this awesome library and your quick assistance. Thanks brother!

**Comment by jemise111** [comment]
>  Can you please make the readme more userfriendly

Any suggestions?
