### ISSUE TITLE
Delete on swipe + button

### ISSUE THREAD

**Issue by samykolahi** [jemise111/react-native-swipe-list-view#445]
**Describe the bug**
Hello, I tried to find in the reported issue and your documentation something like that but I could not.
Basically, I am trying to have the functionality in your documentation under the "basic" tab coupled with the "SwipeToDelete" functionality.
I am also quite new to React Native so might be that I just don't have the skill to do it.
I wanted to know if you could help me or give me some tips to start implementing it by using your already existing sublime lib :) !
My only guess so far is to do it with Animation. It is quite a challenge though, so if there is another way that I missed for doing it, I would be more than happy to read it

**To Reproduce**
First example is: 
Drag the swipe row above 50% does the delete but opening it less than 50% does not show the delete button.

Second one is:
Drag the swipe row above 50% does not delete the row but open the button to delete the row.

**Screenshots**
<img width="374" alt="Screenshot 2020-04-05 at 22 21 26" src="https://user-images.githubusercontent.com/29926734/78509097-e38c3e80-778b-11ea-878e-2d958367e7e2.png">
<img width="374" alt="Screenshot 2020-04-05 at 22 21 35" src="https://user-images.githubusercontent.com/29926734/78509100-e850f280-778b-11ea-907e-a1155a2c41e3.png">

**Environment (please complete the following information):**
 - RN Version: 0.61.5

**Comment by jemise111** [comment]
Hey @samykolahi that is a very interesting use case. I'm not sure that would currently be supported with the existing swipe_to_delete examples, however I think you should try out the latest beta version of the library (v3.0.0-rc2) and look at https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/actions.md

That might help you achieve being able to do both at the same time.

Give that shot and if it is still not working I can devote some more time this weekend to looking into this, thanks

**Comment by samykolahi** [comment]
Hey @jemise111, thanks for the answer, I will give it a try when I have time.
Thanks for the answer & have good day,
Cheers

**Comment by kidasov** [comment]
Faced the same issue long time ago. Unfortunately didn't find anything similar. Made my own example with FlatList https://github.com/kidasov/react-native-swipe-to-delete

**Comment by jemise111** [comment]
Closing as inactive
