### ISSUE TITLE
Change hidden view position

### ISSUE THREAD

**Issue by hoangvv511** [jemise111/react-native-swipe-list-view#446]
Currently when the rendering of the hidden view is below the main view, is there any way to make it follow the main view?

**Comment by jemise111** [comment]
Hey @hoangvv511 are you looking for this type of behavior? https://github.com/jshanson7/react-native-swipeable

That is not fundamentally how this library is set up. I would give that one a try

**Comment by hoangvv511** [comment]
@jemise111 The behavior looks like scrollview i guest so, the hidden view will be on the same row
 with main view

**Comment by jemise111** [comment]
So are you able to use that library instead?
