### ISSUE TITLE
render hidden item causes flicker

### ISSUE THREAD

**Issue by hoangvv511** [jemise111/react-native-swipe-list-view#448]
**Describe the bug**
When I call an api to get a list, I use SwipeListView, but it renders the hidden part first and causes flickering on the first render of an item, see the example below.

**Screenshots**
![20200411_155319](https://user-images.githubusercontent.com/33971551/79039718-6d655d00-7c0d-11ea-8de8-3e32836e94b9.gif)

The blinking green part is the hidden view, is there any way to avoid this phenomenon?

**Comment by jemise111** [comment]
Can I see the code you use to render the SwipeList?

This sometimes happens when people use a `TouchableOpacity` for their rows instead of a `TouchableHighlight`

**Comment by amitava82** [comment]
I'm seeing this as well when moving in/out of view.
Here is renderItem:
```
<SwipeRow disableRightSwipe rightOpenValue={-75}>
        <TouchableOpacity
          disabled={inboxStore.saving}
          style={[styles.backRightBtn, styles.backRightBtnRight]}
          onPress={() => this.onArchive(item)}
        >
          <View>
            <Icon name="ios-archive" color="white" />
            <Text color="white">Archive</Text>
          </View>
        </TouchableOpacity>
        <ListItem
          convo={item}
          account={account}
          onPress={this.onMessagePress.bind(this, item)}
        />
      </SwipeRow>
```
And `ListItem` is using `TouchableHighlight`

**Comment by jemise111** [comment]
Closing as inactive
