### ISSUE TITLE
Per-row feature not working in production

### ISSUE THREAD

**Issue by npomfret** [jemise111/react-native-swipe-list-view#45]
I'm getting an error when deployed to an iPhone in production mode.  The behaviour seems to be different than when connecting to a local npm server.

I'm trying to use the new per-row features, but they're failing when I deploy it to TestFlight with this error:

`Fatal Exception: RCTFatalException: Unhandled JS Exception: this.props.renderHiddenRow is not a function. (In 'this.props.renderHiddenRow(e,o,s,this._rows)', 'this.props.renderHiddenRow' is undefined)
`

It's a guess, but I think maybe this is failing:

`if (Component.type.name === 'SwipeRow') {`

Is it possible that the deployment (minification?) process destroys the name, and so this statement never resolves to `true`? Perhaps instead use `if(!this.props.renderHiddenRow) {...`?

**Comment by npomfret** [comment]
This works: https://github.com/jemise111/react-native-swipe-list-view/pull/46

**Comment by jemise111** [comment]
Fixed by #46
