### ISSUE TITLE
SwipeRow cannot render View inside View

### ISSUE THREAD

**Issue by isThereAnyF-ingNameAvailable** [jemise111/react-native-swipe-list-view#451]
This code shows a problem I'm having with rendering a View inside a View. If I use renderItem1(item) I will get the error depicted below. If I instead use renderItem2(item) it will work fine (it will look horrible but that's not the issue now). br Knut
```
import React, { Component } from 'react';
import {
  AppRegistry,
  Text,
  View,
} from 'react-native';
import { SwipeListView, SwipeRow } from 'react-native-swipe-list-view';

const list = [
  { id:"AE:AE:AE", name: "DEV1" },
  { id:"BE:BE:BE", name: "DEV2" },
  { id:"CE:DE:EE", name: "DEV3" },
  { id:"DE:DE:DE", name: "DEV4" },
  { id:"EE:EE:EE", name: "DEV5" },
  { id:"FE:FE:FE", name: "DEV6" },
]

function  renderItem1(item) {
  /* Error.  <View><View></View></View>*/
  return (
    <SwipeRow>
      <View>
        <Text>{item.name}</Text>
       
        <View>
          <Text>{item.id}</Text>
        </View>
      </View>        
    </SwipeRow>
  );
}

function  renderItem2(item) {
  /* Good.  <View></View><View></View>*/
  return (
    <SwipeRow>
      <View>
        <Text>{item.name}</Text>
      </View> 
        <View>
          <Text>{item.id}</Text>
        </View>
            
    </SwipeRow>
  );
}

export default function App(props) {
  return (
    <SwipeListView
        data={list}
        renderItem={({ item }) => renderItem1(item) }
        keyExtractor={item => item.id}                  
    />
  );
}

AppRegistry.registerComponent('default', () => App);
```
![Screenshot_20180313-152640_BLE Central](https://user-images.githubusercontent.com/63792001/79456647-29989c00-7fef-11ea-9210-9e6003548211.jpg)

**Comment by isThereAnyF-ingNameAvailable** [comment]
oh - adding…
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 8.66 GB / 15.68 GB
  Binaries:
    Node: 13.7.0 - C:\Program\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.6 - C:\Program\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 1.8.0_211
    Python: 3.8.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0
    react-native: ^0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

react-native-swipe-list-view@2.5.0

**Comment by jemise111** [comment]
Hi @isThereAnyF-ingNameAvailable Please see the docs for SwipeRow here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeRow.md

You must pass ***exactly*** two children. You cannot pass one top level View.

Please let me know if you have more questions, closing for now..

**Comment by isThereAnyF-ingNameAvailable** [comment]
Ok, I see this: "Row that is generally used in a <SwipeListView/>. If you are rendering a <SwipeRow/> explicitly you must pass the <SwipeRow/> exactly two children. The first will be rendered behind the second. e.g." So I see now why there was a difference. The problem now is that I'm instantiating SwipeRow via the renderItem function in SwipeListView. SwipeListView solves the rendering of visible and hidden component by two function pointers. The requirement for two children in ListRow I assume is for using it in standalone mode (=not wrapped in SwipeListView). ListRow doesn't "know" that it was created by SwipeListView. Is there a prop to tell ListRow that it is or isn't a standalone? If not, there probably should be? Issue #2: IMHO I think using two function pointers like renderItem and renderHiddenItem is a better approach. Then you could set renderHiddenItem={null} and not attempt to render it. In many situations (and all of mine) you don't need or want a hidden object, but just the ability to swipe-to-delete. I understand this is a feature request and not a bug report, but as a user I wanted to bring it to your consideration. Thanks and keep up the good work! /Knut

**Comment by jemise111** [comment]
Hey @isThereAnyF-ingNameAvailable, this applies no matter where you use the swipe row, as a standalone or as part of the list view

As for your second request, pull requests are always welcome :)
