### ISSUE TITLE
SwipeListView useSectionList={true} imports undefined SectionList

### ISSUE THREAD

**Issue by cHaLkdusT** [jemise111/react-native-swipe-list-view#453]
**Describe the bug**
SwipeListView returns null when useSectionList props is `true`

**To Reproduce**
```
<SwipeListView useSectionList={true} data={DATA} ...
```

Sample data:
```
const DATA = [
  {
    title: 'Main dishes',
    data: ['Pizza', 'Burger', 'Risotto'],
  },
  {
    title: 'Sides',
    data: ['French Fries', 'Onion Rings', 'Fried Shrimps'],
  },
  {
    title: 'Drinks',
    data: ['Water', 'Coke', 'Beer'],
  },
  {
    title: 'Desserts',
    data: ['Cheese Cake', 'Ice Cream'],
  },
];
```

**Screenshots**
<img width="638" alt="Screen Shot 2020-04-17 at 23 49 21" src="https://user-images.githubusercontent.com/2569355/79589126-825b5800-8107-11ea-833e-6dd8692b3cbb.png">

**Environment (please complete the following information):**
 - OS: iOS and Android
 - RNSLV Version: v2.5.0
 - RN Version: v0.62.1

**Comment by jemise111** [comment]
Hi @cHaLkdusT, this is just a problem with the debugger, not the library. If you over over `SectionList` you'll see it is definitely not undefined.

Also in `examples/sectionlist.js` everything is working just fine

![image](https://user-images.githubusercontent.com/4265163/79688838-a0fc4480-8216-11ea-8075-355eb0cfec46.png)
