### ISSUE TITLE
Swipe to Delete item with Redux

### ISSUE THREAD

**Issue by Dannark** [jemise111/react-native-swipe-list-view#455]
Hey Guys, Whats is up! Awesome job on this lib, I'm in love with it. I just need some help, i might be doing something wrong here.

**Describe the bug**
So, when I swipe the last item of the list, it seems to works fine all the animation. But if I swipe any others items on the list, the next item gets deleted instead of the one i choose! But if i re-open this screen, everthing is okay, so it is probably on the render logic i guess. Maybe something to do with keyExtractor?

**My code**
```
export default props =>{
    const data = useSelector(state => state.caloriesFood)
    const dispatch = useDispatch()
    
    const onSwipeValueChange = swipeData => {
        const { key, value } = swipeData;
        
        if (
            value == Dimensions.get('window').width
        ) {
            console.log("deleting item ["+key+"]")
            
            dispatch({type: 'REMOVE_FOOD', key})
        }
    };
    
    return(
        <SwipeListView 
            data={data}
            renderItem={({ item, index }) => 
                <ButtonList
                    onPress={onclick()} name={item.name} time={item.time} foods={item.foods} />
            }
            keyExtractor={(item, index) => ""+index}
            disableLeftSwipe
            leftOpenValue={Dimensions.get('window').width}
            onSwipeValueChange={onSwipeValueChange}
            renderHiddenItem={ (item, index) => (
                <View style={s.rowBack}>
                    <EvilIcons name="trash" size={30} color={Config.primaryColor.color}  />
                    <Text style={{color:'white'}}>Deletado!</Text>
                </View>
            )}
            //leftOpenValue={75}
            //rightOpenValue={-75}
        />
    )
}
```

**Screenshots**
![erro](https://user-images.githubusercontent.com/7622553/80010610-0a8f8380-84a1-11ea-9a77-905ade1944a0.gif)

**Environment (please complete the following information):**
 - OS: [Android Emulator]
 - RN Version: [v0.62]

**Comment by Dannark** [comment]
I just figured it out. It was actualy the index of the array that changes when I remove the item. So if i have the array:

> [0,1,2,3,4...] 

by removing the item **2**, the item **3** and **4** now becomes **2** and **3**... So i changed the `keyExtractor `to use a random Id instead a sequential, then i can later search the key on the list and find the index of it.

**Comment by daweimau** [comment]
> So i changed the keyExtractor to use a random Id

Better to use an actual item `id` if it is available 😁
