### ISSUE TITLE
leftActivationValue along with onLeftActionStatusChange are not working

### ISSUE THREAD

**Issue by sshenoy700** [jemise111/react-native-swipe-list-view#458]
When i set leftActivationValue, and swipe to that value, onLeftActionStatusChange is not firing. Please check this.

**Comment by skylerrichter** [comment]
I think you need to update to version 3.0.0.

**Comment by jemise111** [comment]
@sshenoy700 Can you list the version you are using?

**Comment by jemise111** [comment]
Assuming this was just a versioning issue, please feel free to re-open if that's not the case, thanks!

**Comment by Jurpp** [comment]
Hi! I've experienced this issue aswell. I fixed it by just trying things and never had een issue with it again until today. Luckily I'm able to reproduce the behaviour now. 
When using this setup:
```                    
<MaskedView maskElement={<MyFadeElement/>} style={styles.mask}>
    <SwipeListView
        useFlatList={true}
        data={myList}
        initialNumToRender={15}
        useAnimatedList={true}
        useNativeDriver={true}
        keyExtractor={(item) => String(item.id)}
        renderItem = {(rowData, rowMap) =>  
            <SwipeRow 
                        useNativeDriver={true} 
                        disableRightSwipe={!rowData.item.swipeable} 
                        disableLeftSwipe = {true}                             
                        leftOpenValue={50} 
                        stopLeftSwipe={125} 
                        leftActivationValue={100} 
                        leftActionValue={-2}
                        onLeftActionStatusChange={(data) => onItemSwiped(data)}>
                             <HiddenItemWithActions rowData={rowData}/>
                             <MyItem item={rowData.item}/>
            </SwipeRow>
        }
        style={styles.flatlist}
    />
</MaskedView>
```
onLeftActionStatusChange does NOT fire. 

When I comment out the MaskedView, onLeftActionStatusChange directly starts working. I can then even uncomment the MaskedView to re-enable my fade effect and onLeftActionStatusChange keeps working! However, as soon as I reload the app the callback stops working again.

To me this is very weird behaviour, I hope it makes some more sense to you @jemise111 and maybe you'll be able to figure out what is going wrong.

I'm using version **3.2.6** of this library and I am developing on an Android device.
