### ISSUE TITLE
Add `SwipeRow.isOpen` type

### ISSUE THREAD

**Issue by PrescottJRynewicz** [jemise111/react-native-swipe-list-view#459]
# Add `SwipeRow.isOpen` type. 

Quick one for you (love the library btw). Was hoping to add a type for the `isOpen` class value on `SwipeRow`. 

```
export class SwipeRow<T> extends Component<Partial<IPropsSwipeRow<T>>> {
        isOpen: boolean;
	closeRow: () => void;
	closeRowWithoutAnimation: () => void;
	render(): JSX.Element;
	manuallySwipeRow: (toValue: number, onAnimationEnd?: () => void) => void;
}
```

Thanks!

**Comment by jemise111** [comment]
Hey @PrescottJRynewicz turns out I already had the property set up, just had to add it to types!
