### ISSUE TITLE
Turn preview off

### ISSUE THREAD

**Issue by espadon54** [jemise111/react-native-swipe-list-view#460]
Hi, I have looked at other issues and tried to turn off the row preview. I am using the 3.0.0 release with react-native@0.62.2.

Tried to pass previewRowKey to false, to play with previewDuration and previewOpenDelay values. But unfortunately the preview is always display when I press a row (tested on IOS only for now).

What is the proper way to disable the preview?

Thanks for your help.

**Comment by jemise111** [comment]
Hi @espadon54 I'm trying this in my own app and not seeing the same behavior. If I remove all "preview" related props the row never opens until I swipe. Can I see the code you're using? An example video would be super helpful too, thanks!

**Comment by espadon54** [comment]
Hi, thanks, this is how I use it.

`<SwipeListView
  data={Object.values(rooms).filter(room => room && 
  room.name.toLowerCase().includes(search.toLowerCase()))}
   renderItem={(data, rowMap) => this.renderItem(data)}
  renderHiddenItem={ (data, rowMap) => this.renderHiddenItem(data)}
  rightOpenValue={-75}
  stopLeftSwipe={0}
/>`

**Comment by jemise111** [comment]
@espadon54 Hm there's really no reason that should run a preview at all. If it's possible can you debug a little more by adding some breakpoints and see if this block of code is running? 

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L238

**Comment by jemise111** [comment]
Closing as inactive
