### ISSUE TITLE
nativeDriver issues with Release 3.0.0

### ISSUE THREAD

**Issue by Hirbod** [jemise111/react-native-swipe-list-view#461]
After upgrading to 3.0.0, I get "Style property 'height' is not supported by native animated module".

I've set useNativeDriver to false on my interpolation, but now it complains "Attempting to run JS driven animation node that has been moved to "native" earlier.

Then I've seen that you've added "useNativeDriver" to SwipeListView in your Readme, but useNativeDriver isn't even exported and Typescript is also complaining and it looks whatever I'm setting there (true or false) it drops the same errors. My application works great with v2+ for 6 months now. Here are some BCs now which I can't resolve.

**Comment by Hirbod** [comment]
<img width="699" alt="Bildschirmfoto 2020-05-01 um 15 25 55" src="https://user-images.githubusercontent.com/504909/80808544-145f6800-8bc0-11ea-86fc-d50ffc445108.png">


Looks like it is actually working but reporting like its not existing. I had a useNativeDriver for my renderHiddenItem, fixed it, not its working.

**Comment by jemise111** [comment]
Hey @Hirbod just to be clear, this is solely a typescript compiler warning issue now?

Also, I don't use Typescript often. It would be super helpful if you could tell me how to repro this locally and I can attempt to fix, thanks!

**Comment by Hirbod** [comment]
@jemise111 yes it is a Typescript warning - nothing more. I’m also pretty new into TypeScript but it looks like something is not exported correctly since it’s the only prop my compiler yells at. 

At the end, the internals indeed did change since you’ve added the native driver but I was able to fix it since I am using a height animation which isn’t supported by native. My renderHiddenItem had an „react-native-animatable“ view with native driver (which was working before because it was just opacity) but since the internals render them without driver support now, you can’t use any native driver in that specific component and vice versus.

**Comment by jemise111** [comment]
Ok I think I was also missing `useNativeDriver` in SwipeListView props in the types file, should be fixed now, thanks!
