### ISSUE TITLE
useNativeDriver : true doesn't work in onScroll Animated.event() 

### ISSUE THREAD

**Issue by masum-mollik** [jemise111/react-native-swipe-list-view#468]
At first, thanks for your awesome library. But, this was good until I used the ` { useNativeDriver: true }` in the Animated.event and generate the following error:
```
  <SwipeListView
  ...
  useAnimateList={true}
  useFlatList
  // @ts-ignore
  useNativeDriver={true}
  onScroll={Animated.event(
    [
      {
        nativeEvent: {
          contentOffset: { y: this.state.ScrollValue },
        },
      },
    ],
    { useNativeDriver: true }
  )}
  ...
/>;
```

![index](https://user-images.githubusercontent.com/42398581/82721516-8585cd00-9cdf-11ea-862a-30b5b785c6b1.jpg)

As I can't use NativeDriver, my animation in the header is missing frames. I'm waiting for your response. Thank you

**Comment by jemise111** [comment]
Hey @masum-mollik looks like you just misspelled the prop name. It's `useAnimatedList`, not `useAnimateList`
