### ISSUE TITLE
Different open values for different rows

### ISSUE THREAD

**Issue by BlindDev** [jemise111/react-native-swipe-list-view#477]
Hi. Thank for this library. Great Job!

I wonder if I can specify different open values for swiping.

In my project in the swipe list I may have rows that should have different amount of actions:
1. one action on the right side and one on the left
2. one acton only on the right side
3. one action on the right, two actions on the left

So I need to somehow specify different leftOpenValue, stopLeftSwipe, rightOpenValue, stopRightSwipe for different types of rows or even prevent swiping for some of them in the same list. 

Is there any solution

**Comment by BlindDev** [comment]
Oh, sorry, my bad, I've found how to do that.

**Comment by thanhluantl2304** [comment]
why didn't you show how???

**Comment by BlindDev** [comment]
It is in the doc.
You can use SwipeRow with specific 'leftOpenValue' and 'rightOpenValue'
https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeRow.md

**Comment by code-by** [comment]
how to automatically close the row when user begin to swipe another one? with `SwipeListView` it is doing automatically, but not in case of `SwipeRow`
