### ISSUE TITLE
Prevent preview from repeat after re-render

### ISSUE THREAD

**Issue by olegbraginmmc** [jemise111/react-native-swipe-list-view#479]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/jemise111/react-native-swipe-list-view/issues) before creating one.

**Describe the bug**
Use the SwipeRow component standalone. Set the preview as `true` and previewRepeat as `false`. After any re-render caused my a parent view the preview is shown again. 

**Environment (please complete the following information):**
 - OS: iOS 13.5
 - RNSLV Version: 3.1.0
 - RN Version: 0.62.2

**Comment by jemise111** [comment]
Hey @olegbraginmmc do you have some example code you can show me that would reproduce this behavior? Thanks!

**Comment by jemise111** [comment]
Closing as inactive
