### ISSUE TITLE
Usage with Navigator react-native-navigation

### ISSUE THREAD

**Issue by kendrickkesley** [jemise111/react-native-swipe-list-view#48]
Hi! I was using your library and realized that something wrong when I implement it on tabBar using 
react-native-navigation 
https://github.com/wix/react-native-navigation

I use the same component and the backRow is not rendered in the second tab and above. But in the first tab, it's rendered perfectly (I'm using your example as the component)

Is it a bug or did I do something wrong?

**Comment by kendrickkesley** [comment]
I managed to fix this by using props 
recalculateHiddenLayout={true}

Is this a correct practice?

**Comment by jemise111** [comment]
Hey @kendrickkesley yep using that prop is just fine. It's a small performance optimization to set that prop to false. But if you are re-rendering swipe rows that could have different sizes (which it sounds like you are) then this prop should be set to true.

Closing this issue, please reopen if you still have problems!

**Comment by kendrickkesley** [comment]
Thank you! @jemise111 btw your library is awesome!

**Comment by jemise111** [comment]
@kendrickkesley Thanks so much! Glad it's working for you

**Comment by bjacog** [comment]
@umut885 The prop is for the SwipeRow, see docs here: https://github.com/jemise111/react-native-swipe-list-view/blob/95a47b0a96a07471987b6bdaf45bd0819e6261ed/docs/per-row-behavior.md
