### ISSUE TITLE
Swipe to delete locks vertical movement of the Swipelistview

### ISSUE THREAD

**Issue by mikeslinkman** [jemise111/react-native-swipe-list-view#481]
**Describe the bug**
Swiping and then deleting the element from the list seems the vertical movement from the list until another row is swiped. So it seems the movement stays locked until another row is swiped (even if it is just a little).

**To Reproduce**
- Construct a list of elements
- Swipe to delete an item from the data array (redux controlled list)
- try to scroll vertically **(Now it doesn't work)**
- Now swipe another element (just a little)
- try to scroll **(Now it works)**

**Environment (please complete the following information):**
 - OS: iOS & Android
 - RNSLV Version: v3.1.2
 - RN Version: v0.62.2

**Comment by jemise111** [comment]
Hey @mikeslinkman would you be able to post some code or better yet a reproducible example I could play with? Everything is working fine in my own examples so I need to see what you're doing differently, thanks!

**Comment by mikeslinkman** [comment]
Hi,

Hopefully I get some time later to work on a reproducible example but for now I'll post the code.

```
`<SwipeListView
        disableLeftSwipe
        data={offlineRoutes}
        style={styles.container}
        keyExtractor={(item, index) => item.routeID}
        onSwipeValueChange={(data) => handleChange(data)}
        renderHiddenItem={(data) => renderHiddenItem(data)}
        renderItem={({item, index}) => renderItem(item, index)} />
```
The data variable is a redux controlled data array.

```
 const renderHiddenItem = () => {
    return (
      <RectButton style={styles.rectButton}>
        <Image style={{paddingTop: 10}} source={TRASH_IMAGE} />
      </RectButton>
    );
  };
```

```
  const renderItem = (item, index) => {
    return <RouteListItem key={index} item={item} />;
  };
```

```
export const RouteListItem = ({item}) => {
  return (
    <ListItem
      style={{padding: 0}}
      title={
        <Text numberOfLines={2} style={styles.h2}>
          {item.title}
        </Text>
      }
      subtitle={
        <View>
          <Text style={styles.subtitle}>
            {Math.round(item.length)} km / {Math.round(item.duration)} h
          </Text>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
              justifyContent: 'flex-end',
            }}>
            <Rating
              readonly
              type="custom"
              imageSize={10}
              startingValue={item.rating}
              ratingImage={GRAYSTAR_IMAGE}
              ratingColor={Colors.textGray}
              ratingBackgroundColor="#b1b1b1"
            />
          </View>
        </View>
      }
      leftElement={
        <View>
          {item.picture && item.picture.length ? (
            <Image
              source={{
                uri: `data:image/png;base64,${item.picture[0].picture}`,
              }}
              style={styles.thumbnail}
            />
          ) : (
            <Image source={DEFAULT_IMAGE} style={styles.thumbnail} />
          )}
          <View style={styles.overlay} />
        </View>
      }
      rightElement={
        <View>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
              justifyContent: 'flex-end',
            }}>
            <Text style={styles.distance}>
              {Math.round(item.distance)} km{'\n'}away
            </Text>
          </View>
        </View>
      }
    />
  );
};
```

**Comment by jemise111** [comment]
@mikeslinkman I don't see anything obvious that would cause this to not work. If you want a working example of using `onSwipeValueChange` to handle deleting rows (I just double checked) you can check out this file and see if there's something in there that looks different from what you're doing https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/swipe_to_delete.js#L27

Otherwise can I see your `handleChange` function?

**Comment by mikeslinkman** [comment]
Hi,

Thanks for getting back to me. As far as I can tell not too much is different except for the handling of the actual deleting, since I'm using redux. I'll add the relevant portion of the handleChange which only exclude some calls to delete actual content from the device.

```
const handleChange = (data) => {
    const {key, value} = data;
    const target = `${RNFS.DocumentDirectoryPath}/Route${key}/`;
    const screenWidth = Math.round(Dimensions.get('window').width / 2);

    if (value > screenWidth) {
      animationRunning = true;
      // Filter the element out of the array so we keep everything except the just deleted route
      const routes = offlineRoutes.filter((item) => item.routeID !== key);
     // Dispatch to our reducer so that the list will be updated
      dispatch(setOnDeviceRoutes(routes));

      animationRunning = false;
    }
  };
```

I only tried removing the animation running part of the code from the if check but re-adding it doesn't result in the desired behavior.

**Comment by jemise111** [comment]
Okay I think I get what's going on now. Usually when the row finishes swiping but before it is removed it will trigger a function to re-enable scrolling on the parent ListView. However in your case I think your redux action is removing the row before the animation actually finishes. Can I ask you to try to manually re-enable scrolling and see if that fixes it. Here's an example:

```
<SwipeListView
        listViewRef={ref => this.swipeListViewRef = ref}             <===== ADD THIS LINE
        disableLeftSwipe
        data={offlineRoutes}
        style={styles.container}
        keyExtractor={(item, index) => item.routeID}
        onSwipeValueChange={(data) => handleChange(data)}
        renderHiddenItem={(data) => renderHiddenItem(data)}
        renderItem={({item, index}) => renderItem(item, index)} />
```

```
const handleChange = (data) => {
    const {key, value} = data;
    const target = `${RNFS.DocumentDirectoryPath}/Route${key}/`;
    const screenWidth = Math.round(Dimensions.get('window').width / 2);

    if (value > screenWidth) {
      animationRunning = true;
      // Filter the element out of the array so we keep everything except the just deleted route
      const routes = offlineRoutes.filter((item) => item.routeID !== key);
     // Dispatch to our reducer so that the list will be updated
      dispatch(setOnDeviceRoutes(routes));

      animationRunning = false;
     
      // WHENEVER THE ANIMATION FINISHES...
     this.swipeListViewRef.getScrollResponder().setNativeProps({ scrollEnabled: true }); // <====== ADD THIS
    }
  };
```

We can maybe come up with a more elegant solution but this would confirm the problem

Thanks!

**Comment by mikeslinkman** [comment]
I'm not near my computer so I'll try it tomorrow. Thanks for the help so
far and I'll get back when I've tried it.

**Comment by mikeslinkman** [comment]
Hi

Just getting back now after I've tried your solution to identify the problem. Doing the above mentioned I was able to solve the issue for both iOS and Android. Although there might be better solutions (don't know one yet) this feels perfectly fine for now. So as far as I'm concerned this issue can be seen as closed

**Comment by jemise111** [comment]
Awesome! One way you could achieve this wouldn't manually re-enabling scrolling is to allow the animation to fully finish before you dispatch your setOnDeviceRoutes action.. just a thought.

Glad it's solved

**Comment by mikeslinkman** [comment]
After I had my morning coffee I also got to that solution and I think that would make more sense. Thanks for the support helped me a lot!
