### ISSUE TITLE
"Animated: 'useNativeDriver' was not specified" in swipe_to_delete example.

### ISSUE THREAD

**Issue by yu-221** [jemise111/react-native-swipe-list-view#482]
The "swipe_to_delete" example gives a warning message, so I propose the fix like this just for the better developer's experience.

https://github.com/jemise111/react-native-swipe-list-view/blob/4a701757398dc26a4c888555860df4a7287d7282/SwipeListExample/examples/swipe_to_delete.js#L34-L37

```diff
            Animated.timing(rowTranslateAnimatedValues[key], {
                toValue: 0,
                duration: 200,
+              useNativeDriver: false
            }).start(() => {
```

**Comment by jemise111** [comment]
Thank you, sounds great! Would you like to submit a PR for this?

**Comment by jemise111** [comment]
@yu-221 nevermind, just took care of this one in v3.1.3
