### ISSUE TITLE
Add bottom button for loading more record

### ISSUE THREAD

**Issue by minhthien309** [jemise111/react-native-swipe-list-view#483]
Hello everybody, i'm create a list with button to load more record in bottom of list, but i see this component was not supported this. I wonder how i can do it?

**Comment by filipe-valente** [comment]
Hello. SwipeListView supports FlatList so you can use FlatList props.
In your case, you can use ListFooterComponent to render a "Load more" button that will fetch more data. Then all you have to do is concat the new data to the state like this for example (will depend on the data structure so don't take this literally):
`setData(prevValue => ([...prevValue, ...newData]));`

**Comment by minhthien309** [comment]
Thank you very much

**Comment by jemise111** [comment]
Hey @minhthien309, @filipe-valente is absolutely right. This library is just a wrapper around a plain `FlatList` (or `SectionList`), anything you can do with those lists you can do with this library. I'm going to close this, but if you need example code or anything LMK
