### ISSUE TITLE
Invariant Violation: ListView has been removed. 

### ISSUE THREAD

**Issue by Traced** [jemise111/react-native-swipe-list-view#484]
Invariant Violation: ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview`.

pleach help me, how can fix?

**Comment by jemise111** [comment]
Hi @Traced are you using the latest version of this library? There shouldn't be any more traces of `ListView`

**Comment by jemise111** [comment]
Closing as inactive

**Comment by ThuyDang88** [comment]
I got the same issue with latest version of this library.
"react-native-swipe-list-view": "^3.2.5"
Please help me check it?
