### ISSUE TITLE
swipeGestureEnded doesn't pass arguments to its function

### ISSUE THREAD

**Issue by valsan** [jemise111/react-native-swipe-list-view#487]
**Describe the bug**
Hi, I'm trying to get swipe values inside swipeGestureEnded. The code:
```
<SwipeRow
      ref={rowRef}
      leftOpenValue={SWIPE_ACTION_WIDTH}
      // stopLeftSwipe={SWIPE_MAX_WIDTH}
      rightOpenValue={-SWIPE_ACTION_WIDTH}
      // stopRightSwipe={-SWIPE_MAX_WIDTH}
      disableRightSwipe={expanded || !read}
      disableLeftSwipe={expanded}
      tension={70}
      onRowOpen={() => { setIsSwipeRowOpen(true) }}
      onRowDidClose={() => { setIsSwipeRowOpen(false) }}
      swipeGestureBegan={() => { setIsSwiping(true) }}
      swipeGestureEnded={evt => {
        setIsSwiping(false);
        console.log(evt);
      }}
      onSwipeValueChange={({ value }) => setSwipeValue(value)}
    >
```

I expected the log to print an object 
`{ rowKey: string; data: { translateX: number; direction: 'left' | 'right'; event: GestureResponderEvent; gestureState: PanResponderGestureState; } }`

**Environment (please complete the following information):**
 - OS: iOS and Android
 - RNSLV Version: v3.1.3
 - RN Version: v0.62.2

Can someone help me?

A workaround: get swipe values from `onSwipeValueChange` inside the `swipeGestureEnded` using some state.

**Comment by jemise111** [comment]
Hey @valsan I think you misread the docs for that func, there are actually two args passed to the `swipeGestureEnded` prop. Change your code to this and you should be good to go:

```
<SwipeRow
      swipeGestureEnded={(key, evt) => {
        setIsSwiping(false);
        console.log(evt);
      }}
>
```
