### ISSUE TITLE
Expose "open" or "close" state to renderRow or renderHiddenRow

### ISSUE THREAD

**Issue by chandlervdw** [jemise111/react-native-swipe-list-view#49]
If I wanted my SwipeRow to do one thing when tapped while the row is closed and another while it's open (say, close the row), is that possible with how things stand?

**Comment by jemise111** [comment]
Exposing methods to check row state is a great idea! (and a PR is always appreciated :) but as it stands that doesn't exist. However I think you could achieve this with the onRowOpen / onRowClosed props. If you're using a SwipeListView something like this should do the trick:

```javascript
onPress(data, rowId, secId, rowMap) {
	const rowRef = rowMap[`${secId}${rowId}`];
	if (this.openRowId && this.openRowId === rowId) {
		rowRef.closeRow();
	} else {
		this.doSomeOtherOnPressAction();
	}
}

render() {
	return (
		<SwipeListView
			renderRow={ (data, rowId, secId, rowMap) => (
				<Touchable onPress={ _ => this.onPress(data, rowId, secId, rowMap) }>
				</Touchable>
			)}
			onRowOpen={ (rowId, secId, rowMap) => { this.openRowId = rowId } }
			onRowClose={ (rowId, secId, rowMap) => { this.openRowId = null } }
			closeOnRowPress={false} // we're managing this manually
		/>
	);
}
```

If it's just a plain SwipeRow (without the ListView) you may have to manage the open rowId differently but the approach should be similar.

Let me know if this works for you!

Also will definitely look into adding open / close states to individual rows.

**Comment by chandlervdw** [comment]
@jemise111 thanks for that! To note, I think your `onPress()` if statement needs
```
if (this.openRowId && this.openRowId === secId) { ... }
```

**Comment by jemise111** [comment]
@chandlervdw Yeah it depends if you're using sections or not. I believe if you just have one section then just using the rowId will be good for a unique identifier. But if you have rows with sections you may need to keep track of both.

Hope this solution worked for you! If it did let me know so I can close this issue, thanks!

**Comment by chandlervdw** [comment]
@jemise111 Yeah, it worked! Thank you so much. I will try to get a PR to you in the next couple of weeks.

**Comment by jemise111** [comment]
@chandlervdw awesome! Much appreciated
