### ISSUE TITLE
Incorrect height after orientation change.

### ISSUE THREAD

**Issue by jungleyu** [jemise111/react-native-swipe-list-view#491]
**Describe the bug**
Change orientation from portrait to landscape, then switch back, the multiple line text item's height is incorrect.

**Screenshots**
<img width="327" alt="Screen Shot 2020-07-20 at 20 08 48" src="https://user-images.githubusercontent.com/6914315/87936186-fc172f00-cac4-11ea-99ff-90ce5e7fea11.png">
<img width="716" alt="Screen Shot 2020-07-20 at 20 09 01" src="https://user-images.githubusercontent.com/6914315/87936204-046f6a00-cac5-11ea-9699-7af8b28210bd.png">
<img width="334" alt="Screen Shot 2020-07-20 at 20 09 11" src="https://user-images.githubusercontent.com/6914315/87936219-09ccb480-cac5-11ea-91a4-07161adc981a.png">

**Environment (please complete the following information):**
 - OS: iOS
 - RNSLV Version: latest
 - RN Version: v0.62.2

**Comment by jemise111** [comment]
@jungleyu have you tried passing `recalculateHiddenLayout={true}` to the `SwipeListView`?

**Comment by jungleyu** [comment]
@jemise111 No, I retried without RNSLV, and this issue still exist, I think it's something related Flatlist and TouchaleOpacity.
`const renderItem = ({item}) => (
    <TouchableOpacity>
      <View style={styles.listCardWrapper}>
        <View style={styles.listCardLeftContentWrapper}>
          <Text style={styles.listCardType}>FYI Note</Text>
        </View>
        <View style={styles.listCardRightContentWrapper}>
          <Text style={styles.listCardTitleText}>{item}</Text>
          <Text style={[styles.listCardTitleText, {color: 'red'}]}>Local</Text>
          <Text style={styles.listCardText}>Created: 08-Jul-2020 | 17:53</Text>
          <Text style={styles.listCardText}>Length: 00:13 min</Text>
        </View>
      </View>
    </TouchableOpacity>
  );` 
Once I using above code as Flatlist item, the height will be incorrect after rotate screen.

**Comment by jemise111** [comment]
@jungleyu Hm that's strange. Maybe something to do with `getItemLayout` or you could try passing `extraData` and forcing the FlatList to re-render on orientation changes.

Happy to look at some more code if you want to post more. But since this isn't an issue with the RNSLV itself I'm going to close this issue if that's cool

**Comment by spooksmus** [comment]
I'm seeing the same issue. When changing the orientation the height of the swipe row is incorrect and it causes some of the red background to be shown.

**Comment by mauhammadadnan** [comment]
Thanks Issue Resolved

**Comment by mauhammadadnan** [comment]
Issue Resolve by using  recalculateHiddenLayout={true}
