### ISSUE TITLE
Swiperow crashed after navigate to new view

### ISSUE THREAD

**Issue by developerZirkonzahn** [jemise111/react-native-swipe-list-view#492]
I use a Swiperow with 2 buttons, on one button i change view and when i go back to the previouse view my app crashes.

```
`<SwipeRow disableRightSwipe={true} rightOpenValue={-150} useNativeDriver={true}>
                <View style={styles.rowBack}>
                    <TouchableOpacity
                        style={[styles.backRightBtn, styles.backRightBtnLeft]}
                        onPress={() => onInfo() }
                    >
                        <Ionicons name="md-information" size={40} color='white' />
                    </TouchableOpacity>
                    <TouchableOpacity
                        style={[styles.backRightBtn, styles.backRightBtnRight]}
                        onPress={() => onDelete()}
                    >
                        <Ionicons name="md-trash" size={40} color='white' />
                    </TouchableOpacity>
                </View>
            </SwipeRow>`
```

**Comment by jemise111** [comment]
Hey @developerZirkonzahn do you have any info about the crash, what the error message is?

**Comment by developerZirkonzahn** [comment]
When i run it on Expo it doesn`t thorw an error, but if i build the app on ios and run it on testflight it crashs. In the crashlog it only sasy:

Exeption Type:  EXC_CRASH (SIGABRT)
Exeption Note: EXC_CORPSE_NOTIFY

**Comment by developerZirkonzahn** [comment]
the `onDelete` button works how it should, it only crashes when i change screen with the onInfo button.

**Comment by jemise111** [comment]
@developerZirkonzahn This is the first I'm ever hearing of this so I have a feeling this issue isn't related to this library, but happy to help you debug.. what's going on in the `onInfo` function?

**Comment by developerZirkonzahn** [comment]
i call `navigation.navigate` to navigate to the next view. nothing else

**Comment by developerZirkonzahn** [comment]
I used the old version of swipeout `react-native-swipeout` and everything worked fine. 

In my `homescreen` i use a Flatlist:
```
<FlatList
                    data={this.state.machineList}
                    onRefresh={() => this.onRefresh()}
                    refreshing={this.state.isFetching}
                    keyExtractor={item => this._keyExtractor(item)}
                    renderItem={({ item, index }) => {
                        return (
                            <MachineListItem machine={item} index={index} timestamp={(item.unit_id == 'werbung' ? null : this._calculateTime(item.lastCallback))}
                                onPress={() =>
                                    this.props.navigation.navigate('MachineDetailScreen', {
                                        machine: item,
                                        machineName: item.name,
                                        machineSerial: item.serial,
                                        queue: false,
                                        index: index,
                                        timestamp: this._calculateTime(item.lastCallback)
                                    })
                                }
                                onDelete={() => { this._removeMachine(item.unit_key) }}
                                onAd={() =>
                                    this.props.navigation.navigate("AdScreen", {
                                        link: item.link,
                                        title: item.title
                                    })
                                }
                                onInfo=
                                {() =>
                                    this.props.navigation.navigate('MachineInfoScreen', {
                                        image: item.machineImg,
                                        name: item.name,
                                        serial: item.serial,
                                        code: item.unit_key,
                                        type: item.type,
                                        service: item.services,
                                        timestamp: this._calculateTime(item.lastCallback)
                                    })
                                }
                            />
                        )
                    }}
                    ListEmptyComponent={() => (
                        <View>
                            <Text style={styles.listEmpty}>{I18n.t('homeScreen.emptyMilling')}</Text>
                        </View>
                    )}
                    ItemSeparatorComponent={() => <View style={styles.listSeparator} />}
                />
```

I pass every Item to the class `MachineListItem`, where I use `SwipeRow`.

**Comment by jemise111** [comment]
Hm I don't see anything wrong with the code. Is there anyway to run this in debug mode in Xcode and try to see more in the crash logs? Without more to go on this is tough to diagnose on this end

**Comment by developerZirkonzahn** [comment]
Maybe the Native Driver is causing a problem...

**Comment by developerZirkonzahn** [comment]
I rewrote my code and I use a SwipeListView now. How can I close ah row when i press a button, bc when I use `rowMap[rowData.item.key].closeRow()`, `rowData.item.key` is `undefined`.

`<SwipeListView
                    useNativeDriver={true}
                    data={this.state.machineList}
                    onRefresh={() => this.onRefresh()}
                    refreshing={this.state.isFetching}
                    keyExtractor={item => this._keyExtractor(item)}
                    renderItem={this._renderItem}
                    renderHiddenItem={this._renderHiddenItem}
                    rightOpenValue={-150}  
                    disableRightSwipe={true}
                />`

`_renderHiddenItem = (data) => (
        <View style={styles.rowBack}>
            <TouchableOpacity
                style={[styles.backRightBtn, styles.backRightBtnLeft]}
                onPress={() => {          <  ---   \\ close row here, before navigate
                    this.props.navigation.navigate('MachineInfoScreen', {
                        image: data.item.machineImg,
                        name: data.item.name,
                        serial: data.item.serial,
                        code: data.item.unit_key,
                        type: data.item.type,
                        service: data.item.services,
                        timestamp: this._calculateTime(data.item.lastCallback)
                    })
                }}
            >
                <Ionicons name="md-information" size={40} color='white' />
            </TouchableOpacity>
        </View>
    );`

**Comment by jemise111** [comment]
@developerZirkonzahn can you show me where in your code you're calling `rowData.item.key`, I don't see it above?

This should definitely be working, see here for a reference: https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/basic.js#L54

**Comment by developerZirkonzahn** [comment]
nvm, I could fix all my problems.
thanks.
