### ISSUE TITLE
TypeError: null is not an object (evaluating 'row.currentTranslateX)

### ISSUE THREAD

**Issue by ShayGit** [jemise111/react-native-swipe-list-view#493]
Hello, I'm new to React Native and I am making a food ordering app, I found this swipe list view very usefull for the Products in the CartScreen for having 3 buttons for each product item when swiping, buttons are for editing the items in the cart.
each product has 'add', 'edit' and 'remove' button. Using each one of them updates the state array of products such as: 
'add' duplicates the specified item and adds it to the list, 'edit' navigating to a screen for editing the product, and 'remove' removes the item from the list.
I am also using a ref of the swipelistview to open all rows and close all rows on 'edit' button click.

**Describe the bug and reproducing**
When adding some products to the cart, then at some point pressing the 'edit' button to open all rows,
then ranodomly pressing some product's 'add' button -> then 'remove' button -> then the 'edit' button of the item that replaces the item that was removed. I am getting this error:  TypeError: null is not an object (evaluating 'row.currentTranslateX)
I hope the error is relevant for this library and not some silly mistake I made.

**Screenshots**
![image](https://user-images.githubusercontent.com/26070570/89060510-d105c880-d36b-11ea-95a4-46c9e72d6513.png)

![ezgif com-resize](https://user-images.githubusercontent.com/26070570/89062259-cdc00c00-d36e-11ea-9947-837e71926748.gif)

My code: 
'edit' button press makes isEditMode state true and rerenders screen, then in useEffect:
editItems is the swipelistview reference

  useEffect(() => {
    if (editItems) {
      isEditMode
        ? editItems.manuallyOpenAllRows(-180)
        : editItems.closeAllOpenRows();
    }
  }, [isEditMode]);

// Context Consuming
const {
    state: { totalPrice, products },
    emptyCart,
    addOneMoreProduct,
    deleteProduct,
  } = useContext(CartContext);

![image](https://user-images.githubusercontent.com/26070570/89063904-a7e83680-d371-11ea-86d3-bc212899bb87.png)
![image](https://user-images.githubusercontent.com/26070570/89063968-c4846e80-d371-11ea-8d4e-9ca1ed558b13.png)
![image](https://user-images.githubusercontent.com/26070570/89064050-ec73d200-d371-11ea-9b9b-f4d9215fabd2.png)
![image](https://user-images.githubusercontent.com/26070570/89064100-044b5600-d372-11ea-9e63-4f91ab05cc63.png)

====
const styles = StyleSheet.create({
  listContainer: {
    flex: 3,
    borderWidth: 1,
    marginHorizontal: 1,
  },
rowBack: {
    alignItems: "center",
    backgroundColor: "white",
    flex: 1,
    flexDirection: "row",
  },
  backRightBtn: {
    width: 60,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 0,
    bottom: 0,
  },

  backTextWhite: {
    fontFamily: "Heebo_500Medium",
    fontSize: 14,
    color: "black",
    alignSelf: "center",
  },
}

And in CartContext.js: 
![image](https://user-images.githubusercontent.com/26070570/89063343-ac601f80-d370-11ea-8a6b-3d42a9420e4f.png)

The Reducer: 
![image](https://user-images.githubusercontent.com/26070570/89063278-8b97ca00-d370-11ea-96ec-6717dfb3fd9f.png)

Hope you can help me find the problem :)

**Environment (please complete the following information):**
 I am using Expo
 - OS: Android emulator and phone ( not checked on ios yet )
 - RNSLV Version: ^3.2.3
 - RN Version: 0.62.2

**Comment by Samtruc** [comment]
I also encountered this error. I think it is because of the "closeAllOpenRows()" method that cannot handle something in your way of manipulating items of the list.
In my project, I didn't provide the possibility to open all rows at the same time. I also stopped using the "closeAllOpenRows()" method and use "safeCloseOpenRow()" instead.
Not sure if it will really help you fixing your issue though.

**Comment by jemise111** [comment]
Hey @ShayGit, I think @Samtruc is right. I think after removing an item from the list the `closeAllOpenRows()` is still trying to close a row that doesn't exist. I just merged a PR that should hopefully fix this issue. It will go out with the next release

Apologies for the delay in responding

**Comment by jemise111** [comment]
Closing as resolved
