### ISSUE TITLE
App crashes when trying to close multiple rows

### ISSUE THREAD

**Issue by GwFreak01** [jemise111/react-native-swipe-list-view#494]
Recently, I implemented your new feature for `manuallyOpenAllRows` which works mostly, but I ran into some strange issue where if I try to swipe to close multiple rows in quick succession, I get a `Maximum call stack size exceeded`.

It keeps repeating this:

{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7237":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7305":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7309":{},"7312":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7313":{},"7314":{},"7316":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7319":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7320":{},"7323":{},"7326":{},"7327":{},"7328":{

**Some reference code**

```
const onRowDidClose = rowKey => {
    swipeListRef.current.closeAllOpenRows();
    dispatch({
      type: 'UPDATE_OPEN_ALL_ROWS',
      openAllRows: false,
    });
  };

<SwipeListView
        ref={swipeListRef}
        useFlatList={true}
        data={state.surgicalCases}
        keyExtractor={(data, index) => {
          return data.surgery_id;
        }}
        renderItem={renderItem}
        renderHiddenItem={renderHiddenItem}
        leftOpenValue={75}
        rightOpenValue={-150}
        previewRowKey={'0'}
        previewOpenValue={-40}
        previewOpenDelay={3000}
        onRowDidOpen={onRowDidOpen}
        onRowDidClose={onRowDidClose}
        closeOnRowOpen={false}
      />
```

**Comment by jemise111** [comment]
Hi @GwFreak01 I just ran this code in my own example and I'm not seeing any issues, I think I need to see more of your code to be able to help here. e.g. what is the dispatched action doing?

Apologies for the delay in responding

**Comment by jemise111** [comment]
Closing as inactive, please feel free to reopen when you can respond to the above, thanks!
