### ISSUE TITLE
Can't get swipe to delete in class component

### ISSUE THREAD

**Issue by avishags** [jemise111/react-native-swipe-list-view#497]
Hi,
I'm using the swipe list for a todo list, where swiping will get the item done.
I'm not using hooks as an example, but classes. And when I'm using setState for the new updated list the item doesn't disappear, instead the row stays green.
Also it seems like it get into a recursive state (doing some logging seems like the list get to 0 items).
I'm new to recat native, so it might be something very basic, but I've been spending few days on this.
Can you please help?

const onSwipeValueChange = swipeData => {
    const { key, value } = swipeData;
    if (
        value < -Dimensions.get('window').width 

    ) {
       // this.animationIsRunning = true;
        Animated.timing(rowTranslateAnimatedValues[key], {
            toValue: 0,
            duration: 50,
        }).start(() => {
            const newData = [...this.state.listData];
            const prevIndex = this.state.listData.findIndex(item => item.data.key === key);
            newData.splice(prevIndex, 1);
            this.setState( {listData: newData });
           // this.animationIsRunning = false;
        });
    }
};
![image0](https://user-images.githubusercontent.com/12912229/90149747-c3ddd600-dd7c-11ea-8809-95ed1b745f00.png)

**Comment by jemise111** [comment]
Hi @avishags, it looks like you commented out these lines:

```
this.animationIsRunning = true;

...

this.animationIsRunning = false;
```

By doing that the animation is going to run on every swipe event, i.e. many many times. And each time it's going to delete a row. You need to leave those lines in or write your own code to prevent the animation from running more than once per row.

Hope that helps!

Going to close this but please reopen if you still have problems

**Comment by avishags** [comment]
Hi,
Thanks a lot for your reply! But unfortunately this doesn't fix it.
Still same issue.
When I'm using the original sample code as is, it is working also when this is commented out so it is clearly not the problem.
The only main difference is that I am using component and not hooks.
From some reason the deletion of the item doesn't really work

**Comment by avishags** [comment]
Also after updating the new list it still stays in the screen as an open row and doesn't disappear

**Comment by avishags** [comment]
Seems like the problem is in the setState which I'm using instead of setListData, and from some reason doesn't work properly

**Comment by avishags** [comment]
Also, when I'm using my own data source, how do I set the key value?

**Comment by jemise111** [comment]
Hey @avishags sorry for the late reply. Can you post more code I can look at? Also you can set a `key` on each object in an array of objects if that is your data source. Or you can use a `keyExtractor`, see more here: https://reactnative.dev/docs/flatlist#keyextractor
