### ISSUE TITLE
Next row down from deleted row becomes "swiped"

### ISSUE THREAD

**Issue by dontpressthat** [jemise111/react-native-swipe-list-view#498]
I have a delete button that removes a row item based on index in the state array. After I swipe and delete, the next item in the list shows as "swiped", showing its Delete button. I am looking to keep the next item from showing swiped state after deleting the item above it.

**Comment by eramudeep** [comment]
> I have a delete button that removes a row item based on index in the state array. After I swipe and delete, the next item in the list shows as "swiped", showing its Delete button. I am looking to keep the next item from showing swiped state after deleting the item above it.

**Having the same issue.  did you found the fix .??**

**Comment by aidankinzett** [comment]
I had the same issue and ended up fixing it by passing the closeRow function into my hiddenItem component, and then calling it before deleting the item.
```jsx 
<SwipeRow
    rightOpenValue={-80}
    disableRightSwipe
    disableLeftSwipe={item.request !== true}>
            <HiddenItem data={item} closeRow={() => rowMap[item._id].closeRow()} />
            <TransactionListItem
              item={item}
            />
</SwipeRow>
```
and then
``` jsx
const HiddenItem = ({ data, closeRow }) => (
  <View style={styles.rowBack}>
    <View style={{...}}>
      <TouchableOpacity
        onPress={() => {
          closeRow();
          Alert.alert("Delete Request", "Are you sure?", [
            {
              text: "Confirm",
              onPress: () => {
                deleteTransaction(data._id);
              }
            },
            { text: "Cancel", style: "cancel" }
          ]);
        }}
        style={{
          alignItems: "center",
          justifyContent: "center",
          height: "100%",
        }}
      >
        <Text style={[styles.backTextWhite]}>Decline</Text>
      </TouchableOpacity>
    </View>
  </View>
);```

**Comment by jemise111** [comment]
Hey @dontpressthat I'll admit I tend to manually close a row as it's being deleted so there's never a chance that I run into this issue. However I just ran my example and removed this line: https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/basic.js#L26 and I'm still not seeing the behavior you're talking about. Can you post some code to show how you're implementing it? Thanks!

(apologies for the delay in responding)

**Comment by jemise111** [comment]
Closing as inactive

**Comment by Robiullah2244** [comment]
This fixed my issue.
https://github.com/jemise111/react-native-swipe-list-view/issues/455#issuecomment-618104389
