### ISSUE TITLE
Render Hidden Item only if the row is swiped 

### ISSUE THREAD

**Issue by mshafex** [jemise111/react-native-swipe-list-view#499]
I want to render Hidden Button Component only if the row is swiped is it possible to do that ?
here is the code that am trying to make it work

    ` <SwipeListView
        data={data}
        refreshing={loading}
        onRefresh={() => {
          getData();
        }}
      
      
      
        keyExtractor={(item, index) => `item._id`}
        renderItem={({item}) => {
          return (
            <Card
              item={item}
              onPress={() => {
                setOpened(item).then(() => {
                  navigation.navigate('OpenedScreen');
                });
              }}
            />
          );
        }}
        onSwipeValueChange={swipe => {
          if (swipe.isOpen) {
            setRowSwiped(swipe.key);
          }
        }}
        disableLeftSwipe
        renderHiddenItem={(data = {}, rowMap) => {
          if (
            rowMap[`${data.item._id}`] &&
            rowMap[`${data.item._id}`].isOpen
          ) {
            return (
              <TouchableOpacity
                style={{
                  height: hp('14%'),
                  justifyContent: 'center',
                  width: wp('40%'),
                  backgroundColor: '#E71D36',
                  borderRadius: 15,
                }}>
                   <DeleteIcon /> 
              </TouchableOpacity>
            );
          } else {
            return <View />;
          }
        }}
        leftOpenValue={75}
      />`

**Comment by jemise111** [comment]
Hey @mshafex how about this?

```
export default function Basic() {
    const [listData, setListData] = useState(
        Array(20)
            .fill('')
            .map((_, i) => ({ key: `${i}`, text: `item #${i}` }))
    );

    const [show, setShow] = useState(false);

    const onRowOpen = () => {
        setShow(true);
    };

    const onRowClose = () => {
        setShow(false);
    };

    const renderItem = data => (
        <TouchableHighlight
            onPress={() => console.log('You touched me')}
            style={styles.rowFront}
            underlayColor={'#AAA'}
        >
            <View>
                <Text>I am {data.item.text} in a SwipeListView</Text>
            </View>
        </TouchableHighlight>
    );

    const renderHiddenItem = (data, rowMap) => (
        <View style={styles.rowBack}>
            <Text>Left</Text>
            <TouchableOpacity
                style={[styles.backRightBtn, styles.backRightBtnLeft]}
                onPress={() => closeRow(rowMap, data.item.key)}
            >
                {show && <Text style={styles.backTextWhite}>I'm showing!</Text>}
            </TouchableOpacity>
            <TouchableOpacity
                style={[styles.backRightBtn, styles.backRightBtnRight]}
                onPress={() => deleteRow(rowMap, data.item.key)}
            >
                <Text style={styles.backTextWhite}>Delete</Text>
            </TouchableOpacity>
        </View>
    );

    return (
        <View style={styles.container}>
            <SwipeListView
                data={listData}
                renderItem={renderItem}
                renderHiddenItem={renderHiddenItem}
                leftOpenValue={75}
                rightOpenValue={-150}
                onRowOpen={onRowOpen}
                onRowClose={onRowClose}
            />
        </View>
    );
}
```

![hidden MP4](https://user-images.githubusercontent.com/4265163/93288089-bb742300-f7a0-11ea-897c-b877d7dcc239.gif)

**Comment by mshafex** [comment]
> Hey @mshafex how about this?
> 
> ```
> export default function Basic() {
>     const [listData, setListData] = useState(
>         Array(20)
>             .fill('')
>             .map((_, i) => ({ key: `${i}`, text: `item #${i}` }))
>     );
> 
>     const [show, setShow] = useState(false);
> 
>     const onRowOpen = () => {
>         setShow(true);
>     };
> 
>     const onRowClose = () => {
>         setShow(false);
>     };
> 
>     const renderItem = data => (
>         <TouchableHighlight
>             onPress={() => console.log('You touched me')}
>             style={styles.rowFront}
>             underlayColor={'#AAA'}
>         >
>             <View>
>                 <Text>I am {data.item.text} in a SwipeListView</Text>
>             </View>
>         </TouchableHighlight>
>     );
> 
>     const renderHiddenItem = (data, rowMap) => (
>         <View style={styles.rowBack}>
>             <Text>Left</Text>
>             <TouchableOpacity
>                 style={[styles.backRightBtn, styles.backRightBtnLeft]}
>                 onPress={() => closeRow(rowMap, data.item.key)}
>             >
>                 {show && <Text style={styles.backTextWhite}>I'm showing!</Text>}
>             </TouchableOpacity>
>             <TouchableOpacity
>                 style={[styles.backRightBtn, styles.backRightBtnRight]}
>                 onPress={() => deleteRow(rowMap, data.item.key)}
>             >
>                 <Text style={styles.backTextWhite}>Delete</Text>
>             </TouchableOpacity>
>         </View>
>     );
> 
>     return (
>         <View style={styles.container}>
>             <SwipeListView
>                 data={listData}
>                 renderItem={renderItem}
>                 renderHiddenItem={renderHiddenItem}
>                 leftOpenValue={75}
>                 rightOpenValue={-150}
>                 onRowOpen={onRowOpen}
>                 onRowClose={onRowClose}
>             />
>         </View>
>     );
> }
> ```
> 
> ![hidde MP4](https://user-images.githubusercontent.com/4265163/93288649-fe82c600-f7a1-11ea-9f50-2b0c493354c6.gif)

Thanks This really Helps

**Comment by jemise111** [comment]
Hey @mshafex it's in there. Please see this doc: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeListView.md

Going to close this for now, thanks!
