### ISSUE TITLE
how to reset previouslyOpenedRowKey...

### ISSUE THREAD

**Issue by salmanitb** [jemise111/react-native-swipe-list-view#500]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/jemise111/react-native-swipe-list-view/issues) before creating one.

**Describe the bug**

**To Reproduce**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android]
 - RNSLV Version: [e.g. v2.0.2]
 - RN Version: [e.g. v60.0.5]

**Comment by salmanitb** [comment]
@jemise111 i have 3 button.. button1 , button 2 and button 3..
and i have react native swipe list view.
if i click button 1,button2 or button 3 just change the data.
<SwipeListView data={this.state.data} />
 the problem is if i open swipe in one item(button 1) if 
i click button 2, automatic item open in the same one  posisition in previousopenedrowkey.

this is my function to open and close manually

bukatutup = (rowMap, rowKey)  => {
        let row = rowMap[rowKey];
        if (rowIsOpen) {
            if (rowKey === previouslyOpenedRowKey) {
                row.closeRow();
                rowIsOpen = false;
                previouslyOpenedRowKey = null;
            } else {
                let previouslyOpenedRow = rowMap[previouslyOpenedRowKey];
                previouslyOpenedRow.closeRow();
                row.manuallySwipeRow(normalize(-160));
                rowIsOpen = true;
                previouslyOpenedRowKey = rowKey;
            }
        } else {
            row.manuallySwipeRow(normalize(-160));
            rowIsOpen = true;
            previouslyOpenedRowKey = rowKey;
        }
    };

"react-native-swipe-list-view": "^2.1.3",
"react-native": "^0.61.5",

please help me..

**Comment by salmanitb** [comment]
i want if i click button2, my swipe is reset..

**Comment by jemise111** [comment]
Hey @salmanitb I'm sorry but I'm not fully understanding the question. Do you think you could post a gif of the problem? Happy to take another look then, thanks!

(apologies for the delay in responding)

**Comment by jemise111** [comment]
Closing as inactive
