### ISSUE TITLE
Handle for onLongPress

### ISSUE THREAD

**Issue by nhimspec** [jemise111/react-native-swipe-list-view#501]
I have issue with onLongPress. It not work when i release apk. When i hold on item, it won’t trigger my own onLongPress. Could you help me?

**Comment by salmanitb** [comment]
can u share u code???
in my case its work.

**Comment by nhimspec** [comment]
> can u share u code???
> in my case its work.

![image](https://user-images.githubusercontent.com/19776115/91439915-fb2da600-e897-11ea-9fe8-aa8fe5919133.png)
In this case, i use my own onLongPress. On debug mode, it works, however when I release apk, it won't work

**Comment by jemise111** [comment]
Hey @nhimspec I'm pretty positive if this is really an issue it's not with this library. Can you try adding a `onLongPress` handler to a `Touchable` in your app in a component that's **not** using your library and see if you have the same issue? Thanks!

(apologies for the delay in responding)

**Comment by jemise111** [comment]
Closing as inactive
