### ISSUE TITLE
Row gets clicked onPressOut the swipe

### ISSUE THREAD

**Issue by fleissigal** [jemise111/react-native-swipe-list-view#503]
Hello everyone,

I have an issue with <SwipeListView> that I couldn't find the answer to in the docs or within the other issues.

**The issue**
Every time I swipe the row, then I release the mouse press while the mouse is located on the swiped row (I'm using react native web), the item that I swiped gets clicked. However, if I swipe and release the mouse press while the mouse is located on a different item - then it doesn't click on the item.

**Environment:**
 - OS: web
 - RN Version: >60

Does anyone know how to solve it?
I can attach code as needed (though my swipe list properties are pretty standard).

Thanks!

**Comment by fleissigal** [comment]
I managed to solve the issue:

All I had to do was to wrap the <SwipeListView> with <ScrollView>.

This way, as soon as I start the swipe the "item press gets canceled" so when I release the mouse press the item does not get clicked.

**Comment by danstepanov** [comment]
@fleissigal How did you solve this?

**Comment by danstepanov** [comment]
for me it was making sure I was importing TouchableWithoutFeedback from react-native, rather than from react-native-gesture-handler

**Comment by fleissigal** [comment]
Sorry, just noticed that my comment was not formatted correctly.

I just fixed it, you can see there, I basically had to wrap the SwipeListView with ScrollView and it solved the problem.
