### ISSUE TITLE
How to stop updating a Row Item when the Hidden Item is visible? 

### ISSUE THREAD

**Issue by saumaypaul20** [jemise111/react-native-swipe-list-view#504]
I want to stop update a Row Item if its swiped open its hidden item. Going through the docs, found shouldItemUpdate is a prop to play with. But can anybody explain how to know if Row is opened so that I can apply a logic in shouldItemUpdate?

**Comment by jemise111** [comment]
Hi @saumaypaul20 there are a couple ways to do this. You can use the `onRowOpen`, `onRowClose` props to keep track of which rows are open / closed. See more here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeListView.md. Or you can keep refs to rows and check if it is open using `rowRef.isOpen`.

If you have more questions please reopen and let me know, thanks!

(apologies for the delay in responding)
