### ISSUE TITLE
Swipe-to-delete with TypeScript gives 'this' implicitly has type 'any' because it does not have a type annotation.ts(2683)

### ISSUE THREAD

**Issue by ethankeshishian** [jemise111/react-native-swipe-list-view#506]
I've tried to implement the swipe-to-delete example, but I keep encountering an error on `this.animationIsRunning` in `onSwipeValueChange`. Here's the error:
```
'this' implicitly has type 'any' because it does not have a type annotation.ts(2683)
MyLibraryScreen.tsx(25, 17): An outer value of 'this' is shadowed by this container.
```

I've even implemented the list exactly like the example, but the issue persists. I noticed that when I try to `console.log(this)`, `this` is undefined. Any idea why? Thanks.

**Comment by jemise111** [comment]
Hi @ethankeshishian, good call! `this` shouldn't be there. Fixed here: https://github.com/jemise111/react-native-swipe-list-view/pull/521
