### ISSUE TITLE
Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled.

### ISSUE THREAD

**Issue by vistier** [jemise111/react-native-swipe-list-view#51]
ExceptionsManager.js:76 Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled.reactConsoleError @ ExceptionsManager.js:76console.error @ YellowBox.js:60_handleLongDelay @ Touchable.js:595JSTimersExecution.callbacks.(anonymous function) @ JSTimers.js:47callTimer @ JSTimersExecution.js:84(anonymous function) @ JSTimersExecution.js:119callTimers @ JSTimersExecution.js:119__callFunction @ MessageQueue.js:204(anonymous function) @ MessageQueue.js:95guard @ MessageQueue.js:41callFunctionReturnFlushedQueue @ MessageQueue.js:94onmessage @ debuggerWorker.js:39

**Comment by jemise111** [comment]
@vistier I haven't been able to reproduce this.

Could you provide the code you're using with the SwipeListView or SwipeRow? Also if you could provide the version of RN, device info, and anything else that would be super helpful, thanks!

**Comment by joonhocho** [comment]
https://github.com/facebook/react-native/issues/1693

**Comment by jemise111** [comment]
Closing as I haven't heard anything here for a while
