### ISSUE TITLE
rowMap is not getting updated after deleting an item from the list

### ISSUE THREAD

**Issue by Yandamuri** [jemise111/react-native-swipe-list-view#510]
**Describe the bug**
if any item is deleted from the list, rowMap is still holding it as a key but it's value is null. Even though there is a state update rowMap is not getting updated unless go to another screen and come back to the current screen. That means if component is unMounted and mounted once again then only rowMap is getting updated

**To Reproduce**
Delete any item from list and then check rowMap if it still holds the deleted item.

**Screenshots**
![del](https://user-images.githubusercontent.com/31983789/95185890-f1785600-07e6-11eb-9eab-559cc530923f.PNG)

**Environment (please complete the following information):**
 - OS: Android
 - RNSLV Version: "^3.2.4"
 - RN Version: "0.63.2"

How to update rowMap as soon any item is deleted from the list?

**Comment by staghouse** [comment]
Have you tried adding the row data in the `extraData` prop of `<SwipeListView>`?:

```
<SwipeListView
  ...
  data={myListData}
  extraData={myListData}
  ...
/>
```

This worked for me to keep the re-render "stateful".

**Comment by Yandamuri** [comment]
@staghouse This solution doesn't show any effect. Any alternative to refresh rowMap?

**Comment by jemise111** [comment]
Hi @Yandamuri I suppose I could constantly check for changes in the `data` prop and compare them to the `rowMap` but it's a pretty expensive computation to keep `rowMap` stateful. Can I ask why this is an issue for you?

**Comment by Yandamuri** [comment]
@jemise111  I used to get error when i try to delete two records consecutively. so i thought it's because of  rowmap. Then later i realized that i didn't provide the unique keys to the list of records. when i did so everything was ok. But i'm sure that when i console logged rowmap after deleting an item, we can see null for the deleted item as i shown in the screen shot mention in the question.

**Comment by jemise111** [comment]
Hey @Yandamuri glad you solved your issue. I think you're definitely right that `rowMap` will have `null` items when rows are deleted, I just don't think it's a problem worth solving. It's just a lot easier to check to a `null` row on the end users side than it is for the library to try and keep the `rowMap` and `data` props in perfect sync

**Comment by Yandamuri** [comment]
@jemise111 Thanks for giving clarity over rowMap.
