### ISSUE TITLE
How to prevent list scroll while swiping an item

### ISSUE THREAD

**Issue by Yandamuri** [jemise111/react-native-swipe-list-view#511]
**Describe the bug**
List scrolls everytime i swipe an item in the list. this is happening every time i swipe any item in the list 

**To Reproduce**
run the swipe list view and try to swipe any item in the list

Environment :

OS: Android
RNSLV Version: "^3.2.4"
RN Version: "0.63.2"

**Comment by jemise111** [comment]
Hi @Yandamuri the SwipeListView is locked to scrolling when an item is swiped so I'm not sure how this could be happening? Could you show me a gif of the issue and some reproducible sample code? I can't currently reproduce on my side, thanks!

**Comment by Yandamuri** [comment]
@jemise111 I am not if it happened in my device only i found only once and i am unable to reproduce it now. Anyway thank you for your response. If i can reproduce in the future i will come up with code .
