### ISSUE TITLE
Warning - VirtualizedLists should never be nested inside plain ScrollViews.

### ISSUE THREAD

**Issue by ashok-sl** [jemise111/react-native-swipe-list-view#515]
I am constantly getting this warning.
`VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead. 
`

My Code is
`<View 
      style={{flex: 1, justifyContent: 'center'}}
  >
       <ScrollView
		style={{flex: 1}}
		ref={(c) => {this.scroll = c}}
		nestedScrollEnabled={true}
	>
		<View style={{paddingLeft: 15, paddingRight: 15}}>
			<View>
			{
				data.map((items, index) => {
					return (
						<View key={index}>
							<Text>{items.title}</Text>
							<SwipeListView
								scrollEnabled={false}
								nestedScrollEnabled={true}
							 	ref={ref => this[`_swipeListView${index}`] = ref}
								data={items.users}
								renderItem={ (data, rowMap) => this.renderCards(data)}
								renderHiddenItem={ (rowData, rowMap) => {
									return this.renderHiddenItem(rowData, rowMap, items)
								}}
								leftOpenValue={75}
								rightOpenValue={-75}
								closeOnRowOpen={false}
							/>
						</View>
					)
				})
			}
			</View>
		</View>
	</ScrollView>
</View>`

**Environment (please complete the following information):**
 - OS: iOS
 - RN Version: [e.g. v 0.63]

**Comment by jemise111** [comment]
Hi @ashok-sl, `SwipeListView` is a virtualized list so RN is warning you it should not be nested within a `ScrollView` as you have shown above, if the orientation is the same. To fix you'll need to remove your `ScrollView` wrapper

**Comment by ngmikeng** [comment]
In my case I'm trying use `SwipeListView` in a children component. I have removed ScrollView wrapper arround `SwipeListView` in children component but still get the warning, I have another ScrollView wrapper on a parent component and it's required because of its content is very long.

**Comment by mixmaster429** [comment]
> Hi @ashok-sl, `SwipeListView` is a virtualized list so RN is warning you it should not be nested within a `ScrollView` as you have shown above, if the orientation is the same. To fix you'll need to remove your `ScrollView` wrapper

In my case, the content is too long, so I need to use **ScrollView** wrapper and use **SwipeListView** inside of it. 
Any solution to get rid of this issue without removing the **ScrollView** element

**Comment by lukas-kuhl** [comment]
> > Hi @ashok-sl, `SwipeListView` is a virtualized list so RN is warning you it should not be nested within a `ScrollView` as you have shown above, if the orientation is the same. To fix you'll need to remove your `ScrollView` wrapper
> 
> @jemise111 In my case, the content is too long, so I need to use **ScrollView** wrapper and use **SwipeListView** inside of it. Any solution to get rid of this issue without removing the **ScrollView** element

+1 

I updated react and react-native. Before the update there was no error for the same code (<ScrollView> ...<SwipeListView/> ...</ScrollView>

**Comment by oimolab** [comment]
ListHeaderComponent solved this problem.
[https://reactnative.dev/docs/flatlist#listheadercomponent](url)

**Comment by ymc-thzi** [comment]
just add  
```
<SwipeListView
                  scrollEnabled={false}
                  ...
```
then you can keep your surrounding ScrollView
