### ISSUE TITLE
SwipeRow Override on the internal button

### ISSUE THREAD

**Issue by frodoe7** [jemise111/react-native-swipe-list-view#518]
**Describe the bug**

The swipe list component works well , but there's a trick with me
There's a SwipeRow element override on a button (check the inspector details on the below screenshot)
I don't use these hidden items and so on..

instead , I wrote some customized stylings to increase the main component width and so on..

here's my codes

```javascript
   renderItem(item)
   {
        return (<TouchableOpacity style={{flexDirection:"row"}}>
        <WideProduct increaseItemAmount={this.increaseItemAmount} decreaseItemAmount={this.decreaseItemAmount} item={item} />
        <TouchableOpacity onPress={() => {
          alert("Clicking !!"); // not working
        }} style={{width:responsiveWidth(85),marginTop:responsiveHeight(19),alignItems:"center",justifyContent:"center",height:responsiveHeight(85)
        ,backgroundColor:DynamicAppStyles.colorSet.light.red}}>
                 <AntIcon color="#FFF" size={32} name="delete" />
               </TouchableOpacity>
        </TouchableOpacity>)
   }
```

**Screenshots**
![bb6875d3-dbeb-4859-872e-99f72f96cbd9](https://user-images.githubusercontent.com/2767001/96572992-d240f480-12cd-11eb-82a7-8fed4aa6a536.jpeg)

**Environment**
 - OS: Android
 - RNSLV Version: 3.2.4
 - RN Version: 61.4

if this issue has no solution , please recommend a better library or how to make it without (plugins/libraries)

**Comment by jemise111** [comment]
Hi @frodoe7 I'm not sure what the issue is here? Can you elaborate please

**Comment by ajitdas123** [comment]
@jemise111 , let's say a button appears on top of the swipe list when swiping , on clicking the button nothing happens. On inspection, it shows that the swipe list is taking over.

**Comment by frodoe7** [comment]
It's very old issue
I had to use another swipe list library
