### ISSUE TITLE
Animation problem in height on swipe to delete

### ISSUE THREAD

**Issue by fdelavra** [jemise111/react-native-swipe-list-view#522]
Hello. 

I have a problem on the swipe to delete example :
Even if the usenativedriver is set to false, I have an error trying to animate the height of the list item as in the example: 
- Style property 'height' is not supported by native animated module

Every supported animations like translate or scale works fine. 

React native version :0.62

Thanks for your help

**Comment by jemise111** [comment]
Hi @fdelavra can you share your code please?

**Comment by fdelavra** [comment]
Yes of course sorry ;)


import React, {useEffect, useState, useRef} from 'react';
import _ from 'lodash';
import {Animated, Easing, View} from 'react-native';
import {Button, Text, Icon} from 'native-base';
import CartContent from './CartContent';
import { SwipeListView } from 'react-native-swipe-list-view';
import styles, {colors} from '../styles/index.style';
import { useSelector, useDispatch } from 'react-redux';
import { deleteCart, removeFromCart } from '../redux/action/CartAction';
import { updateTotal } from '../redux/action/TotalAction';
import nodejs from 'nodejs-mobile-react-native';
import DeviceInfo from 'react-native-device-info';
import Properties from '../static/Properties';
import UtilsAlert from '../utils/UtilsAlert';
import CartContentHidden from './CartContentHidden';

const Cart = () => {
  const dispatch = useDispatch();
  const total = useSelector(state => state.total);
  const cart = useSelector(state => state.cart);
  const [cartLayout, setCartLayout] = useState(0);
  const animTab = {};
  const animTime = 500;

  useEffect(() => {
    dispatch((updateTotal(cart)));
  }, [cart]);

  cart.map(cartItem => {
    animTab[cartItem.product.name] = new Animated.Value(1);
  })

  const animationIsRunning = useRef(false);

  const closeRow = (rowMap, data) => {
    if (rowMap[data.item.product.name]) {
      rowMap[data.item.product.name].closeRow();
    }
  }

  const onSwipeValueChange = (swipeData) => {
    const { key, value } = swipeData;
    const cartItem = _.find(cart, function(o) {return o.product.name === key});
    if(value < -cartLayout.width && !animationIsRunning.current){
      animationIsRunning.current = true;
      Animated.timing(animTab[key], {
        toValue: 0,
        duration: 300,
        useNativeDriver: false,
        easing: Easing.linear
      }).start(() => {
        dispatch(removeFromCart(cartItem));
        animationIsRunning.current = false;
      })
    }
  }

  const removeProductLine = (rowMap, data) => {
      closeRow(rowMap, data);
      dispatch(removeFromCart(data.item));
  }

  const cleanCart = () => {
    UtilsAlert.showAlert('Attention', 'Voulez-vous vraiment vider votre panier?', [
      {text: 'Annuler', style: 'cancel'},
      {text: 'Supprimer', onPress: (evt) => dispatch(deleteCart())}
    ]);
  }

  const askToOrder = cart => {
    UtilsAlert.showAlert('Confirmer', 'Toute commande envoyée devra être reglée', [
      {text: 'Annuler', style: 'cancel'},
      {text: 'Commander', onPress: (evt) => orderCart(cart)}
    ]);
  }

  const orderCart = cart => {
    let cartPrint = {deviceName: '', content: [], total: ''};
      DeviceInfo.getDeviceName().then(deviceName => {
        cartPrint.printIp = Properties.PRINT_IP;
        cartPrint.deviceName = 'Tablette: ' + deviceName;
        cart.map(cartItem => {
          let tmpPrice = cartItem.product.price ? cartItem.product.price : cartItem.product.prices[0].value;
          let price = 
          cartItem.product.optionPrice ? 
          (tmpPrice + cartItem.product.optionPrice).toFixed(2).replace(".", ",")+'€'
          : tmpPrice.toFixed(2).replace(".", ",")+'€';
          cartPrint.content.push([Number(cartItem.quantity), cartItem.product.name, price]);
        });
        cartPrint.total ='Total: ' + total.toFixed(2) + '€';
        thermalPrint(cartPrint);
      }, (noSuccess) => {
        UtilsAlert.showAlert('Erreur', 'nom de tablette introuvable', [
                             {text: 'Ok'}
                           ]);
      });
  }

  const thermalPrint = cartPrint => {
    nodejs.channel.post('print', cartPrint);
  }

  return (
    <View style={{width: '100%', height: '100%'}} onLayout={(event) => {setCartLayout(event.nativeEvent.layout)}}>
      <View style={{height:55, flexDirection:'column', alignItems:'center'}}>
        <Text style={styles.title}>Panier</Text>
      </View>
      <View style={{flex:9}}>
          <SwipeListView
                useFlatList
                closeOnRowPress
                closeOnRowBeginSwipe
                disableRightSwipe
                rightOpenValue={-75}
                keyExtractor={(item, index) => item.product.name}
                onSwipeValueChange = {onSwipeValueChange}
                data={cart}
                renderItem={(data, rowMap) =>
                  <Animated.View 
                      style={{
                        opacity: opacity,
                          height: animTab[data.item.product.name].interpolate({
                            inputRange: [0, 1],
                            outputRange: [0, 50]
                          })
                      }}
                  >
                    <CartContent
                            key={data.item.product.name}
                            cartItem={data.item}
                            animTime={animTime}
                    />
                  </Animated.View>
                }
                renderHiddenItem={(data, rowMap) => (
                    <CartContentHidden
                            key={data.item.product.name}
                            removeProductLine={removeProductLine}
                            animTime={animTime}
                            rowMap={rowMap}
                            data={data}
                            animTab={animTab}
                    />
                )}
          />
      </View>
    </View>
  );

}

export default Cart;

**Comment by jemise111** [comment]
@fdelavra can you try also adding `useNativeDriver={false}` as a prop to the `SwipeListView` like this https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/swipe_to_delete.js#L93

**Comment by fdelavra** [comment]
It's working perfectly ! thanks a lot!

**Comment by jemise111** [comment]
👍 glad to hear
