### ISSUE TITLE
SwipeToDelete - Example in Expo fails.

### ISSUE THREAD

**Issue by istanbulbyefendisi** [jemise111/react-native-swipe-list-view#525]
I want to use its package, but here (https://snack.expo.io/@jemise111/react-native-swipe-list-view) SwipeToDelete example fails. I fixed the error by replacing the height with translateY and adding useNativeDriver: true. But scroll animation does not work after item deletion as in Gif.

**Comment by jemise111** [comment]
Hi @istanbulbyefendisi you just need to set `useNativeDriver={false}` on the `SwipeListView` and everything works as intended. I updated the snack, thanks!
