### ISSUE TITLE
How to swipe only one and turn off another

### ISSUE THREAD

**Issue by methineeinkan** [jemise111/react-native-swipe-list-view#526]
![Screen Shot 2563-11-05 at 13 27 33](https://user-images.githubusercontent.com/40588602/98205439-c0687e00-1f6a-11eb-84ab-da12f0757828.png)

**Comment by luojiong** [comment]
This document wrote  https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/manually-closing-rows.md

**Comment by luojiong** [comment]
If you are using'SwipeRow', please define a'ref' for him and use'ref' to call'closeRow()'

**Comment by methineeinkan** [comment]
SwipeListView  not work closeOnRowBeginSwipe and closeOnRowOpen

**Comment by luojiong** [comment]
Please check if your 'data' contains' key '

**Comment by ikeliec** [comment]
> Please check if your 'data' contains' key '

This helped. `closeOnRowBeginSwipe` prop works for me.

**Comment by xiaobinhuang** [comment]
I meet this problem too when I create a SwipeListView, and use SwipeRow in the renderItem funciton. I found my data not contains the 'key', so I add a _keyExtractor_ property in the SwipeListView element and solved this problem.
`
_keyExtractor = (item, index) => {
        return index.toString();
    }
`
`
   <SwipeListView
                        useFlatList
                        keyExtractor={this._keyExtractor}
                        data={data}
                        renderItem={(data, rowMap) => (
                            <SwipeRow> ....</SwipteRow>
   />
`

**Comment by jemise111** [comment]
Hey @methineeinkan I agree with @luojiong , this is almost always solved by ensuring you either have a `key` for your data or pass a `keyExtractor` prop.

Looks like that is working for people in this thread, so I will close this, but reopen if you still have issues, thanks!
