### ISSUE TITLE
Warning: Something is calling a React component directly.

### ISSUE THREAD

**Issue by tudiantuan** [jemise111/react-native-swipe-list-view#528]
I use swipe-list-view recieve warning: Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory
  
             <SwipeListView
                data={newsList}
                extraData={newsList}
                renderItem={renderItem}
                keyExtractor={item => item.c13}
                renderHiddenItem={renderHiddenItem}
                rightOpenValue={-150}
                disableRightSwipe
                scrollEnabled={false}
            />

    const renderItem = ({ item }) => {
        return (
        <Row
            style={{ marginVertical: dimensions.halfIndent, backgroundColor: PRIMARY__BG__COLOR }}
            onPress={changeOrderDetail}>
            <Text style={{ flex: 0.8, color: c2 === '1' ? UP__COLOR : DOWN__COLOR, fontSize: c4.length > 3 ? fontSizes.smallest : fontSizes.verySmall }}>
                {item.a1}
            </Text>
            <Text style={{ flex: 1, textAlign: 'right', color: PRIMARY__CONTENT__COLOR, fontSize: Number(c5) > 999999 ? fontSizes.smallest : fontSizes.verySmall }}>
                {item.a2}
            </Text>
            <Text style={{ flex: 1, textAlign: 'right', color: PRIMARY__CONTENT__COLOR, fontSize: Number(c8) > 999999 ? fontSizes.smallest : fontSizes.verySmall }}>
                {item.a3}
            </Text>
            <Text style={{ flex: 1, textAlign: 'right', color: PRIMARY__CONTENT__COLOR, fontSize: fontSizes.verySmall }}>
                {item.a4}
            </Text>
            <Text style={{ flex: 1.5, textAlign: 'right', color: colorC11, fontSize: fontSizes.smallest }}>
                {item.a5}
            </Text>
        </Row>
        )
    };

      const renderHiddenItem = (data) => {
    return (
        <View style={UI.rowBack}>
            <TouchableOpacity
                style={[UI.backRightBtn, UI.backRightBtnLeft]}
                onPress={() => {
                    console.log('edit')
                    handleShowModalModify(data.item)
                }}>
                <Feather
                    name="edit"
                    size={22}
                    style={UI.trash}
                    color={styles.PRIMARY}
                />
            </TouchableOpacity>

            <TouchableOpacity
                style={[UI.backRightBtn, UI.backRightBtnRight]}
                onPress={() => showModalCancel(data.item)}>
                <AntDesign
                    name="delete"
                    size={22}
                    color={styles.DOWN__COLOR}
                />
            </TouchableOpacity>
        </View>
    );
}

**Comment by jemise111** [comment]
Hi @tudiantuan I just updated to the latest RN version to be safe. I'm definitely not seeing this warning on my side. Can you confirm that this is not due to the `AntDesign` or `Feather` components?

**Comment by jemise111** [comment]
Closing as inactive
