### ISSUE TITLE
Doesn't touch on swipe

### ISSUE THREAD

**Issue by osvald0** [jemise111/react-native-swipe-list-view#529]
I have a list of touchable components and when I want to make a Swipe always the component receive the touch event.
Can I swipe a touchable component without make the touch action?

 - OS: Android 10
 - RN Version: 0.63.2

**Comment by osvald0** [comment]
I couldn't found a solution. Is this project abandoned?

**Comment by jemise111** [comment]
Hey @osvald0 this project is not abandoned, just took some time off :)

Are you saying you have a row that is touchable but you do **not** want the touch event to fire when the row is swiped? If so please see this https://github.com/jemise111/react-native-swipe-list-view#note and you can also see an example of that here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/basic.js#L37

**Comment by jemise111** [comment]
Closing as inactive
