### ISSUE TITLE
Close all open rows?

### ISSUE THREAD

**Issue by tcagkansokmen** [jemise111/react-native-swipe-list-view#531]
Is that possible to close all open rows?

I want to close them, when I click any otherwhere

None of these methods works:

```
 <SwipeListView
            closeOnScroll={true}
            closeOnRowBeginSwipe={true}
            closeOnRowOpen={true}
            closeOnRowPress={true}
            data={orders.data}
            renderItem={renderItem}
            renderHiddenItem={(data, rowMap) => (
```

If they are not working, why they are still on docs?

**Comment by jemise111** [comment]
Hi @tcagkansokmen please see the discussion here for a solution to this problem, thanks!

https://github.com/jemise111/react-native-swipe-list-view/issues/465
