### ISSUE TITLE
OnPress of Delete button currently deletes the last item in the FlatList, rather than what is selected.

### ISSUE THREAD

**Issue by usman646** [jemise111/react-native-swipe-list-view#533]
[HomeScreen1.txt](https://github.com/jemise111/react-native-swipe-list-view/files/5719608/HomeScreen1.txt)
[reviewForm.txt](https://github.com/jemise111/react-native-swipe-list-view/files/5719609/reviewForm.txt)l
[reviewDetails.txt](https://github.com/jemise111/react-native-swipe-list-view/files/5719612/reviewDetails.txt)

Hi everyone.. hope you are well! 
Any help with this issue would be greatly appreciated, I am a newbie to coding and attempting to create an app which will serve as a tracking tool for professionals. 

**Context:** I followed this YouTube tutorial (https://www.youtube.com/watch?v=t4Q1s8WntlA) to create a page which allows you to fill out a form and onPress of the Submit button, display the results in a list. I have created two buttons, Close and Delete. 

**Issue 1:** The close button works fine however the delete button currently deletes the first item in the list, rather than what is selected. 

**Issue 2:** (not sure if it causes Issue 1) Creating the key for each item in the FlatList. At the moment this is done using "Math.random().toString()" however I understand this is not advisable. I have come across UUID which could be one option to create a unique identifier, wondering what you would suggest and how I could build this into my project?

**### _Code_**

**_HomeScreen1_**

``import React, { useState } from 'react';
import { StyleSheet, View, Button, Text, TouchableOpacity, FlatList, Modal,
  TouchableWithoutFeedback, Keyboard } from 'react-native';
import { globalStyles } from '../screens/global.js';
import { MaterialIcons } from '@expo/vector-icons';
import Card from '../screens/card.js';
import ReviewDetails from '../screens/reviewDetails.js';
import ReviewForm from '../screens/reviewForm.js';
import { SwipeListView } from 'react-native-swipe-list-view';
import LoginPage from '../screens/LoginPage.js';
import DashboardPage from '../screens/DashboardPage.js';
import SecondPage from '../screens/secondPage.js';
import ThirdPage from '../screens/thirdPage.js';

export default function Home({ navigation }) {
  const [modalOpen, setModalOpen] = useState(false);
  const [reviews, setReviews] = useState([
    { title: '', rating: '', body: '', key: '' },
  ]);

  const addReview = (review) => {
    review.key = Math.random().toString();
    setReviews((currentReviews) => {
      return [review, ...currentReviews];
    });
    setModalOpen(false);
  };

  return (
    <View style={globalStyles.container}>
      <Modal visible={modalOpen} animationType='slide'>
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <View style={styles.modalContent}>
            <MaterialIcons
              name='close'
              size={24}
              style={{...styles.modalToggle, ...styles.modalClose}}
              onPress={() => setModalOpen(false)}
            />
            <ReviewForm addReview={addReview} />
          </View>
        </TouchableWithoutFeedback>
      </Modal>

      <MaterialIcons
        name='add'
        size={24}
        style={styles.modalToggle}
        onPress={() => setModalOpen(true)}
      />

      <SwipeListView
        useFlatList={true}
        data={reviews}
        renderItem={({ item }) => (
          <TouchableOpacity onPress={() => navigation.navigate('ReviewDetails', item)}>
            <Card>
              <Text style={globalStyles.titleText}>{ item.title } { item.body } { item.rating } { item.key }</Text>
            </Card>
          </TouchableOpacity>
        )}
        renderHiddenItem={ ({ item }, rowMap, rowKey) => (
        <View>
            <TouchableOpacity
            onPress={ () => {
              const newData= [...reviews];
              newData.splice(item.key, 1);
              setReviews(newData);
            }}
            style={[styles.backRightBtn, styles.backRightBtnLeft]}
            >
              <Text>Delete</Text>
            </TouchableOpacity>

            <TouchableOpacity
            //onPress={onClose}
            onPress={() => rowMap[item.key].closeRow() }
            style={[styles.backRightBtn, styles.backRightBtnRight]}
            >
            <Text>Close</Text>
            </TouchableOpacity>
            <TouchableOpacity
            style={[styles.backRightBtn, styles.backRightBtnCenter]}
            >
            <Text>Edit</Text>
            </TouchableOpacity>
        </View>
        )}
        rightOpenValue={-180}
        disableRightSwipe
      />
    </View>

  );
}

const styles = StyleSheet.create({
  modalToggle: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'black',
    padding: 10,
    borderRadius: 10,
    alignSelf: 'center',
  },
  modalClose: {
    marginTop: 20,
    marginBottom: 0,
  },
  modalContent: {
    flex: 1,
  },
  backRightBtn: {
  alignItems: 'flex-end',
  bottom: -85,
  justifyContent: 'center',
  position: 'absolute',
  top: 10,
  width: 60,
  paddingRight: 15,
},
backRightBtnLeft: {
  backgroundColor: '#1f65ff',
  right: 110,
},
backRightBtnCenter: {
  backgroundColor: 'red',
  right: 60,
},
backRightBtnRight: {
  backgroundColor: 'green',
  right: 5,
  borderTopRightRadius: 5,
  borderBottomRightRadius: 5,
},
});

**_reviewForm_**

import React from 'react';
import { StyleSheet, Button, TextInput, View, Text } from 'react-native';
import { globalStyles } from '../screens/global.js';
import { Formik } from 'formik';

export default function ReviewForm({ addReview }) {

  return (

    <View style={globalStyles.container}>
      <Formik
        initialValues={{ title: '', body: '', rating: '' }}
        onSubmit={(values, actions) => {
          actions.resetForm();
          addReview(values);
        }}
      >
        {props => (
          <View>
            <TextInput
              style={globalStyles.input}
              placeholder='Review title'
              onChangeText={props.handleChange('title')}
              value={props.values.title}
            />

            <TextInput
              style={globalStyles.input}
              multiline
              placeholder='Review details'
              onChangeText={props.handleChange('body')}
              value={props.values.body}
            />

            <TextInput
              style={globalStyles.input}
              placeholder='Rating (1 - 5)'
              onChangeText={props.handleChange('rating')}
              value={props.values.rating}
              keyboardType='numeric'
            />

            <Button color='maroon' title="Submit" onPress={props.handleSubmit} />
            <Button color='maroon' title="Cancel" />
          </View>
        )}
      </Formik>
    </View>

  );
}
`
**_reviewDetails_**

import React from 'react';
import { StyleSheet, View, Text, Image } from 'react-native';
import { globalStyles } from '../screens/global.js';
import Card from '../screens/card.js';

export default function ReviewDetails({ navigation }) {
  const rating = navigation.getParam('rating');

  return (
    <View style={globalStyles.container}>
      <Card>
        <Text style={globalStyles.titleText}>
          { navigation.getParam('title') }
        </Text>
        <Text>{ navigation.getParam('body') }</Text>
        <View style={styles.rating}>
          <Text>Will fill in later </Text>
        </View>
      </Card>
    </View>
  );
}

const styles = StyleSheet.create({
  rating: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: 16,
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  }
});

**Comment by jemise111** [comment]
Hey @usman646 can you try changing this:

```
<TouchableOpacity
        onPress={ () => {
          const newData= [...reviews];
          newData.splice(item.key, 1);
          setReviews(newData);
        }}
```

to this

```
<TouchableOpacity
        onPress={ () => {
          const newData= [...reviews];
          const index = reviews.findIndex(review => review.key === rowKey);
          newData.splice(index, 1);
          setReviews(newData);
        }}
```

and see if that works, thanks

**Comment by usman646** [comment]
> Hey @usman646 can you try changing this:
> 
> ```
> <TouchableOpacity
>         onPress={ () => {
>           const newData= [...reviews];
>           newData.splice(item.key, 1);
>           setReviews(newData);
>         }}
> ```
> 
> to this
> 
> ```
> <TouchableOpacity
>         onPress={ () => {
>           const newData= [...reviews];
>           const index = reviews.findIndex(review => review.key === rowKey);
>           newData.splice(index, 1);
>           setReviews(newData);
>         }}
> ```
> 
> and see if that works, thanks

Hi @jemise111, thank you for your respnse
Unfortunately, that did not work.

**Comment by usman646** [comment]
@jemise111 Thanks for your help!

I had to make one change and it now works- replacing rowKey with item.key...

`            onPress={ () => {
              const newData= [...reviews];
              const index = reviews.findIndex(review => review.key === item.key);
              console.log(index)
              newData.splice(index, 1);
              setReviews(newData);
            }}`

**Comment by Saimoon0311** [comment]
- 

1. 

> ### 

- [ ]   #@**_`[](url)`_**
