### ISSUE TITLE
Scroll being called while swiping

### ISSUE THREAD

**Issue by ingerable** [jemise111/react-native-swipe-list-view#538]
**Describe the bug**
When I'm swiping an item the scroll event may be fired which means is it not disabled while swiping. We have combined recycle list view and row swipe like @tomasmozeris did in the issue [513#](https://github.com/jemise111/react-native-swipe-list-view/issues/513#issuecomment-716420373).

**To Reproduce**
We have our list :

````
      <RecyclerListView
        layoutProvider={this._layoutProvider}
        dataProvider={this.state.dataProvider}
        rowRenderer={this._rowRenderer}
        extendedState={{
          selectionMode: this.props.selectionMode
        }}
        directionalLockEnabled={true}
      />
````
And each swipeable row rendered :

````
  _rowRenderer(type, data, index) {
    return (
      <SwipeRow style={{ flex: 1, backgroundColor: "red" }}
        leftOpenValue={hiddenButtonWidth * 3}
        rightOpenValue={-hiddenButtonWidth}
        stopLeftSwipe={hiddenButtonWidth * 3}
        stopRightSwipe={-hiddenButtonWidth}
        swipeToClosePercent={15}
        swipeToOpenPercent={20}
        disableLeftSwipe={this.props.selectionMode}
        disableRightSwipe={this.props.selectionMode}
        friction={100}
        tension={100}
        recalculateHiddenLayout={true}
        directionalDistanceChangeThreshold={5}
        swipeGestureBegan={(value) => {
          this.currentOpenRowRef = React.createRef();
          if (this.state.currentOpenRowIndex != null && this.state.currentOpenRowIndex != index) {
            this.rowsRef[this.state.currentOpenRowIndex].closeRow();
          }
          this.setState({currentOpenRowIndex: index})
        }}
        onRowClose={(value) => {
          index == this.state.currentOpenRowIndex ? this.setState({ currentOpenRowIndex: null}) : this.setState({ currentOpenRowIndex: index }) ;
        }}
        ref={(elm) => {
          this.rowsRef[index] = elm;
        }}
      >
        {this._renderHiddenItem(data, index)}
        {this._renderItem(data, index)}
      </SwipeRow>
    );
  }
````
**Screenshots**
https://user-images.githubusercontent.com/26652057/105335437-5447fe80-5bd8-11eb-839e-8e26c4163625.mp4

Do I have to open an issue aswell in the RecycleList repo ? Is there any way to detect the scroll distance vertically and to prevent the user to scroll unless a certain distance is reached ?

**Environment :**
 - OS: Android 10
 - RNSLV Version: [3.2.5]
 - RN Version: [0.63.3]

**Comment by ingerable** [comment]
I have tested with https://www.npmjs.com/package/react-native-swipeable-row and the scroll is locked when I am swiping the rows.

**Comment by jemise111** [comment]
Hey @ingerable `SwipeRow` has a prob called `setScrollEnabled`, you can pass a function that takes a bool to enable or disable scroll on the parent list view

This is done by default for you when you use both the `SwipeListView` and the `SwipeRow` but since in this case the package has no access to the parent ListView, you have to pass the prop yourself.

Give it a try and LMK how it works for you!

**Comment by ingerable** [comment]
Yes it is working thanks !
For SwipeRow component: <br>
`       setScrollEnabled={(enable) => {
          this.setState({enableScroll: enable})
        }}`

To add on RecycleListView (or any flatlist): <br>
`scrollEnabled={this.state.enableScroll}`
