### ISSUE TITLE
0.3.0 not working with RN0.32.0 

### ISSUE THREAD

**Issue by npomfret** [jemise111/react-native-swipe-list-view#54]
When I swipe a row in a SwipeListView it immediately bourse back and won't stay open.  I tried reverting back to 0.2.3 but that didn't help, so maybe is an issue with RN0.32

**Comment by jemise111** [comment]
Hm @npomfret I'm personally using 0.3.0 with RN 0.32 and haven't had an issue so far. If you could post your code and any other information about platform, OS, or version number that'd be really helpful and I'd be happy to take a look, thanks!

**Comment by npomfret** [comment]
```
  <SwipeListView
            previewFirstRow={true}
            previewOpenValue={50}
            keyboardDismissMode="on-drag"
            removeClippedSubviews={false}
            enableEmptySections={true}
            scrollEventThrottle={2}
            dataSource={dataSource}
            renderRow={this.renderRow.bind(this)}
            renderHiddenRow={this.renderHiddenRow.bind(this)}
            renderSeparator={this.renderSeparator.bind(this)}
            renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} />}
            rightOpenValue={-75}
            disableLeftSwipe={true}
          />

```

**Comment by npomfret** [comment]
Solved it.  

I was missing a `leftOpenValue={xx}` prop.  I thought because I'd used `disableLeftSwipe={true}` that it wasn't needed, but without it the right swipe just bounces back.  Strangely, I tried settings it to 0 and 1 but neither worked.  So I set it to 75 and the right swipe works now.

Thanks!
