### ISSUE TITLE
Android loads hidden item firsts 

### ISSUE THREAD

**Issue by Lisamarie73187** [jemise111/react-native-swipe-list-view#541]
When going to the page with the swipeListView the hidden items shows first and there is a weird flashing. Is there anything that can be done to avoid this?

[http://g.recordit.co/OVfueqeNPj.gif](http://g.recordit.co/OVfueqeNPj.gif)

**Comment by anthlasserre** [comment]
Hey @Lisamarie73187, can you share a sample of your code please that we can understand more ?

**Comment by jemise111** [comment]
Hey @Lisamarie73187 sorry for the delay. This has been reported a few times before and generally is not a problem with this component but rather with navigation libraries that fade in non-absolutely positioned elements. You can find suggestions for fixes here:

https://github.com/jemise111/react-native-swipe-list-view/issues?q=is%3Aissue+flash+is%3Aclosed

Thanks!
