### ISSUE TITLE
Need to touch twice to fire onPress after adding RefreshControl

### ISSUE THREAD

**Issue by QiYuNew** [jemise111/react-native-swipe-list-view#543]
**Describe the bug**
After adding RefreshControl, need to touch the screen first and then touch the list items, the onPress of inner Touchableopacity can be fired. Both renderItem and renderHiddenItem use Touableopacity for the top-most.

**To Reproduce**
1. add RefreshControl for swipeListView
2. refreshing state and refreshing function(useCallback) are working well
3. pull to refresh
4. press the list item not firing onPress
5. press the list item or the whole screen first, onPress works

**Screenshots**
            <SwipeListView
                // onRefresh={refreshDiary}
                // refreshing={refreshing}
                refreshControl={
                    <RefreshControl 
                        onRefresh={refreshDiary}
                        refreshing={refreshing}
                    /> 
                }
                data={diarylist}
                keyExtractor={(item) => item.id}
                renderItem={renderDiaryItem}
                renderHiddenItem={renderHiddenItem}
                disableRightSwipe={true}
                rightOpenValue={-75}
                closeOnRowPress={true} // close when press
                closeOnRowOpen={true} // close when another open
                closeOnScroll={true} // close when scroll
                closeOnRowBeginSwipe={true} // close when swipe another open
            />

**Environment (please complete the following information):**
 - OS: iOS 14.4
 - RNSLV Version: v3.2.6
 - RN Version: v0.63.4

**Comment by QiYuNew** [comment]
I find maybe this is related to the following
https://github.com/facebook/react-native/issues/20011

**Comment by QiYuNew** [comment]
disableScrollViewPanResponder = {true} works for me - by @ravirajn22
rn 0.63.4

**Comment by jemise111** [comment]
Hey @QiYuNew seems like you found a fix and it definitely looks related to a RN bug with ListViews and not specifically this library. Going to close this one, thanks!
