### ISSUE TITLE
Can I make section headers as sticky headers in the flat list?

### ISSUE THREAD

**Issue by raghavmathur1993** [jemise111/react-native-swipe-list-view#545]
I need to make the section headers as sticky headers. Please help.

**Comment by jemise111** [comment]
Hi @raghavmathur1993 sorry for the delay. Please see here for a full example of using a section list => https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/examples/sectionlist.js

You can pass any props to the `SwipeListView` that you would normally pass to a `SectionList`, see more here https://reactnative.dev/docs/sectionlist#stickysectionheadersenabled
