### ISSUE TITLE
rowMap object unpopulated on first render

### ISSUE THREAD

**Issue by unstableair** [jemise111/react-native-swipe-list-view#546]
The rowMap object passed to each row appears to be unpopulated on first render of a SwipeListView

Subsequent re-renders do pass a populated rowMap

I've created a snack that illustrates the problem
It logs the rowMap objects keys and on first render the objects passed to all rows are empty.
Pressing the 'Update' button will force a re-render which then shows the keys.

https://snack.expo.io/@unstableair/rowmap-unpopulated-example

react-native@0.63.4
react-native-swipe-list-view@3.2.6

**Comment by jemise111** [comment]
Hey @unstableair I believe this is a long outstanding issue because the rowMap is populated by tapping into the `ref` callback of each row. So only **_after_** a row is rendered will it be added to the rowMap. Is this causing you any problems?

**Comment by unstableair** [comment]
Hi @jemise111 thanks for the explanation and the plugin which has some great features. I call manuallySwipeRow() from SwipeRow to open the row on a longPress (common on Android) but this only works after the 2nd render. I guess the best workaround would be to immediately force a 2nd render of the SwipeListView. or is there a better way?

**Comment by jemise111** [comment]
Can you show me some example code? I think there should be a way around that

**Comment by unstableair** [comment]
This snack has the longPress to open logic but only works after you click the button to force a re-render

https://snack.expo.io/@unstableair/press-and-hold-issue

**Comment by jemise111** [comment]
@unstableair Oops! Forgot you already sent that, thank you!

I modified your snack code and was able to make it work without re-rendering by passing in a reference to the `rowMap` object (which is later populated with rows)

```
import React, { useState } from 'react';
import {
  Text,
  View,
  StyleSheet,
  Button,
  TouchableHighlight,
} from 'react-native';
import { SwipeListView, SwipeRow } from 'react-native-swipe-list-view';

const openRow = (rowMap, key) => {               <===== CHANGE HERE
  const row = rowMap[key];                       <===== CHANGE HERE
  if (row && !row.isOpen) {
    row.manuallySwipeRow(-75);
  }
};

function Row(data, rowMap) {

  return (
    <SwipeRow>
      <View style={styles.rowBack}>
        <Text>Left</Text>
        <Text>Right</Text>
      </View>
      <TouchableHighlight
        underlayColor="#000044"
        onLongPress={() => openRow(rowMap, data.item.key)}>         <===== CHANGE HERE
        <View style={styles.rowFront}>
          <Text>Press & Hold to open ({data.item.text})</Text>
        </View>
      </TouchableHighlight>
    </SwipeRow>
  );
}

export default function App() {
  const [listData, setListData] = useState([
    { key: 1, text: 'item 1' },
    { key: 2, text: 'item 2' },
    { key: 3, text: 'item 3' },
  ]);

  return (
    <>
      <Button onPress={() => setListData([...listData])} title="Click me to force a Re-render" />
      <SwipeListView data={listData} renderItem={Row} />
    </>
  );
}

const styles = StyleSheet.create({
  rowFront: {
    alignItems: 'center',
    backgroundColor: '#CCC',
    borderBottomColor: 'black',
    borderBottomWidth: 1,
    justifyContent: 'center',
    height: 50,
  },
  rowBack: {
    alignItems: 'center',
    backgroundColor: '#DDD',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
  },
});

```

**Comment by unstableair** [comment]
@jemise111  The update works perfectly. Thanks so much for the help!

**Comment by code-by** [comment]
Why `rowMap` is empty if one put `SwipeRow` inside e.g. `View` ? How to solve problem with empty `rowMap` putting `SwipeRow` inside another component?
