### ISSUE TITLE
Automatically close row doesn't work

### ISSUE THREAD

**Issue by jainshreyp** [jemise111/react-native-swipe-list-view#549]
**Describe the bug**
- My items that are rendered, aren't automatically closing when another one is opened, and aren't closing as soon as they are pressed (even when i manually set the options on the component). They all open and don't close until they are manually closed with a swipe in the opposite direction to the way they were opened

**To Reproduce**
Create a component with all the basic options, and use section list, with section list data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/75991940/113642995-2d359080-964f-11eb-897a-c8fc6442236b.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android]
 - RNSLV Version: [e.g. v2.0.2]
 - RN Version: [e.g. v60.0.5]

**Comment by jemise111** [comment]
@jainshreyp 99% of the time this is due to the objects not having a `key` property or your `keyExtractor` being implemented incorrectly. Can you please double check these two things and if you don't find any problems please post some example code I could look at, thanks!

**Comment by jainshreyp** [comment]
Ahhh your right, forgot to pass my keyExtractor haha! Thanks for your help, sorry for not being more informed, I didn't see the keyExtractor on the swipe list (but i realized thats cuz u had the key property). Thank you!
