### ISSUE TITLE
Swipe LandScape issue

### ISSUE THREAD

**Issue by mauhammadadnan** [jemise111/react-native-swipe-list-view#550]
SwipeListView working perfectly in portrait mode, but in Landscape mode delete and close button show center of flex which is wrong
![Screenshot_2021-04-06-12-31-09 1](https://user-images.githubusercontent.com/33023754/113677591-2f433200-96d7-11eb-9052-2f12b74b479b.png)
![Screenshot_2021-04-06-12-57-16](https://user-images.githubusercontent.com/33023754/113678393-02dbe580-96d8-11eb-91dd-a88c84a66947.png)
![Screenshot_2021-04-06-12-57-11](https://user-images.githubusercontent.com/33023754/113678399-040d1280-96d8-11eb-89db-627f93c43540.png)

**Comment by mauhammadadnan** [comment]
rowBack: {
        flex: 1,
        width:"100%",
        flexDirection:'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },

**Comment by jemise111** [comment]
@mauhammadadnan can you please try this? https://github.com/jemise111/react-native-swipe-list-view/issues/491#issuecomment-661063501

**Comment by mauhammadadnan** [comment]
Thanks for you reply issue gonna resolved  " recalculateHiddenLayout={true}
"
