### ISSUE TITLE
No scroll while swiping row (basically don't scroll when swiping diagonally)

### ISSUE THREAD

**Issue by jainshreyp** [jemise111/react-native-swipe-list-view#551]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/jemise111/react-native-swipe-list-view/issues) before creating one.

**Describe the bug**
Compared to the expo (I have mostly the same fields set) I can scroll and open a row (which is something I shouldn't be able to do. I'm sure there is a default value, and I saw the onScroll function, but not sure where I'm doing it wrong. 

**To Reproduce**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS or Android]
 - RNSLV Version: [e.g. v2.0.2]
 - RN Version: [e.g. v60.0.5]

**Comment by jemise111** [comment]
Hi @jainshreyp did you solve your issue?

**Comment by jainshreyp** [comment]
Hey @jemise111 , this issue was found, I realized that that wrapping a ScrollView around the Swipe List View, will make it be able to scroll and swipe at the same time.
