### ISSUE TITLE
SwipeListExample: Unable to resolve module SwipeListView - could not be found

### ISSUE THREAD

**Issue by chriswayg** [jemise111/react-native-swipe-list-view#554]
SwipeListExample fails with the same error both on iOS and Android

**To Reproduce**
followed all the steps for SwipeListExample

Error text on iOS iPhone 11 & Android Pixel 4 API29 Simulators:

```
error: bundling failed: Error: Unable to resolve module `../SwipeListView` 
from `...react-native-swipe-list-view/SwipeListExample/examples/actions.js`: 

The module `../SwipeListView` could not be found 
from `...react-native-swipe-list-view/SwipeListExample/examples/actions.js`.

Indeed, none of these files exist:
  * `/...ReactNativeProjects/react-native-swipe-list-view/SwipeListExample/
  SwipeListView(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
```
**Environment - yarn react-native info**
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 2.84 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /var/folders/9l/wwt6ljv10b9fhwjsybmw3d140000gn/T/yarn--1621579498560-0.8442548028715078/node
    Yarn: 1.22.5 - /var/folders/9l/wwt6ljv10b9fhwjsybmw3d140000gn/T/yarn--1621579498560-0.8442548028715078/yarn
    npm: 6.14.13 - ~/.nodenv/versions/14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3

**Comment by chriswayg** [comment]
See pull request above

`import SwipeListView from 'SwipeListView';`

in actions.js should be:

`import { SwipeListView } from 'react-native-swipe-list-view';`

**Comment by jemise111** [comment]
Commented on the PR, this is expected. If you'd like to work on the repo you can run `yarn run dev` to fix this, thanks!
