### ISSUE TITLE
How to combine swipe to delete and standalone swipe

### ISSUE THREAD

**Issue by assimovt** [jemise111/react-native-swipe-list-view#559]
I am trying to combine the examples of **SwipeToDelete** and **StandaloneSwipeRow**.

Basically, I want to simulate the Apple Mail behavior, where you swipe a bit and it stops to show you a set of actions. Then you swipe further and it performs the outermost action, while also resizing it.

I've managed to dynamically change the size of the last item with `recalculateHiddenLayout`, however, I can't figure out the right options for the stop + full swipe behavior. I've tried all of the combinations of `stopRightSwipe`, `rightOpenValue`, `rightActionValue`, and `rightActivationValue` w/o any luck.

Any ideas on how I could achieve it? Thanks! ✌️

**Comment by jemise111** [comment]
Hey @assimovt a bit selfish on my part but you mind uploading a gif or video of what it is you're trying to achieve? I don't have the Apple Mail app. I can give it a shot after that, thanks!

**Comment by assimovt** [comment]
Sure @jemise111 Here is a little preview. There, I swiped to the left a bit and it opened action buttons. Then, I swiped further some threshold and it swiped till the end and performed the last action in the list - Archive (purple). Similarly, I swiped to the right and it opened Delete action button, and swiped further to perform it. As mentioned, I've managed to do all of that resizing/behavior but can't figure out how to workaround stop & long swipe. Would really appreciate your input 👍 

![Image](https://user-images.githubusercontent.com/5113/121766523-b0dd9300-cb52-11eb-900f-74cc21c0a8cf.GIF)

**Comment by jemise111** [comment]
Hey @assimovt this is most certainly possible, just takes a little bit of tricky animated interpolation work. It's possible you can use actions. However, as that was an OS contribution, I'm not as familiar with that style of doing things. For something like this I would use the swipe value directly as the basis for all animations and interpolated styles. Here's the code and a demo I used to achieve what I think you are going for, note this is rough code, you should clean this up and use your own values for hidden row items and screen width:

```
import React, { useState, useRef } from 'react';
import {
    Animated,
    Dimensions,
    Image,
    StyleSheet,
    Text,
    TouchableHighlight,
    View,
} from 'react-native';

import SwipeListView from '../SwipeListView';

const rowTranslateAnimatedValues = {};
Array(20)
    .fill('')
    .forEach((_, i) => {
        rowTranslateAnimatedValues[`${i}`] = new Animated.Value(1);
    });

export default function SwipeToDelete() {
    const [listData, setListData] = useState(
        Array(20)
            .fill('')
            .map((_, i) => ({ key: `${i}`, text: `item #${i}` }))
    );
    const swipeValue = useRef(new Animated.Value(0)).current;
    const [fullWidthMode, setFullWidthMode] = useState(false);

    const animationIsRunning = useRef(false);

    const onRowDidClose = () => {
        setFullWidthMode(false);
    };

    const onSwipeValueChange = swipeData => {
        const { key, value } = swipeData;
        swipeValue.setValue(value);
        if (value <= -150 && !fullWidthMode) {
            setFullWidthMode(true);
        }
        if (value < -375 && !animationIsRunning.current) {
            animationIsRunning.current = true;
            Animated.timing(rowTranslateAnimatedValues[key], {
                toValue: 0,
                duration: 200,
                useNativeDriver: false,
            }).start(() => {
                const newData = [...listData];
                const prevIndex = listData.findIndex(item => item.key === key);
                newData.splice(prevIndex, 1);
                setListData(newData);
                animationIsRunning.current = false;
                setFullWidthMode(false);
            });
        }
    };

    const renderItem = data => (
        <Animated.View
            style={[
                styles.rowFrontContainer,
                {
                    height: rowTranslateAnimatedValues[
                        data.item.key
                    ].interpolate({
                        inputRange: [0, 1],
                        outputRange: [0, 50],
                    }),
                },
            ]}
        >
            <TouchableHighlight
                onPress={() => console.log('You touched me')}
                style={styles.rowFront}
                underlayColor={'#AAA'}
            >
                <View>
                    <Text>I am {data.item.text} in a SwipeListView</Text>
                </View>
            </TouchableHighlight>
        </Animated.View>
    );

    const renderHiddenItem = () => (
        <View
            style={[
                styles.rowBack,
                {
                    backgroundColor: fullWidthMode ? 'red' : 'white',
                },
            ]}
        >
            {!fullWidthMode && (
                <Animated.View
                    style={[
                        styles.backRightBtn,
                        styles.backRightBtnLeft,
                        {
                            right: swipeValue.interpolate({
                                inputRange: [-150, 0],
                                outputRange: [75, 0],
                                extrapolate: 'clamp',
                            }),
                            width: swipeValue.interpolate({
                                inputRange: [-150, 0],
                                outputRange: [75, 0],
                                extrapolate: 'clamp',
                            }),
                        },
                    ]}
                >
                    <Text style={styles.backTextWhite}>L</Text>
                </Animated.View>
            )}
            <Animated.View
                style={[
                    styles.backRightBtn,
                    styles.backRightBtnRight,
                    !fullWidthMode
                        ? {
                              right: 0,
                              width: swipeValue.interpolate({
                                  inputRange: [-150, 0],
                                  outputRange: [75, 0],
                                  extrapolate: 'clamp',
                              }),
                          }
                        : {
                              right: swipeValue.interpolate({
                                  inputRange: [-375, 0],
                                  outputRange: [300, -75],
                              }),
                              width: 75,
                          },
                ]}
            >
                <Image
                    source={require('../images/trash.png')}
                    style={styles.trash}
                />
            </Animated.View>
        </View>
    );

    return (
        <View style={styles.container}>
            <SwipeListView
                disableRightSwipe
                data={listData}
                renderItem={renderItem}
                renderHiddenItem={renderHiddenItem}
                rightOpenValue={-Dimensions.get('window').width}
                onSwipeValueChange={onSwipeValueChange}
                useNativeDriver={false}
                onRowDidClose={onRowDidClose}
            />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        backgroundColor: 'white',
        flex: 1,
    },
    backTextWhite: {
        color: '#FFF',
    },
    rowFront: {
        alignItems: 'center',
        backgroundColor: '#CCC',
        borderBottomColor: 'black',
        borderBottomWidth: 1,
        justifyContent: 'center',
        height: 50,
    },
    rowBack: {
        alignItems: 'center',
        backgroundColor: 'red',
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingLeft: 15,
    },
    backRightBtn: {
        alignItems: 'center',
        bottom: 0,
        justifyContent: 'center',
        position: 'absolute',
        top: 0,
        overflow: 'hidden',
    },
    backRightBtnRight: {
        backgroundColor: 'red',
    },
    backRightBtnLeft: {
        backgroundColor: 'blue',
    },
    trash: {
        height: 15,
        width: 15,
    },
});

```
![SwipeDelete mov](https://user-images.githubusercontent.com/4265163/122600318-3373c000-d035-11eb-90bd-cc104d234e1f.gif)

**Comment by assimovt** [comment]
@jemise111 Thanks a lot for the example. That's exactly what I've managed to build myself but the only thing was missing is being able to stop the animation when you swipe a bit. There are basically two steps: First, you a bit swipe and it opens, stops. Then you swipe further and it swipes automatically to the end as you've shown. I've tried to use the `stopRightSwipe` to handle stopping, but then it does not let you swipe till the end ofc. How would you extend your example to support that behavior if anyhow possible? 🤓

**Comment by jemise111** [comment]
Sorry @assimovt I'm having a hard time understanding the additional functionality you want to add. Can you explain further? I don't see any case where you would want to stop the user from swiping with these examples

**Comment by assimovt** [comment]
@jemise111 Pls check on my video above that when I first swiped it paused the animation (what's missing). Only when I swiped further the threshold it started animating the last action in the row (like you have in the demo).

**Comment by jemise111** [comment]
@assimovt I'm watching the first video but I don't see anything in the mail app that stops the animation. If you're asking if it's possible to show just the buttons without immediately switching to the last action maybe you mean something like this? I'm still not 100% sure...

![RenderHidden mov](https://user-images.githubusercontent.com/4265163/122944210-3c1e0c00-d33d-11eb-847e-5c878034360c.gif)

**Comment by simplenotezy** [comment]
@jemise111 Sorry to interrupt here, but I hope I can ask a related question to this. I looked at the example here: https://snack.expo.dev/@simplenotezy/react-native-swipe-list-view, specifically `swipe_to_delete.js`.

1. How can the example know that the user released the finger? Naturally, you don't want to trigger a deletion event, before the finger is released. Say the user just swiped, and then changed his mind, and moves the swipe "back" to its position. The demo takes care of this perfectly, I just don't seem to be able to replicate a similar approach in my project.

2. What's the reason behind: `if ( value < -Dimensions.get('window').width)`? I would perhaps write it as: `if ( value > (Dimensions.get('window').width / 2) ) {`, so a deletion only should be triggered if the item was swiped more than half way through the screen

Thanks in advance.
