### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by Angelk90** [jemise111/react-native-swipe-list-view#560]
Hi @jemise111 ,
It would be possible to implement an example that allows drag and drop, if it is enabled.

![image](https://res.cloudinary.com/flycatcher/image/upload/v1572289775/listgif_igl9j7.gif)

**Comment by jemise111** [comment]
Hey @Angelk90, drag and drop is a separate feature set that is a really out of the scope of this component. I would recommend using one of the OS drag and drop flatlist libraries and in the renderItem use a `<SwipeRow />` from this library. You'll lose a little of the built in 'SwipeListView' functionality but it should get you a good chunk of the way there. Hope that helps!

**Comment by bmitioglov** [comment]
I wonder if it's possible to combine it with this library https://github.com/computerjazz/react-native-draggable-flatlist
