### ISSUE TITLE
Warning: Animated.event now requires a second argument for options

### ISSUE THREAD

**Issue by Nogias9x** [jemise111/react-native-swipe-list-view#568]
**Describe the bug**
Warning: `Animated.event now requires a second argument for options`

**To Reproduce**
```js

![](https://f9.photo.talk.zdn.vn/8038413744966505575/55da1030249ed3c08a8f.jpg)

import { SwipeItem, SwipeButtonsContainer } from 'react-native-swipe-item';
  const btn = (
    <SwipeButtonsContainer
      style={{
        alignSelf: 'center',
        aspectRatio: 1,
        flexDirection: 'column',
      }}
    >
      {buttonContent}
    </SwipeButtonsContainer>
  );

  return (
      <SwipeItem rightButtons={btn} >
        <Content />
      </SwipeItem>
  );
```

**Screenshots**
![55da1030249ed3c08a8f](https://user-images.githubusercontent.com/11822492/130224683-bd1f6703-fb75-4b41-84c7-505d4f137e40.jpg)

**Environment (please complete the following information):**
 - OS: Android 10
 - RNSLV Version: 0.4.0
 - RN Version: 0.63.4

**Comment by jemise111** [comment]
@Nogias9x this is not the GH repo for `react-native-swipe-item`
