### ISSUE TITLE
VirtualizedList supported?

### ISSUE THREAD

**Issue by TommySorensen** [jemise111/react-native-swipe-list-view#569]
I see no documentation about the `SwipeListView` library support the `VirtualizedList` which is kind of the same as a normal FlatList. Can someone provide information about if it's supported? I tried with using the `data`, `getItem` and `getItemCount` props together but i keep getting error `FlatList does not support custom data formats.` on the `<SwipeListView` component

**Comment by DmitryKvant** [comment]
The same error
Any idea?

**Comment by jemise111** [comment]
Hi @TommySorensen this lib currently does not support use of `VirtualizedList` out of the box. Your best bet would probably be to render a `VirtualizedList` and just use the `SwipeRow` for your individual list items. You'd lose some of the functionality of `SwipeListView` but that's the best I can offer at this time, sorry
