### ISSUE TITLE
Get Error when add ScrollView To component

### ISSUE THREAD

**Issue by edenmeshulam** [jemise111/react-native-swipe-list-view#570]
Get this error when i put the `<SwipeListView>` inside a `<ScrollView>`:

VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. 

![image](https://user-images.githubusercontent.com/20186807/130457823-99a4df21-9036-4c4d-9ce1-2910f35dffb4.png)

any ideas ? :)

 - OS: BOTH
 - RN Version: @latest

**Comment by jemise111** [comment]
Hi @edenmeshulam this is an error from the RN library itself. You should follow what it says, remove any container ScrollViews around the `SwipeListView`. If you need more scrollable content on the page you should use the list's Header and Footer components, thanks

**Comment by ymc-thzi** [comment]
just add  
```
<SwipeListView
                  scrollEnabled={false}
                  ...
```
then you can keep your surrounding ScrollView
