### ISSUE TITLE
Missing examples for actions

### ISSUE THREAD

**Issue by simplenotezy** [jemise111/react-native-swipe-list-view#571]
Looking at https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/actions.md in the bottom it says:

"See the actions example for reference."

But that link links to itself.

The examples would be really helpful, especially because it looks like the swipe_to_delete.js from https://snack.expo.dev/@jemise111/react-native-swipe-list-view? does not seem to leverage 'actions'.

Is it an error, or am I missing something?

**Comment by jemise111** [comment]
Oops! Fixed with #575 , thanks for noticing :)
