### ISSUE TITLE
SwipeRow: close after onRightPress

### ISSUE THREAD

**Issue by mwegener-com** [jemise111/react-native-swipe-list-view#579]
**Describe the bug**
I need to use this component in a vertical ScrollView, but since it is not possible to nest this component in such a ScrollView, I tried to build my own solution with SwipeRow.

In doing so, I have the following problem:
How can I hide the backView after pressing it?
It is working fine if I delete the last item, but not if I delete anything else except the last item.

I think with the following video it will become clearer:

https://user-images.githubusercontent.com/64470126/139585059-87cce9ce-3f15-4c33-8f3a-53a479d6f69d.mov

**To Reproduce**
```javascript
	<CollapsibleSection label={language.WINE_RECOMMENDATIONS}>
		{wineRecommendations.map((wine, index) => (
			<SwipeRow
				key={index}
				disableRightSwipe
				rightOpenValue={-75}
				preview={index === 0}
				style={styles.wineRow}
			>
				<DeleteItem
					onPress={() => {
						const newData = [...wineRecommendations];
						newData.splice(index, 1);
						setWineRecommendations(newData);
						}}
		         	/>
				<ListDetailsItem
					data={wine}
					onPress={() =>
						props.navigation.navigate('WineEdit', {
							...params...
						})}
				/>
			</SwipeRow>
		))}
		
               <ListAddItem onPress={() => props.navigation.navigate('WineEdit', { mode: NEW_FOOD_WINE })} />
	</CollapsibleSection>
```

**Environment:**
 - OS: iOS
 - RNSLV Version: 3.2.9
 - RN Version: 0.64.2

Thanks for help!

**Comment by mwegener-com** [comment]
Another problem is, that sometimes the back view isn't visible at all. 
Maybe you also have an idea for this:

https://user-images.githubusercontent.com/64470126/139586725-e3ccf5fa-51f5-4a90-85c8-8bb05c20c4b2.mov

**Comment by mwegener-com** [comment]
Solved it using react-native-gesture-handler

**Comment by kkureli** [comment]
hi, how did u solve it ?

**Comment by sakthimaheshalgo** [comment]
For the first issue, make sure the objects present in array supplied to the package has a key property whose value is unique other than index.

**Comment by kkureli** [comment]
thanks, I solved the problem by using ref
