### ISSUE TITLE
Is there any way to close the swipe manually ?

### ISSUE THREAD

**Issue by GokuVijay** [jemise111/react-native-swipe-list-view#605]
I want my swipe list to close while clicking a button. I didn't tried many way to close it, but can't find a way. please reply if there's any solution.

**Comment by AdamLee321** [comment]
See the following link: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/manually-closing-rows.md

**Comment by GokuVijay** [comment]
Thanks dude ,I finally solved my issue 

> See the following link: https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/manually-closing-rows.md

**Comment by lively-krishnan** [comment]
如果按页面状态去执行关闭，该如何操作
useEffect(() => {
    if(mode === 2) {
       // 如何触发关闭
    }
  }, [mode]);
