### ISSUE TITLE
Weird issue when switching between components

### ISSUE THREAD

**Issue by eamonpenland** [jemise111/react-native-swipe-list-view#61]
Hey! great component, but I'm having a weird issue that I can't seem to track down. I have a parent component that determines which rn component to render based on a selected filter. The components are changed correctly, but when I want to navigate back to the component with the react-native-swipe-list-view i must press the button twice to get the list view to show on the screen. None of the underlying data has changed. Any ideas?

**Comment by basequatro** [comment]
@eamonpenland  Remove styles, or props, one by one, until you find the guilty.
I had this problem and was a color: 'white' on the Swipe component.
You can also change to default listview from RN to know if its a problem with this component.

**Comment by jemise111** [comment]
Hey @eamonpenland, hm.. I agree with @basequatro 's suggestions. My hunch is that this wouldn't be related to this component but it is possible.

If you see here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L76 the example is actually doing exactly what you're describing. There are two SwipeListView's and a toggle, when you press the toggle one of the two SwipeListView's shows and the other hides. I haven't had any problems like you're describing.

Happy to investigate this more if you want to paste some of the code you're using. Thanks!

**Comment by jemise111** [comment]
Closing as I haven't heard anything here for a while
