### ISSUE TITLE
Can't programatically close a row

### ISSUE THREAD

**Issue by npomfret** [jemise111/react-native-swipe-list-view#62]
I'm using a per-row configuration and am seeing some strange behaviour.  I think its related to the view being updated with new rows while an existing row is a swiped state.  It looks like its getting confused as to while row was in the swiped state when the model was updated.  I'm not sure how to fix, but a workaround might be to programatically close all rows before the model changes - which in my case would be fine.  But how do you do that?

**Comment by jemise111** [comment]
Hm @npomfret I'll have to look into this further but for now you could try keeping a ref to your `SwipeListView` and calling:

`this.refs.swipeListView.safeCloseOpenRow()`

That's a bit of a hack but it might work

**Comment by npomfret** [comment]
Thanks for the suggestion but it didn't seem to work.  I'm using per row behaviour, I think that's what's causing it to fail.  In fact I noticed that onRowPress and onRowOpen aren't being called either.  Maybe I've set it up wrong?

**Comment by vestvud** [comment]
+1

**Comment by lednhatkhanh** [comment]
+1, any news on this?

**Comment by stoufa88** [comment]
It is working for me

**Comment by kingorange2309** [comment]
@jemise111 hi,is it possible to programatically open a row ?

**Comment by jemise111** [comment]
@kingorange2309 Yes it is. Here is an example of opening a row programmatically when it is touched. You can use the `manuallySwipeRow` instance method on swipe rows.

```
<SwipeListView
	dataSource={this.ds.cloneWithRows(this.state.listViewData)}
	renderRow={(data, secId, rowId, rowMap) => (
		<TouchableHighlight
			onPress={_ => rowMap[`${secId}${rowId}`].manuallySwipeRow(75)}
			style={styles.rowFront}
			underlayColor={'#AAA'}
		>
			<View>
				<Text>I'm {data} in a SwipeListView</Text>
			</View>
		</TouchableHighlight>
	)}
	renderHiddenRow={(data, secId, rowId, rowMap) => (
		<View style={styles.rowBack}>
			<Text>Left</Text>
			<View style={[styles.backRightBtn, styles.backRightBtnLeft]}>
				<Text style={styles.backTextWhite}>Right</Text>
			</View>
			<TouchableOpacity style={[styles.backRightBtn, styles.backRightBtnRight]} onPress={_ => this.deleteRow(secId, rowId, rowMap)}>
				<Text style={styles.backTextWhite}>Delete</Text>
			</TouchableOpacity>
		</View>
	)}
	leftOpenValue={75}
	rightOpenValue={-150}
/>
```

**Comment by jemise111** [comment]
@npomfret I'm trying to reproduce your issues but I can't seem to. It would be super helpful if you could post all the version information (SLV version, RN version, device platform and OS version) and the code you're using.

![](http://g.recordit.co/FkXxViX1pb.gif)

**Comment by kingorange2309** [comment]
@jemise111  yes,it worked ,thx!

**Comment by npomfret** [comment]
Is it possible just using a SwipeRow?

**Comment by KingAmo** [comment]
@npomfret have you solve this problem?

**Comment by npomfret** [comment]
@KingAmo sorry no, I stopped using react-native

**Comment by jemise111** [comment]
Closing as inactive, please re open if anyone still has this issue
