### ISSUE TITLE
How set DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD properly?

### ISSUE THREAD

**Issue by bellatu** [jemise111/react-native-swipe-list-view#64]
If set  DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD value too large, the row can not swipe out easily. If set DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD too small, when scroll the swipe list, the row is easy to bring out. 

The large DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD value set 4.
const DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD = 4;
 _onMoveShouldSetPanResponder = (event, gestureState) => {
    const { dx } = gestureState;
    return Math.abs(dx) > DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD;
  }

The small DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD value set 0.
const DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD = 0;
_onMoveShouldSetPanResponder = (event, gestureState) => {
    const { dx } = gestureState;
    return Math.abs(dx) > DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD;
  }

**Comment by jemise111** [comment]
Fixed by #106
