### ISSUE TITLE
Using renderHiddenRows with per row behaviour

### ISSUE THREAD

**Issue by jorelllinsangan** [jemise111/react-native-swipe-list-view#65]
I'm looking through your example and you're not using renderHiddenRows when implementing a per row behaviour list. Are we not able to use that property when doing per row behaviour?

**Comment by levitanong** [comment]
Each SwipeRow requires two children: the first child will always be what will be rendered as renderHiddenRows, and the second child will be the row itself. You'll simply want to work on the first child.

It isn't explicitly stated in the doc, but as you can see here, there are two elements.
https://github.com/jemise111/react-native-swipe-list-view#per-row-behavior

**Comment by levitanong** [comment]
@jorelllinsangan No problem.

The thing is, hiddenRow is just a convenience method. Under the hood, it actually just uses SwipeRow, and calls hiddenRow as the first element.
See https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L104

**Comment by jemise111** [comment]
Thanks @levitanong for answering!

@jorelllinsangan fair point. I think it's just matter of preference but if you want to submit a PR for a hiddenRow prop feel free.

If you do so just make sure not to break backwards compatibility and check for both cases, thanks!

Closing this as it looks like the problem's been resolved.
