### ISSUE TITLE
Rows with different height

### ISSUE THREAD

**Issue by vestvud** [jemise111/react-native-swipe-list-view#69]
Hello! 
Would you do support to rows with different height? Otherwise, rows height break.

**Comment by jemise111** [comment]
Hm @vestvud  I'm not sure what you mean. I tried running the example with rows with different heights and everything seems to be working fine! Here's the code:

![image](https://cloud.githubusercontent.com/assets/4265163/20033710/9a161e3c-a37d-11e6-8a9e-6f7a031ed7f5.png)

And the corresponding view

![image](https://cloud.githubusercontent.com/assets/4265163/20033706/8c729f1c-a37d-11e6-8a29-14ad987d1b7b.png)

**Comment by vestvud** [comment]
Thanks!
yes, i looked and it's really work, thanks!
and i used recalculateHiddenLayout, because, sometimes hidden row had wrong height, less than renderRow. 

p.s. but in your screen - first row is break. No? 
p.s.2 sorry, im have bad english. 
p.s.3 i had also question - when my list view is changed, opened row hovewer also stay opened. why it may be? 

`<SwipeListView
dataSource={this.ds.cloneWithRows(issuesList)}
                    disableRightSwipe
                    enableEmptySections
                    recalculateHiddenLayout
                    renderRow={(issue, secId, rowId, rowMap) => (
                        <IssuesListItem
                            onPress={() => rowMap[`${secId}${rowId}`].closeRow() }
                            issue={issue}
                            navigator={navigator}
                        />
                    )}
                    renderHiddenRow={(issue) => (
                        <View style={[styles.backRightBtn, styles.backRightBtnRight]}>
                            <TouchableOpacity
                                style={styles.favoriteButtonStyle}
                                onPress={() =>
                                dispatch(toggleIssueFavorite(issue.key, issue.favorite))}
                            >
                                <IconView
                                    name={issue && issue.favorite ? 'bookmark' : 'bookmark-outline'}
                                    size={28}
                                    color='#fff'
                                />
                            </TouchableOpacity>
                        </View>
                    )}
                    rightOpenValue={-70}
                    refreshControl={
                        <RefreshControl
                            refreshing={isFetching}
                            onRefresh={() => this.fetchIssuesList(1, true)}
                        />
                    }
                    renderFooter={() => (
                        !isFetching && moreIssuesExist &&
                            <TouchableOpacity
                                style={styles.IssuesList__moreButton}
                                onPress={() => (this.fetchIssuesList(issuesListPage + 1))}
                            >
                                <Text style={styles.IssuesList__moreButtonText}>
                                    Еще задачи
                                </Text>
                            </TouchableOpacity>
                    )}
                    renderHeader={() => (
                        !isFetching && issuesList.length === 0 &&
                            <Text style={styles.screenCapText}>Задач нет</Text>
                    )}
                />`
