### ISSUE TITLE
Close row on renderHiddenRow buttons?

### ISSUE THREAD

**Issue by Thorbenandresen** [jemise111/react-native-swipe-list-view#7]
Really great work, thanks for making this!

How can I close the row if I press on the one of the buttons in the `renderHiddenRow`func? 

```js
			renderHiddenRow={ rowData => (
						<View style={styles.rowBack}>
							<Text>Left</Text>
              
							<TouchableHighlight style={[styles.backRightBtn, styles.backRightBtnLeft]}
                  onPress={ ()=> this._setDefault(rowData)}>
								<Text style={styles.backTextWhite}>Make Default</Text>
							</TouchableHighlight>
              
							<TouchableHighlight style={[styles.backRightBtn, styles.backRightBtnRight]}
                  onPress={ ()=> this._delete(rowData)}>               
								<Text style={styles.backTextWhite}>Delete</Text>
							</TouchableHighlight>
						</View>
					)}
					leftOpenValue={75}
					rightOpenValue={-150}
				/>

```

**Comment by jemise111** [comment]
Thanks! Hm that's a great question. As it stands I'm not sure it's possible. I'll try to make this work over the weekend but if you want to look into it sooner I'd start by looking here:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L72

If it's possible to pass the SwipeRow's ref to the renderHiddenRow function, i.e. `renderHiddenRow(rowData, secId, rowId, rowRef)` then from within that function you could call rowRef.closeRow(). But passing that ref might not be so easy.

If you make any headway feel free to submit a PR, thanks!

**Comment by jemise111** [comment]
@Thorbenandresen fixed by #8. See this section of the README for more details https://github.com/jemise111/react-native-swipe-list-view#manually-closing-rows. Let me know if you still have issues, thanks! (published in 0.0.4)

**Comment by Thorbenandresen** [comment]
that works, thanks so much for fast fix!

**Comment by jemise111** [comment]
Note for anyone using this new functionality. v0.1.0 introduced a breaking change to how closeRow should be used. Please see https://github.com/jemise111/react-native-swipe-list-view#manually-closing-rows for details. Thanks!
