### ISSUE TITLE
renderRow not passing valid rowMap

### ISSUE THREAD

**Issue by jorelllinsangan** [jemise111/react-native-swipe-list-view#70]
I have this block of code
`<SwipeListView
              dataSource={this.ds.cloneWithRows(this.state.listViewData)}
              renderRow={this._renderRow.bind(this)}
            />`

For some reason, `_renderRow` gets a empty object `{}` for its `rowMap` argument. Any idea what's happening?

**Comment by jemise111** [comment]
Hey @jorelllinsangan. I just ran you're code in the example and I'm not having any problems with it. Here's the code:

![image](https://cloud.githubusercontent.com/assets/4265163/20033449/ef6339bc-a376-11e6-8038-c6eb5300dfb7.png)

And the corresponding logs:

![image](https://cloud.githubusercontent.com/assets/4265163/20033460/690cb75c-a377-11e6-8e36-243b8a414b90.png)

(the object looks empty in the debugger until you open it showing it's full of rows)

If you want to paste more code I'm happy to take another look, just please reopen a new issue, thanks!

**Comment by jorelllinsangan** [comment]
@jemise111: I should have followed this up. I figured out what was wrong. I'm very new to react-native and I was passing in rowMap to a component before it was even filled up. Basically, I was getting na empty object. I solved that by just passing in a function that closed the row for me.

**Comment by jemise111** [comment]
@jorelllinsangan No worries, glad you got it working!

**Comment by code-by** [comment]
have same problem

**Comment by deyanskiq** [comment]
Same here as well
