### ISSUE TITLE
Disable animation bouncing

### ISSUE THREAD

**Issue by robcalcroft** [jemise111/react-native-swipe-list-view#74]
Possibility to have a prop to disable the rows bouncing when they are swiped or when they return to their normal position

**Comment by jemise111** [comment]
Hey @robcalcroft I added the tension / friction props to the SwipeListView. You should be able to stop the animation by playing with those values.

Higher friction seems to do the trick. See the Spring animation here for more: https://facebook.github.io/react-native/docs/animations.html#core-api

Thanks!

**Comment by robcalcroft** [comment]
As an FYI, I found
```
tension={-2}
friction={5}
```
to work well to stop the rows bouncing on their way back.
