### ISSUE TITLE
[Question] Scrolling the listview

### ISSUE THREAD

**Issue by oximer** [jemise111/react-native-swipe-list-view#80]
How do I scroll manually scroll the list to its end?
There is any method for it?

**Comment by jorelllinsangan** [comment]
Do you mean a function that when its called, the scroll view goes to the bottom of the list? If so, I don't think that there's a specific function for it. Though I did find this: [https://github.com/facebook/react-native/issues/913]. It looks like you might have to do a bit of writing for you to accomplish this.

**Comment by oximer** [comment]
No, I mean a function like ScrollTo from https://facebook.github.io/react-native/docs/listview.html

**Comment by jorelllinsangan** [comment]
I don't think there is one. Does `ScrollTo` not work with this module?

**Comment by oximer** [comment]
To make it work, I need a reference for the listview. 
However, when I tried the access the component using reference it doesn't work. I keep returning null.

<SwipeListView
          ref={(input) => this.listView = input}

So, I can't do it unless I change this project to expose the listview inside the component.

**Comment by oximer** [comment]
I found a way. This component already expose the listview through a prop.
```
getReference(ref) {
    //Save it as a class attribute.
}

<SwipeListView
...
listViewRef={this.getReference.bind(this)}
...
/>
```
