### ISSUE TITLE
Implementing a different swipe behaviour

### ISSUE THREAD

**Issue by jorelllinsangan** [jemise111/react-native-swipe-list-view#82]
Hi @jemise111 

Have you ever thought of doing a swipe behaviour like this one: http://browniefed.com/blog/react-native-animated-listview-row-swipe/

The idea is an action gets triggered after a threshold. 

I tried implementing the behaviour above but for some reason, the whole row changes color and not just the view behind the actual row.

**Comment by jemise111** [comment]
@jorelllinsangan It's interesting but doesn't seem to be a behavior a lot of people have a need for. I haven't exposed the `handlePanResponderMove` prop in the `SwipeRow` but that would probably be necessary to achieve this. Feel free to submit a PR :) if it's something you're looking to do or post the code you're trying to use if you're having problems

Going to close this issue for now..

Closing this in the meantime as this doesn't seem
