### ISSUE TITLE
Slide row onpress

### ISSUE THREAD

**Issue by sances15** [jemise111/react-native-swipe-list-view#84]
Is it possible to open/slide the row when user touches the row.?

**Comment by jemise111** [comment]
Yep! Definitely possible but sort of a private feature so it's not documented. Something like this should do the trick:

```
class Component {

  onRowPress(rowRef) {
    if (this.rowIsOpen) {
      this.rowIsOpen = false;
      rowRef.closeRow();
    } else {
      this.rowIsOpen = true;
      rowRef.manuallySwipeRow(RIGHT_OPEN_VALUE);
    }
  }

  render() {
    <SwipeListView
      renderRow={ (rowData, secId, rowId, rowMap) => (
        <TouchableOpacity
          activeOpacity={1}
          onPress={ _ => this.onRowPress(rowMap[`${secId}${rowId}`]) }
        >
          <Row />
        </TouchableOpacity>
      )}
    />
  }

}
```

Also since you're maintaining taps on your own you may want to ensure ```closeOnRowPress={false}```

**Comment by jemise111** [comment]
Please let me know if that does the trick for you and feel free to close this issue if it does, thanks!

**Comment by sances15** [comment]
@jemise111  This is awesome. It did work. Thanks for helping out.

**Comment by jemise111** [comment]
Np, glad it worked!

**Comment by NerdDiffer** [comment]
@jemise111, I'm looking at your example code. What's the reasoning behind storing the `rowIsOpen` value directly on the component instance rather than in state?

**Comment by jemise111** [comment]
@NerdDiffer You don't really want to be changing state properties unless your UI depends on them because calling `setState()` will trigger a re-render. Since no UI depends on `rowIsOpen` I don't want it in state. Does that make sense?

**Comment by NerdDiffer** [comment]
It does, thank you!
