### ISSUE TITLE
Not working with ios

### ISSUE THREAD

**Issue by Jaafar-abusair** [jemise111/react-native-swipe-list-view#85]
Hi,

It' working perfect with Android, for iOS it's not working the hidden layer exist under the row, I can swap 2 pixel only and I can see there is button beneath it, My swap margin is 150 pixel.

OS version 10
Any idea?

**Comment by vivekmago** [comment]
Same issue

**Comment by Jaafar-abusair** [comment]
I had to turn off the open side menu by gesure

**Comment by jemise111** [comment]
Hey @Jaafar-abusair I'm not sure I understand your issue. I'm testing on an iPhone6 simulator running iOS 10.1 with RN 0.39.0 and I'm not having any issues with Swiping or seeing the hidden row. Could you provide the code you're using and I'll see if I can reproduce?

**Comment by Jaafar-abusair** [comment]
I had to stop the open side menu by gesture then it worked, I have iOS 10.2, another problem I have list it get loaded when opening the application the swap work but I can see the button under the swapped row, once I refreshed the list by pull down the button will become visible, any idea?

**Comment by tiffanyricks** [comment]
Hi @Jaafar-abusair, I Believe I am having the same problem with IOS 10 and the Swipe Right feature (Swipe left is disabled).   The application crashes when a user tries to swipe right.  What code to did you change to "turn off the open side menu by gesture"?  Thanks.

**Comment by Jaafar-abusair** [comment]
Hi @tiffanyricks , I'm using [Wix Navigation Module](https://github.com/wix/react-native-navigation) They have property for that. but do you have the native side menu in your app?

**Comment by tiffanyricks** [comment]
@Jaafar-abusair yes... I am using the native wipe feature.   I will look into the Wix Module.

**Comment by ItsNoHax** [comment]
`recalculateHiddenLayout={true}`

**Comment by jemise111** [comment]
Closing as this has been inactive for a while, and looks to be related to another package

**Comment by code-by** [comment]
> `recalculateHiddenLayout={true}`

where I need to place this?
