### ISSUE TITLE
Stop working when enable remote debug via chrome

### ISSUE THREAD

**Issue by lednhatkhanh** [jemise111/react-native-swipe-list-view#86]
It's working normally until I turn on the remote debug via chrome, it stops working.

I mean, I just simply can't swift, and I haven't implement any functions to handle the swift so I don't know if they're still working or not, I will update the post after I tried it.

Windows.
React native 0.39
Android development.

**Comment by jemise111** [comment]
Hey @lednhatkhanh I don't have a Windows machine so it's tough for me to debug this but I just confirmed that remote debugging with an Android simulator is working just fine on my mac (although it is very laggy that's just an issue with Android simulator + chrome debugging, not this package).

I'm also not sure I understand your issue. Could you may post the code you're using and I can try to reproduce it.

![http://g.recordit.co/JjmZ8Voqpq.gif](http://g.recordit.co/JjmZ8Voqpq.gif)

**Comment by jemise111** [comment]
Closing as I haven't heard anything on this in a while
