### ISSUE TITLE
Crash when remove the last item

### ISSUE THREAD

**Issue by Haiwen01** [jemise111/react-native-swipe-list-view#9]
hi,

 I love this project. but recently I used it, and found a issues. I set a right button, when click this right button, the row will close manually. Then I remove the last item, it will crash.  The console is "Cannot read property 'closeRow' of null". I think maybe the "openCellId" out of array. Should the "openCellId" reset when items changed or the row close manually?

Thanks.

**Comment by jemise111** [comment]
Hey @Haiwen01, thanks for reporting. I'll take a look asap but would you be able to post the code you're using to render the SwipeList and remove an item? It'd be a big help. Thanks!

**Comment by jemise111** [comment]
@Haiwen01 good call on the openCellId, fixed this in #12.

Closing this. Let me know if you have any other issues. Thanks!

**Comment by Thorbenandresen** [comment]
Hi Jesse,

I still have this problem in my list with sections.

`cannot read property 'closeRow' of null` (if debugger attached)
`null is not an object (evaluating 'rowMap["+secId+rowId].closeRow")` (if no debugger attached)

```js
<TouchableOpacity style={[styles.backRightBtn, styles.backRightBtnLeft]}
			//onPress={ ()=> this._delete(rowData)}
							onPress={ _ => {
								onDelete(rowData)
								rowMap[`${secId}${rowId}`].closeRow() 
									}}
									>               
								<Text style={styles.backTextWhite}>Delete</Text>
							</TouchableOpacity>
```

Thanks!

**Comment by jemise111** [comment]
@Thorbenandresen I believe that's happening because I'm guessing your ```onDelete``` function removes that index from the dataSource before you tried to close it. If you reversed the order of deleting and closing I don't think you'd have a problem.

In any case I've released an update that safe checks against trying to close a row that no longer exists so if you npm install the latest (0.1.1) you shouldn't have a problem either way. Let me know if you do, thanks!

**Comment by Thorbenandresen** [comment]
@jemise111 again, thank you very much! I really appreciate the effort you put into this. Of all the RN swipeout modules out there, this the most elegant one and the first one which works well for me. Keep up the good work!

**Comment by liamse** [comment]
I have same problem. Add ```rowMap[`${secId}${rowId}`].closeRow()``` in `deleteRow` function solve it for me.
The point is you need to `closeRow` before delete it.
