### ISSUE TITLE
How to adjust how far we should swipe for the row to open?

### ISSUE THREAD

**Issue by THPubs** [jemise111/react-native-swipe-list-view#91]
Right now, we have to swipe past the middle of the row and release for it to open. If we release before that the row will close back. How can we adjust this?

**Comment by jdmunro** [comment]
I think you can use ```leftOpenValue``` and ```rightOpenValue``` to do what you're after.

**Comment by jemise111** [comment]
@THPubs Thanks for the question. I added a prop called `swipeToOpenPercent` that will allow you to adjust the % of the openValue the user needs to swipe past to trigger the row to open.

The default is 50% (halfway) but you can change this to a lower number and I think that will solve your problem.

Just grab the latest release (will be released later today) and give that a shot and if it doesn't work please reopen this and let me know. Thanks!
