### ISSUE TITLE
Deleting the first row leaves remaining rows "swiped"

### ISSUE THREAD

**Issue by booboothefool** [jemise111/react-native-swipe-list-view#96]
![lmaonaiiiasdfasde](https://cloud.githubusercontent.com/assets/13257645/22452355/2aa2dc92-e744-11e6-8cac-d800aa9356b4.gif)

It's a little better with `closeRow()`, but it actually closes the 2nd row (Aug 13, 2017)... not the one that was just deleted. I would expect the "Delete" to not show up on the 2nd row at all after the 1st is deleted.

**Comment by LeAcid** [comment]
Have you come up with a solution for this yet? I am working on one now but it would be awesome if you had one.

**Comment by booboothefool** [comment]
@LeAcid Haven't been able to come up with a solution besides `closeRow()`.

![saaa](https://cloud.githubusercontent.com/assets/13257645/22484506/baed8c80-e7cf-11e6-8ee0-7b3f6767429b.gif)

```
  delete(item, secId, rowId, rowMap) {
    rowMap[`${secId}${rowId}`].closeRow();
    this.setState({ list: _.without(this.state.list, item) });
  }
```

Not really what I want, but it's better than leaving it open. It seems like this was done in the example as well, so it's what the author intended?

**Comment by LeAcid** [comment]
@booboothefool I am using the SwipeRow as a standalone in my list ( seemed easier that way ). I fixed my problem by wrapping the SwipeRow in a View  for each of the items and it no longer passes the state down one.

**Comment by lelup** [comment]
@LeAcid Could you explain in more detail? I have same problem in my project. 
![screen shot 2017-02-24 at 16 50 23](https://cloud.githubusercontent.com/assets/19283388/23298738/6601b760-fab1-11e6-9611-dec246292462.png)

**Comment by jemise111** [comment]
Hey @booboothefool thanks for the question. Unfortunately what you're doing is currently the best way I can think of to achieve delete functionality. One thing that may make this look more smooth is to not animate when the row is closed.

Currently that behavior isn't implemented but maybe you could submit a PR to do so? There's an open PR with a start on this. Have a look here #93 

Thanks!

**Comment by mdramos** [comment]
@booboothefool's method is not working for me.  ```rowMap[`${secId}${rowId}`]``` evaluates to `undefined`.

**Comment by Druux** [comment]
@jemise111 same issue as @mdramos described. I keep the refs to the swipe rows but I can't access any function of them. 
<img width="766" alt="bildschirmfoto 2017-04-23 um 13 00 51" src="https://cloud.githubusercontent.com/assets/9655723/25312919/f305fe0a-2824-11e7-93f0-4be5f1a1733d.png">

**Comment by jemise111** [comment]
Going to close this as its been inactive for a while

**Comment by thanhluantl2304** [comment]
@lelup cho mình hỏi với, bạn đã tìm được cách để fix bug này chưa?
