### ISSUE TITLE
Too sensitive on Android? Can't press the TouchableHighlight.

### ISSUE THREAD

**Issue by booboothefool** [jemise111/react-native-swipe-list-view#97]
```
renderRow={ conversation => (
              <TouchableHighlight underlayColor="gray" onPress={() => Actions.conversation({ conversation })}>
                  ...
              </TouchableHighlight>
            )}
```

I noticed this is awfully hard to press on Android real device. It keeps thinking I am trying to swipe. Have to make sure to press it still, and straight down / perpendicular.

Is there a way to adjust the sensitivity?

**Comment by booboothefool** [comment]
Noticed it has to do with 

```
const DIRECTIONAL_DISTANCE_CHANGE_THRESHOLD = 2;
```

Setting it to 3 gives me the effect I want. Feel like this should be exposed as a prop.

**Comment by chetstone** [comment]
Great catch! Care to send a PR?

**Comment by jemise111** [comment]
@booboothefool @chetstone Thanks for the suggestion. I haven't heard about Android being too sensitive in most cases so I'm not going to change the default threshold number but I will expose the number as a prop so you can adjust this number yourself.

See #106 and use the `directionalDistanceChangeThreshold` prop in the next release (out later today).

Thanks!
