### ISSUE TITLE
Close row when another row starts to swipe

### ISSUE THREAD

**Issue by davideweaver** [jemise111/react-native-swipe-list-view#98]
On the built-in apps on iOS (like Mail), when a row is swiped open to show the Delete action, any touch outside the Delete action causes the currently open row to close. 

I would like to achieve a similar behavior. I'm not sure how we could capture the touch on "any touch outside the Delete action", but I think we could better simulate that by closing the row if another row is touched (not just a full press).

Is there a way to detect a touch on another row and subsequently close the open row?

**Comment by jemise111** [comment]
Hey @davideweaver, if I understand your comment correctly this should be the default behavior of this component. Here is how the example behaves when touching either the open row or any other row:

![](http://g.recordit.co/HQvJ29Bc4g.gif)

Is this not what you are looking for?

**Comment by jemise111** [comment]
Hey @davideweaver, good suggestion! I've added a prop that I think will do what you're looking for. In the next release (which will be later today) set the `closeOnRowBeginSwipe` prop equal to `true` to achieve this behavior:

![](http://g.recordit.co/QbXtBrEcEA.gif)

If this isn't what you were looking for please reopen and let me know, thanks!

**Comment by davideweaver** [comment]
Yes. That models the behavior for Apple apps. Thanks!

On Mar 5, 2017, at 5:11 PM, Jesse Sessler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @davideweaver<https://github.com/davideweaver>, if I understand your comment correctly this should be the default behavior of this component. Here is how the example behaves when touching either the open row or any other row:

[https://camo.githubusercontent.com/232e95708b4d25ddae28bfa21c703ac9f4c9181c/687474703a2f2f672e7265636f726469742e636f2f4851764a3239426334672e676966]<https://camo.githubusercontent.com/232e95708b4d25ddae28bfa21c703ac9f4c9181c/687474703a2f2f672e7265636f726469742e636f2f4851764a3239426334672e676966>

Is this not what you are looking for?
